### ISSUE TITLE
Verify Required Attendees of HfLA Projects' Team Meetings 

### ISSUE THREAD

**Issue by daniellex0** [hackforla/CivicTechJobs#11]
### Dependency

- [x] #35 

### Overview
We need to determine which team members are required to attend which HfLA project team meetings, so that we can create a more accurate project team meetings filter for the upcoming Volunteer Opportunities page.

### Action Items
- [x] Review [team meetings spreadsheet](https://docs.google.com/spreadsheets/d/1xG8yQUeR17mkeClJE5gotpWFoP8z6_rE53fqAWBMpOg/edit#gid=0) (based on Events page schedule) - same colors for same teams; question marks for unclear required attendees
- [x] Add 2 new columns: **required** and **invited/welcome** 
- [x] Reach out to the PM(s) of each team on slack to verify:
   - [x] Which roles their project meetings are for
   - [x] Whether these meetings are "required" or "invited/welcome" (and for which roles, if relevant)

### Resources/Instructions
[Team meeting spreadsheet
](https://docs.google.com/spreadsheets/d/1xG8yQUeR17mkeClJE5gotpWFoP8z6_rE53fqAWBMpOg/edit#gid=0)
[Events page schedule
](https://www.hackforla.org/events/)
[Upcoming Volunteer Opportunities page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=5326%3A26395)

**Comment by ExperimentsInHonesty** [comment]
I moved this issue from hackforla website for us to discuss at next team meeting

**Comment by sharadgaurav7** [comment]
@ExperimentsInHonesty , need your guidance on where this ticket should be queued. Does it even belong to Civic Tech Jobs?

**Comment by kcoronel** [comment]
closing this issue because this has been solved and we are moving to retrieving project meeting time from VRMS.
