### ISSUE TITLE
Completing the Community Profile

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#117]
### Overview

This issue for now will be a discussion on the community profile. A proper user story will be added later.

### Action Items

- [x] Review the community profile for missing items:
  - [x] Description
  - [x] Code of conduct 
  - [x] Repository admins accept content reports 

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
[Community profile](https://github.com/hackforla/CivicTechJobs/community)
[Change repository description ](https://github.community/t/change-repository-description/171748/4)
[Adding a code of conduct to your project](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)
[Managing reported content in your organization's repository](https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-reported-content-in-your-organizations-repository)

**Comment by sdimran** [comment]
@Aveline-art do we need to have the community profile? we mainly use our wiki for this kind of information

**Comment by Aveline-art** [comment]
@sdimran I would say it is something that is nice to have. One immediate advantage is that it standardizes our repo so freelance contributors have an easier way to navigate around our repository. I think it might also has search implications by making our repository easier to find.

**Comment by nooriaali9** [comment]
https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-reported-content-in-your-organizations-repository - Bonnie suggested this link - worked with her and resolved the - _Repository admins accept content reports_

**Comment by nooriaali9** [comment]
@kcoronel - After me saving the details for the Repo admins - it still shows the same status on this checklist - https://github.com/hackforla/CivicTechJobs/community
Not sure how I should proceed, will look into it though.

Also, the description is pending do I pick it up from the MK docs?

_CivicTechJobs will be a platform to help prospective volunteers find interdisciplinary projects that will be useful for their career development while contributing to positive civic impact, and also a CMS (Content Mgmt System) for Hack for LA projects to be able to list their open roles._

Does this look okay? ^^

**Comment by kcoronel** [comment]
The description looks good! And thank you for looking into it, maybe check back in tomorrow/next week.

**Comment by nooriaali9** [comment]
Added the Desc & updated the content reports for our repo
Finished the items that were flagged in the community checklist - https://github.com/hackforla/CivicTechJobs/community

I believe the issue is completed now. @kcoronel please let me know if this is good to close out?
