### ISSUE TITLE
C & C Analysis Posting a Job to Volunteer Sites

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/CivicTechJobs#12]
### Overview
We need a C & C analysis on CMSs from orgs that recruit volunteers so that we know what features we might need outside of what we have already identified as our current project managers' needs.  This issue looks at the process for how volunteer opportunities are posted.  

### Action items
- [ ] Identify the orgs
- [ ] Collect the features including screen shots of their cms

### Resources/Instructions
[C& C template](https://docs.google.com/spreadsheets/d/1ePxxsLpdC4MMvJICyMYljHawhs1j-hpFHZFOtB0fdDc/edit#gid=1259306930)

[CTJ C&C Analysis](https://docs.google.com/spreadsheets/d/1bXbbJvR9SBEiyTfdKeypCTZZkJMwt0Qj9-6QQ6Drdl4/edit?pli=1#gid=1562979043)

#### List of orgs
Volunteer Match	
Idealist	
benefit.design 	
Catchfire	
Allforgood.org	
Golden Volunteer Organization
Deed	
GivingWay

### Criteria evaluated on
Able  to create account to test out uploading of volunteer opps?
Where

**Comment by patula006** [comment]
[Volunteer Orgs C&C Analysis.xlsx](https://github.com/hackforla/CivicTechJobs/files/7008609/Volunteer.Orgs.C.C.Analysis.xlsx)

**Comment by stephaniestahlberg** [comment]
@sdimran @sharadgaurav7 Can you let us know what else you would like added here? Patty reviewed 8 sites and found that she could test-post in 2 of them. She took screenshots. @patula006 can you add the screenshots here? The other websites require a lot more information or money before getting to the posting page.

**Comment by patula006** [comment]
Here is the C & C file which includes screenshots.
[Volunteer Orgs C&C Analysis.xlsx](https://github.com/hackforla/CivicTechJobs/files/7875474/Volunteer.Orgs.C.C.Analysis.xlsx)

**Comment by sdimran** [comment]
moved the xls to the shared drive in order to collaborate together on it. also added to the resources in the ticket 

https://docs.google.com/spreadsheets/d/1bXbbJvR9SBEiyTfdKeypCTZZkJMwt0Qj9-6QQ6Drdl4/edit?pli=1#gid=1562979043

**Comment by patula006** [comment]
Updated the CMS C & C file with links to dashboard examples. Not sure if this is what you are looking for though
[Volunteer Orgs C&C Analysis.xlsx](https://github.com/hackforla/CivicTechJobs/files/7900461/Volunteer.Orgs.C.C.Analysis.xlsx)
.

**Comment by stephaniestahlberg** [comment]
@patula006 Can you include the additions in the Google Sheet document that Danish created and linked above? So we can collaborate on the same doc. Thanks!

**Comment by patula006** [comment]
Yes - it's in the second tab now.
