### ISSUE TITLE
Log in/Sign up pages (UX)

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#122]
### Overview

We need to design a welcoming log in page for both volunteers and team leads to access full capabilities of CTJ website.
*We also need to provide disclaimer somewhere about needing to attend onboarding to receive login info.

### Action Items

- [x] Ideate log in pages
- [x] Present to team
- [x] Edit log in pages
- [x] Add sign up pages
- [x] Present to team
- [x] Add to prototype for usability testing

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

**Comment by sdimran** [comment]
@jenchuu @graceerya can we please include the feature labels for this. if you need to create a new relevant label please do and advise @sharadgaurav7 and I

**Comment by jenchuu** [comment]
> @jenchuu @graceerya can we please include the feature labels for this. if you need to create a new relevant label please do and advise @sharadgaurav7 and I

@sdimran @sharadgaurav7 Should we create a new p-feature for Log in page? Or do you want this under Landing page?

**Comment by sdimran** [comment]
Hi @jenchuu we can feature this as "feature: CMS" as the login screen is our entry point into that. landing page initial will be static and MVP will include the dynamic functionalities we are working on so we will keep the milestone as MVP. let me know if there are any questions.

additionally if possible lets keep the issue assigned to 1 person at a time

> > @jenchuu @graceerya can we please include the feature labels for this. if you need to create a new relevant label please do and advise @sharadgaurav7 and I
> 
> @sdimran @sharadgaurav7 Should we create a new p-feature for Log in page? Or do you want this under Landing page?

**Comment by jenchuu** [comment]
[Login page V2](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A15)

Please see three DESKTOP log in page options for feedback:
1. Split screen w/ Helping doodle illustration
2. Split screen w/ Hero illustration
3. Full screen w/ elements from Hero illustration
![V2 Log in page](https://user-images.githubusercontent.com/88695763/151231368-d142346d-8594-444e-9121-2c2ffaa3118b.png)

Please see three MOBILE log in page options for feedback (only did versions for the Helping doodle illustration):
1. Centered box
2. Without box on full screen
3. Centered box on half screen
![V2 Log in mobile page_Helping doodle](https://user-images.githubusercontent.com/88695763/151231485-a4d67a9a-b6f0-4de2-a28a-eca380e6334f.png)

**Comment by stephaniestahlberg** [comment]
I don't see any usability issues with any of them, and since they are a login page for return users, I don't think we should A/B/C test them. Aesthetically, my preference is for versions 1 or 2 for desktop, and version 3 for mobile.

**Comment by sdimran** [comment]
Hi @jenchuu  i think we have made a decision on the login page based on the prototype feedback. this issue is in links questions and review are we good to move it to done or are there additional questions outstanding?

**Comment by jenchuu** [comment]
@sdimran Hi we need to put back into work in progress since we need to change the log in illustration due to Bonnie's comment.

**Comment by jenchuu** [comment]
**Log in pages:**
<img width="1606" alt="Log in page (desktop and mobile)" src="https://user-images.githubusercontent.com/88695763/155248164-3ae38c7e-ba57-4495-a87f-afd5cd0ebf6f.png">


**Sign up pages:**
<img width="1652" alt="Sign up page (desktop)" src="https://user-images.githubusercontent.com/88695763/155248186-8b5ad784-c2f8-41ae-aeeb-48471cfc0584.png">

<img width="1562" alt="Sign up page (mobile)" src="https://user-images.githubusercontent.com/88695763/155248206-4da3d0c7-7ab8-4da3-875d-0d053a09f0d5.png">

**Comment by sharadgaurav7** [comment]
> **Log in pages:**
> 
> * Changed illustration per Bonnie's feedback about woman in middle
> * Added option for user to switch to Sign up page from here if new
> * Changed button states to disabled for pages with blank form fields with no info added
> 
> <img alt="Log in page (desktop and mobile)" width="1606" src="https://user-images.githubusercontent.com/88695763/155248164-3ae38c7e-ba57-4495-a87f-afd5cd0ebf6f.png">
> 
> **Sign up pages:**
> 
> * Same as above
> * Added filled in form fields to use in prototype
> * Added sign up confirmation page to give user feedback their account was created and explain the next steps
> 
> <img alt="Sign up page (desktop)" width="1652" src="https://user-images.githubusercontent.com/88695763/155248186-8b5ad784-c2f8-41ae-aeeb-48471cfc0584.png">
> 
> <img alt="Sign up page (mobile)" width="1051" src="https://user-images.githubusercontent.com/88695763/155248554-49a6bbbd-b774-410a-9f36-026b1fac0903.png">

@ExperimentsInHonesty , please review and provide feedback.

**Comment by sharadgaurav7** [comment]
@sdimran, and I approve. Closing the issue. 
@jenchuu , @graceerya  we need a separate issue for CMS login screens.

**Comment by jenchuu** [comment]
@sharadgaurav7 @sdimran Can't we keep the pages/screens the same for both log ins?

**Comment by sdimran** [comment]
@jenchuu agreed, we can use the same screens and designs but for the CMS log-in there may be an extra step depending on how authentication for projects will work. after discussions with @sharadgaurav7 @Aveline-art , we are trying to work through the account creation process for projects at hackforLA. project emails already exist unlike user emails so the account creation flow that users go through will not be the same as projects. we would likely be giving them accounts attributed to those emails with a temporary password that they would be able to change (this is where the process would differ and is still in discussion with regards to the CMS) I can drop in on the UX meeting today time permitting and explain further
