### ISSUE TITLE
Survey of new volunteers

### ISSUE THREAD

**Issue by stephaniestahlberg** [hackforla/CivicTechJobs#125]
### Overview

As a researcher, we need to gather data from our target users to better understand who they are, their motivations and expectations when deciding to volunteer with Hack for LA. This information will help us design with the users (the volunteers) in mind, with decisions backed by data. We will continuously survey new volunteers during their onboarding process, and the data will be available for all teams to use.

### Action Items

- [x] Draft the research questions
- [x] Prepare the survey in Google Forms
- [x] Present survey to the team
- [x] Decide on final list of questions with Hack for LA org
- [x] Include survey in the onboarding process

### Resources/Instructions
- [New volunteer survey](https://docs.google.com/forms/d/e/1FAIpQLSdTM20e-XBD3_fmTPlYfkBKT7cv7aKdO1b2yx_OCrbHLCvLog/viewform)
- [Google Form Banner Image](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=2459%3A26104)
- [Google Drive folder where the survey is located](https://drive.google.com/drive/u/4/folders/1MiG9TgTKDjzJyIoS-5fovZuIgppUnzZJ)
- [Resources page on CTJ wiki](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
- #152

**Comment by ExperimentsInHonesty** [comment]
History of volunteer onboarding and project selection research starts with the website team, who has already done quite a bit.  That original research resulted in the slide deck we have now, and the need for clarity about open roles.  You will want to review that. Reach out to Simone from the website team to see if she can find and share that with you.

Quick history is 
1. I used to do the onboarding with no slide deck
1. The website UXRs did some research with new volunteers at the end of a couple of onboardings
1. we recorded and transcribed me doing the onboarding and from that we made a slide deck
1. I have continued to iterate on the slide deck as needed.

Current status
1. Here is my [current slides](https://docs.google.com/presentation/d/127UC7q5JOgc5oPev4bbEdydchany-rVBkPRn4w6DMek/edit#slide=id.gd0de62c6b7_0_185) (I don't use them all) 
2. We are changing the onboarding to use an automated form built by the Tables team
2. We are rearranging the onboarding to work better with this form
3. I am in the middle of making a new deck and I will provide the slides for that.  Its a secondary deck which will be provided to the volunteers after I get finished talking to them, and they are ready to fill out the form, setup 2fa, etc.
4. Then I will be making another deck (would like your teams help with this), which explains the current process for finding a project to work on using the open roles board.

**Comment by stephaniestahlberg** [comment]
Thanks, Bonnie. I have reached out to Simone. Team, please see the draft survey link [here](https://docs.google.com/forms/d/e/1FAIpQLSfFoeWbfe1Jvg1BL5fJliIWdbWnSpCeyrmrdQqJ7ABe8xmIxQ/viewform?usp=sf_link). If you have time to review it to share your thoughts during the team meeting today, that would be great.

**Comment by stephaniestahlberg** [comment]
The current onboarding survey is [here](https://docs.google.com/forms/d/e/1FAIpQLScXnJSyCXgO_RCAuCyOkG4sqGILpAepTlJ0HOaK4H_ccEVmNw/viewform).

@ExperimentsInHonesty Here is the proposed updated onboarding survey. Questions to be removed are crossed out, and new questions are in bold. To see the answer options for the questions we are proposing to add, please see [this](https://docs.google.com/forms/d/e/1FAIpQLSfFoeWbfe1Jvg1BL5fJliIWdbWnSpCeyrmrdQqJ7ABe8xmIxQ/viewform) file. When I hear back from Simone with the research files, I will check if we should make any modifications to these questions. Team, also please feel free to share feedback. Is there anything else we would really like to know about the new volunteers?

**How did you hear about Hack for LA?**
**How familiar were you with Hack for LA before you attended the onboarding meeting?** (can leave this one out if the survey becomes long)
**Where do you look for volunteer opportunities?**
**Why do you want to volunteer with us?**
**Do you know what role(s) you want to volunteer for?**
**How important are each of these criteria to you when selecting a project to volunteer for?**
~ Email ~ (keep it anonymous)
~ Name ~ (keep it anonymous)
~ What are your skillsets? ~
~ Which projects most interest you? ~
~ If not captured by our current projects, what civic issues are of interest to you? ~ (the new volunteers probably do not know much about the projects yet. This question may be better asked of more seasoned volunteers)
~ Which of the following times are you available? ~
~ If not located in PDT (Los Angeles), list your time zone: ~ (we are proposing a different time zone question that just gives us an overview of where in the world volunteers are located, since we don't need to know exactly)
** Which continent do you live in? **
~ Which software tools are you proficient in? ~
**How much experience do you have in the field you want to volunteer in?** (to give us a better sense of our volunteer workforce)
**How much work experience do you have overall?** (same as above)
The remote onboarding session answered all of your questions.
~ Hack for LA has been effective in its communication and outreach during the COVID-19 crisis. ~ (Are the new volunteers the right target group for this question?)
How could the remote onboarding session be improved?
**Ideally, how long do you plan to volunteer with us?**
Is there anything else you would like to share?

Next, I can update the survey in Google Forms.

**Comment by sdimran** [comment]
@stephaniestahlberg just a few comments from my end :

when we ask in the survey for Q6 .  the last entry to valuate in terms of importance is - Project size and importance. what are we referring too when we say importance? I think this would be difficult for a potential volunteer who just attended onboarding to answer as all projects are very important. please let me know if I am thinking on a tangent!

for Q8. we have "Only school/college" as an option but I think we should remove the word "Only" and replace it with either "attending/completed" or some variation of that. thoughts?

**Comment by stephaniestahlberg** [comment]
Thanks @sdimran. I went ahead and made these changes and created a new version of the survey in Google Forms [here](https://docs.google.com/forms/d/e/1FAIpQLSf-FyHf_0l98YT_RtE8vTnbvXuoUg0slYE2eGfybdyo_WL4kg/viewform).

**Comment by stephaniestahlberg** [comment]
@ExperimentsInHonesty [survey](https://docs.google.com/forms/d/e/1FAIpQLSf-FyHf_0l98YT_RtE8vTnbvXuoUg0slYE2eGfybdyo_WL4kg/viewform) ready for your review.

**Comment by sdimran** [comment]
Unnassigned Bonnie so we can work on the format as per @sharadgaurav7 feedback from sundays meeting

**Comment by ExperimentsInHonesty** [comment]
![image](https://user-images.githubusercontent.com/37763229/153772781-d752c549-01d0-44b2-9f44-b61727c0a0dc.png)

**Comment by stephaniestahlberg** [comment]
Comment from Bonnie on the banner: the image is hard to see and understand on mobile. We should select a simpler image.
My comment on this: perhaps the CTJ logo would suffice? Moving that to the center.

@stephaniestahlberg to edit the survey based on the discussion with Bonnie today. Bonnie can review again at next Sunday's meeting.

**Comment by stephaniestahlberg** [comment]
The survey has been updated based on today's discussion with Bonnie. Please see [here](https://docs.google.com/forms/d/e/1FAIpQLSdTM20e-XBD3_fmTPlYfkBKT7cv7aKdO1b2yx_OCrbHLCvLog/viewform).

Pending items to discuss at the next team meeting:
* Review the question on collaboration tools to check if any are missing. Any tools used for data analysis?
* Question on what is important when selecting a project: discuss the project stage item. Bonnie said we can brainstorm to identify all project stages and then decide how to frame them here as a question.

**Comment by stephaniestahlberg** [comment]
Hi @ExperimentsInHonesty the survey is ready for your review - I made the changes we discussed last Sunday. It also includes the new CTJ banner. It would be great to include it in the slides/instructions for the next onboarding session on 2/21. Let me know if there are any proposed changes and I can make them before the onboarding.

**Comment by stephaniestahlberg** [comment]
@ExperimentsInHonesty The new volunteer survey has been finalized after another review with Bonnie. Pending items (for Bonnie) are to: set up the new survey with HfLA's data dashboard, and include the survey link in the onboarding slides.

**Comment by ExperimentsInHonesty** [comment]
Edit the [slide ](https://docs.google.com/presentation/d/1bueC40PkklLSJVPttiFeYJvcB69PgJx8pxZK5G7gzzo/edit#slide=id.g1148b651ead_0_2
)with the link to the survey in the onboarding deck to explain why or something that will encourage them to do it.

**Comment by sdimran** [comment]
> Edit the [slide ](https://docs.google.com/presentation/d/1bueC40PkklLSJVPttiFeYJvcB69PgJx8pxZK5G7gzzo/edit#slide=id.g1148b651ead_0_2)with the link to the survey in the onboarding deck to explain why or something that will encourage them to do it.

@ExperimentsInHonesty i cant seem to give @stephaniestahlberg edit access to the slide deck -- might be because i am also on view only access. I think Stephanie has requested edit access to the link (stephaniegz@gmail.com). can you approve from your end?

**Comment by stephaniestahlberg** [comment]
@ExperimentsInHonesty I added a quick explanation of the survey's purpose onto slide 29.
