### ISSUE TITLE
Tweaking the layout components and utilities

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#126]
### Overview
As a developer, we need to improve our design system by providing industry standards for layouts. For this issue we will add several spacing utilities to transform our layout classes.

### Action Items

- [x] Add gap utilities along with our margin and padding utilities.
- [x] Make sure that the gap utilities do not interfere with margin utilities or the standard 12 column design standard
- [x] If not already, move space utilities to the basics directory under a file named `_spacing.scss`
- [x] Also, add classes to layout that will shift its children to either to the start, center, or end (horizontally). This can probably be done through align-items, an attribute related to flex.

### Resources/Instructions
Please review our frontend architecture before you start.

Also note: it might be better to create a new layout class, maybe .grid-container that uses gaps rather than try to do recalculations based on both margins and gaps. This is fine since most DS uses either one or the other, but almost never both; and it is rare to find a use case for both.

**Comment by NickTSA** [comment]
Updated: 
Standard units of 8px increments
Gap sizes from 0-5 * 8px     

_Also test for compatibility with Browser (safari does not support grid gaps)_
