### ISSUE TITLE
C&C Analysis of Volunteer Sites

### ISSUE THREAD

**Issue by Dendorable** [hackforla/CivicTechJobs#127]
### Dependency
none

**Overview**

We need to review and take a look at other websites which focus on volunteering opportunities so that we understand the ease and flow to improve Civic Tech Jobs

### Action Items

- [x] Compare volunteer sites sign-up option
- [x] Compare ease of accessing volunteer opportunities where possible
- [x] Notate any qualifiers that may be required when searching for opportunities
- [x] Notate the fields that are shown when viewing volunteer opportunities

### Resources/Instructions
allforgood.org
Golden Volunteer app
https://www.joindeed.com/
https://www.givingway.com/
https://www.volunteermatch.org/
https://www.idealist.org/en/
https://www.benefit.design/
https://www.catchafire.org/
http://studentshelping.org/

C&C Analysis of Volunteer Sites
https://docs.google.com/spreadsheets/d/1kqpuEH628RX-pR3crixUmZFxOzLghokd4yfOJkhsndY/edit?usp=sharing

**Comment by Punkin18** [comment]
> **Overview** Compare ease and flow of other volunteer sites.
> 
> ### Action Items
> Compare volunteer sites sign-up option
> 
> ### Action Items
> Compare ease of accessing volunteer opportunities where possible
> 
> ### Action Items
> Notate any qualifiers that may be required when searching for opportunities
> 
> ### Action Items
> Notate the fields that are shown when viewing volunteer opportunities
> 
> REPLACE THIS TEXT -If the issue has already been researched, and the course of action is clear, this will describe the steps. However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.
> 
> ### Resources/Instructions
> Sites reviewed to be added here for reference

Please Revise begore submitting

**Comment by sdimran** [comment]
Hi @Dendorable, trying to understand the scope of this issue: is it related to or an expansion of #12  ? if possible please revise the issue with the following format ;

Dependency:

Overview:

Action Items:

Resource:

**Comment by Dendorable** [comment]
C&C Analysis of Volunteer Sites
https://docs.google.com/spreadsheets/d/1kqpuEH628RX-pR3crixUmZFxOzLghokd4yfOJkhsndY/edit?usp=sharing
