### ISSUE TITLE
Create a security policy

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#129]
### Overview

As a developer, we need to patch vulnerabilities as they come up. For this issue, we will draft and create a security policy, so that we may collect feedback on potential holes in our security without making it public.

### Action Items

- [ ] Create a SECURITY.md file with our security policy.
- [ ] Add a link to it to our README.md and CONTRIBUTING.md

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
[Adding a security policy to your repository](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository)

**Comment by sdimran** [comment]
@Aveline-art  i think we can consider this a good first issue for the new developers to take on, let me know if you agree. if so -- once they have been added to the repo one of them can take this on

**Comment by Aveline-art** [comment]
This might be a bit rough for a new developer since it involves security, and that might require a team discussion on how security flaw feedback is collected.

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of #552
