### ISSUE TITLE
API requirements

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/CivicTechJobs#13]
### Overview
We need to determine what data we will require and who will consume it so that we can get signoff from stakeholders and setup the wireframing team for success.

### Action Items
- [x] Create our database schema.
- [x] After creating the schema, get sign off from:
  - [x] Stakeholders who will be using this
  - [x] Our team, who will be managing this, and using this to speak with stakeholders
- [x] Once sign off is done, create issues in peoplesDepot for them to incorporate the model
- [x] Release dependency on #40  

### Resources/Instructions
[Current tentative schema](https://github.com/hackforla/CivicTechJobs/issues/13#issuecomment-886323790)

**Comment by Aveline-art** [comment]
From the Figma file, it seems that we would need these models:

<ins>Job Posting</ins>
| Item | Data Type |
| ----------- | ----------- |
| Job Title | Char/String |
| Description | String |
| Posted Date | DateTime |
| Associated Project | Project (see below) |

<ins>Project</ins>
| Item | Data Type |
| ----------- | ----------- |
| Project Name | String |
| Project About | String |
| Meeting Times | Meeting Time Array (see below) |

<ins>Meeting Times</ins>
| Item | Data Type |
| ----------- | ----------- |
| Day of Week | String |
| Start Time | Time |
| End Time | Time |
| Team Name* | String |

Team Name means the type of meeting, for example, designer meeting or developer meeting.

**Comment by Aveline-art** [comment]
* Progress: Completed a [tentative schema](https://github.com/hackforla/CivicTechJobs/issues/13#issuecomment-886323790). Next step is to discuss additional models needed for the database.
* Blockers: None so far.
* Availability: Random time here and there.
* ETA: Currently indeterminate until meeting with the team.

**Comment by Aveline-art** [comment]
### Next Steps, July 27, 2021

- [ ] Yes on users
- [ ] No login for seekers. Only admin, and the regular users are job posters
- [ ] Some way to log stats for clicks and other information. Maybe outside library?
- [ ] Look at VRMS documentation

**Comment by Aveline-art** [comment]
* Progress: Added login information to schema.
* Blockers: A method to log stats cannot be decided until we decide on a backend framework. Meeting with VRMS team member will clarify for us whether it is best to move on with Express or an alternative. Also, VRMS documentation did not prove helpful in expanding the schema.
* Availability: Some time here and there.
* ETA: Unsure. Waiting on 2 things. 1) Feedback and input from VRMS team, 2) mockups of Figma and the subsequent discussion with the dev team concerning the mockups.

**Comment by Aveline-art** [comment]
Frontend needs to account for usertime zone when displaying meeting times.

**Comment by Aveline-art** [comment]
[Another Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=9266%3A304) retrieved from #11

**Comment by Aveline-art** [comment]
* Progress: The schema is almost complete. Some of the items from VRMS would need to be discussed, especially the user data, to see if they are applicable to our project. Once the finalized designs come in, we can start working on creating the front and backend.
* Blockers: None so far.
* Availability: 5 hours.
* ETA: Probably by next week!

**Comment by Aveline-art** [comment]
To add to schema: some way to note whether or not a certain meeting is required or recommended for the indicated role

**Comment by Aveline-art** [comment]
* Progress: Working with stakeholder to create MVP requirements for VRMS team.
* Blockers: finding a scheduled time to complete requirements
* Availability: unknown
* ETA: unknown

**Comment by ExperimentsInHonesty** [comment]
projectname | Char/String
projectDescription | String
githubOrgId: number (8 characters)
githubPrimaryRepo: number (9 characters)
githubUrl:
projectStatus: String (Active, OnHold, Completed, Closed)
Hide: Boolean
location: string
dreatedDate:
statusChange: Array with strings  example [date-onhold, date-hidden]
slackUrl | URLString
googleDriveUrl
googleDriveId
hflaWebsiteUrl:
partners:
programAreas: String (
SDGs:
projectLeads | Users
Project Image logo | String
Project Image hero
Project Image link

**Comment by ExperimentsInHonesty** [comment]
### Recurring Events Schema
projectId: (number see Project Table)
name: String
location: String
type: String (team meeting, onboarding, special event)
brigadeId: number
dayOfWeek: String
days of month ????
startTime:
DurationInMin: Number
dateCreated:
dateLastUpdated:
videoConferenceUrl: URL String
mustRoles:  Array of Role Ids (see Roles Table)
shouldRoles : Array of Role Ids (see Roles Table)
couldRoles: Array of Role Ids (see Roles Table)
additional information: String 

### Brigade ID Table


### Roles Table

**Comment by ExperimentsInHonesty** [comment]
Seeker
nameFirst:  String
nameLast: String
email: String (email validation)

Password | Hashed String
Slack Handle | String
Availability | String (?)
Role | Role (see above)
TimeZone | TimeZoneObj

Poster
Email | String
Password | Hashed String
Slack Handle | String
Project | Projects (see above)


Association table (join table)
1 record for every permission granted example
Bonnie is on 10 teams, she has at least 10 records, more if she got upgraded permission for any of those teams.  When permissions are upgraded, it creates a new record, and updates the old permission record to add date ended.
each record contains:
userId, projectId, accessLevel, dateGranted, datedEnded

**Comment by ExperimentsInHonesty** [comment]
Tables that still need to be worked on
Checkins
Events
Roles
Questions

Review the vrms 0.4 schema

**Comment by ExperimentsInHonesty** [comment]
![Meeting Times](https://user-images.githubusercontent.com/37763229/142457609-e72eebdb-a66a-454a-90f0-5012bf7c9e6d.png)

**Comment by ExperimentsInHonesty** [comment]
![Meeting Times](https://user-images.githubusercontent.com/37763229/142457609-e72eebdb-a66a-454a-90f0-5012bf7c9e6d.png)

**Comment by ExperimentsInHonesty** [comment]
Roles

users of role data
- hackforla.org 
  - https://www.hackforla.org/projects/100-automations (Current Team)
  - https://www.hackforla.org/communities-of-practice

**Comment by drubgrubby** [comment]
Not Included from VRMS:

### User table:

V3
  accessLevel: { type: String, default: "user" } // We're making a join table
newMember: { type: Boolean },
attendanceReason: { type: String },
projects: // Creating join table
managedProjects: // This will be in join table

v4
LocationZone
ActiveStatus
IsAdmin

**Comment by Aveline-art** [comment]
https://lucid.app/publicSegments/view/7531ed46-77d2-4b91-a09c-b18f9f210980/image.png

**Comment by Aveline-art** [comment]
# API calls

## GET

### Project data
Input: project id
Output: project name, project description, logo, hero image, icon

Questions
1. When someone wants to know more information about a project, where should a link lead them to? Slack, GitHub Repo, GH read me, or the website?
2. If we want to display communities of practice information, how will we be able to tell the difference between a CoP and a project to display only CoPs on our landing page? Would we need to save specific ids into our backened?
3. What is the hide field for?

### Auth data
Input: username, password
Output: auth token, user id

### User data
Input: user id
Output: user status id, user status name, desired roles, current skills, target skills, availability, time zone

Questions
1. When a seeker notices a posting that they want to respond to, where do they go next? What information should the poster needs to know about the seeker?

### Role data
Input: role id
Output: name, description, responsibilities, qualifications

Input: nothing
Output: an array of roles

Questions
1. Roles needs to be associated with a community of practice because we need to display which community a role belongs to for future versions of our landing page.

### Reoccurring events/meetingtimes
Input: project id
Output: list of reoccurring events for that project in an array where each index is an object with the following: name, day of week, start time, duration, must/should/could roles

## PUT/UPDATE

### User
Input: desired roles, availability

Question:
1. Do we still need to gather information on the user's experience level? If so, the database schema of the peoplesDepot does not collect that information.

**Comment by Aveline-art** [comment]
Closed because completed. Further work has been moved to hackforla/peopledepot#2
