### ISSUE TITLE
Propose multi-page architecture

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#132]
### Overview
As a developer, we need to update our architecture to meet the needs of the product we want to deliver. For this issue we will research and gather information on leveraging React/Django to create a multi-page product that is CTJ.

### Action Items

- [x] Gather stakeholder and team thoughts on how urls should work
- [x] Decide on how to create multi-page architecture
- [x] Update the wiki on architecture as needed

### Resources/Instructions
React is known for pioneering [single page apps](https://en.wikipedia.org/wiki/Single-page_application). React works by dynamically transforming the interface through changes in the app's state variables. Therefore, the default React package does not have a way to navigate to a different webpage via url*. The first action item asks whether this feature is desirable as part of our MVP.

The second action item would be a formal proposal on how to meet the needs collected from the first action item. React itself has an associated, well-supported library called ReactRouter that can detect url changes to change the app's state. This is one avenue to achieve multi-page architecture. Another would be to leverage Django's views, essentially rendering one view per web page. Either of these options should suffice, so when forming the proposal, take a good look at the docs and determine which one best fit our project's needs.

*This is a simplification.

**Comment by Aveline-art** [comment]
Questions for all teams:

1. Should we have one url per page? Would each project/posting have its own page/url?
2. Should a user be able to send a direct link to a posting to "share" this opportunity on social media?

Questions for development team:

- Django views as pages, or react router as pages? At a glance:
  - Django pros: does not require additional dependencies | cons: requires considerable set-up; requires one view per webpage; cannot take advantage of Django templates
  - React router pros: built to support react; highly customizable and reusable; easy to translate from userflow diagrams | cons: extra dependency; larger learning curve than Django views

**Comment by stephaniestahlberg** [comment]
@Aveline-art it does seem like a good idea for users to be able to send a direct link to a posting, so they can easily share the posting.

**Comment by sdimran** [comment]
@sharadgaurav7  something for us to discuss further and give feedback to Ava for

**Comment by Aveline-art** [comment]
@sdimran To give some context on urls:

Urls provide gateways to access a page or a page's state. To clarify the difference between a page and page's state, let's use GitHub as an example.

- The url for this issue is: `https://github.com/hackforla/CivicTechJobs/issues/132`
- The url for a comment on this issue is: `https://github.com/hackforla/CivicTechJobs/issues/132#issuecomment-1031023605`

Notice how both links, when visited, goes to essentially the same webpage. The only difference is that the latter url centers your screen to a specific comment and highlights it.

Now, a webpage's state is not always tied to a url. For instance https://github.com/ looks different depending on whether you are logged in or not:

<details>
<summary>Not logged in</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/153347650-e47a4328-0c7c-4a06-a037-dc1f14f93474.png" width="600" length="300" />
<br>
</details>

<details>
<summary>Logged in</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/153347677-10f38f98-bdc9-4249-b2e5-b6c7387b82a2.png" width="600" length="300" />
<br>
</details>

So why is this relevant? So far the design team has made multiple figma-pages. Because of the way urls work, we can have options to have multple figma-pages share the same url, or have the same figma-page use different urls. As a matter of fact, we can even lock certain pages so that users cannot see them without logging in. (For an example, if you tried to visit this url, https://github.com/settings/profile, without logging it, you will be redirected to GitHub's login page).

**Comment by sdimran** [comment]
we will be using the method: redacted version of shared link -- they will need to go through the qualifier page and go through the normal process

**Comment by sharadgaurav7** [comment]
@Aveline-art , is this issue being worked on? Are there any additional questions for the product team? If not, should we move this issue to Done?

**Comment by Aveline-art** [comment]
This issue is currently under review by development via pull request. It should stay in the backlog until the pull request is ready for merging.
