### ISSUE TITLE
review any issues that are in the new issue approval column](https://github.com/hackforla/CivicTechJobs/projects/1#column-10928272)

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#136]

**Comment by sdimran** [comment]
@jenchuu  not sure what this issue is but if it was created by accident can we close it?

**Comment by sharadgaurav7** [comment]
@Aveline-art , are you able to delete this issue?

**Comment by Aveline-art** [comment]
We can, but I do also want to note that it is also possible to recycle issues by giving them a fresh title and body.
