### ISSUE TITLE
Change our existing fallback font

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#137]
### Overview
As a developer, we need to make sure that our website is presentable to users. For this issue, we will change our fallback font to one that matches our existing Roboto the best.

### Action Items

- [x] Locate areas of our css codebase that uses `font-family` for styling.
- [x] Remove all fonts other than Roboto
- [x] Then, next to Roboto add these new fallback fonts: Tahoma, Verdana, sans-serif

### Resources/Instructions
[CSS Basics: Fallback Font Stacks for More Robust Web Typography](https://css-tricks.com/css-basics-fallback-font-stacks-robust-web-typography/)
[CSS Font Fallbacks](https://www.w3schools.com/css/css_font_fallbacks.asp)

Note: DO NOT add fallback fonts to the font-face (`_font.scss` file). This css at-property defines the font. Adding more fonts to it will redefine it such that it will not be "Roboto" any longer.

**Comment by jenchuu** [comment]
@Aveline-art 
Let's use Tahoma as the fallback font for Roboto web font that we are using for our website.

Please see details below and confirm ok!
(https://meowni.ca/font-style-matcher/
)
![Tahoma fallback font vs Roboto web font](https://user-images.githubusercontent.com/88695763/152217449-737c3d54-f45d-4f61-a2c9-44dbda2f0428.png)

**Comment by sdimran** [comment]
This is good to begin work on - Thanks!
