### ISSUE TITLE
Accessibility: Update Close Button component

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#138]
### Overview
As a developer, we need to make sure that our components are accessible as much as humanly possible. For this issue we will update our <CloseButton /> component for accessibility.

### Action Items

- [x] Wrap the CloseButton with <button> html tags
- [x] For the `<img>` tag, add an appropriate alt text (which might be blank, if it is purely decorative)
- [ ] Perform other tasks as needed to ensure accessibility, such as aria labels

### Resources/Instructions
[3.5 Button](https://www.w3.org/TR/wai-aria-practices-1.1/#button)

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of #552
