### ISSUE TITLE
User Test/Research CMS Wireframe

### ISSUE THREAD

**Issue by sharadgaurav7** [hackforla/CivicTechJobs#145]
### Dependency

- [x] #12 
- [x] #139 

### Overview

Based on the requirements, product team has created a wireframe of the potential CMS system that will help product managers, and team leads to post/edit/remove volunteer opportunities within their project. We need to collect more data on other features, and user flow that this CMS needs to have. 

### Action Items

- [x] Review the wireframe created by the product team
- [x] Create a research plan, and share with the team
- [x] Recruit participants
- [x] Conduct research

### Resources/Instructions
- [CMS Wireframe](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=114%3A51437)
- [CMS Research Plan](https://docs.google.com/document/d/1OiLjlT1huexBZL7vcqNBqTbQCDULf_zN4AYWkWEv_0k/edit)
- [CMS user sessions' notes](https://docs.google.com/spreadsheets/d/1NCZfC5lLpSxaY8RTQqEboBwQweNMKiiX_1k0DUa1y-M/edit#gid=1364168455)
- [CMS Research folder](https://drive.google.com/drive/u/0/folders/1dOOZUgNzlsgtsq-KnmtfgbB6p2LqYzMG)
- [C&C template](https://docs.google.com/spreadsheets/d/1ePxxsLpdC4MMvJICyMYljHawhs1j-hpFHZFOtB0fdDc/edit#gid=1259306930)
- [CTJ C&C Analysis](https://docs.google.com/spreadsheets/d/1bXbbJvR9SBEiyTfdKeypCTZZkJMwt0Qj9-6QQ6Drdl4/edit?pli=1#gid=1562979043)

**Comment by patula006** [comment]
3/1/22 Discussed Sharod updating the CMS Figma design:

- Include timezone (probably best to use PST)
- Label "Dashboard" on the left side and "enter roles" on the right [this last part is not exact - I do not recall what Sharod mentioned calling the right side of the page]
- add project cards as per Stephanie's comment
- notes can be found [here](https://docs.google.com/document/d/15ZAPbbp3yq1nbWwvbldzX0O5quBAnuKQWQu357Qsaz0/edit):

**Comment by sharadgaurav7** [comment]
@patula006 , have moved your research plan to the shared drive. Adding the file under resources on the issue description. 
https://docs.google.com/document/d/1OiLjlT1huexBZL7vcqNBqTbQCDULf_zN4AYWkWEv_0k/edit

**Comment by stephaniestahlberg** [comment]
The research team has concluded the research with 11 participants from different CoPs. We are working on analyzing the findings now to create a presentation for the team.

**Comment by sdimran** [comment]
@stephaniestahlberg @Dendorable the wireframe and research is completed, can we create a new issue to track the presentation of the findings this way we can mark this as done as it is a dependency for #179 which is in progress
