### ISSUE TITLE
New Issue Practice (Onboarding)

### ISSUE THREAD

**Issue by janzenmolina** [hackforla/CivicTechJobs#146]
### Dependency

- [ ] [](https://github.com/hackforla/CivicTechJobs/issues/144)

### Overview

The quick brown fox

### Action Items

- [ ] This thing
- [ ] That thing

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

**Comment by sdimran** [comment]
I think we can close this issue @janzenmolina
