### ISSUE TITLE
Create wiki from template

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/CivicTechJobs#15]
### Overview
We need to use the wiki template that other projects are using so that when people move between projects they can find stuff and also because it's easier to know what you need.

### Action Items
- [ ] Clone current wiki to ensure no data is lost
- [ ] Copy template wiki to project wiki

### Resources/Instructions
https://github.com/hackforla/CivicTechJobs/issues/7
[draft guide for copying the template wiki](https://github.com/hackforla/product-management/issues/25)

**Comment by arghmatey** [comment]
Updated wiki with template wiki. Saved old wiki with links locally on machine if any of that information is needed to fill out the template.

**Comment by arghmatey** [comment]
Discussed during 7/27 meeting. This issue will be closed and a new issue will be created to assign wiki pages to be filled out.
