### ISSUE TITLE
Add sign-in through 3rd party apps

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#151]
### Dependency

- [ ] This will be a post MVP1 task (will depend on MVP launch) 

### Overview

As a developer we need to meet stakeholder needs. For this issue, we will add sign-in through 3rd party applications to our product.

### Action Items

- [ ] Compile the necessary settings and modifications we would need to enable sign-in through these 3rd party websites  
  - [ ] GitHub
  - [ ] Google

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
[Google: Account linking with Google Sign-In ](https://developers.google.com/assistant/identity/google-sign-in)
[GitHub: Authorizing OAuth Apps](https://docs.github.com/en/developers/apps/building-oauth-apps/authorizing-oauth-apps)

**Comment by Aveline-art** [comment]
Questions for the team:

1. I am not sure this issue has a high enough scope to adversely affect other developer issues. On the other hand, websites can change their authorization policy at the drop of the a hat (for example, GitHub only allows PAT tokens for API access as of last year). Therefore, it is my opinion that this issue should only be done as we near MVP.

**Comment by sharadgaurav7** [comment]
@Aveline-art , will you please re-write the objective and explain why do we need the 3rd party sign-in, or what is it going to accomplish. 
NOT URGENT :)

**Comment by Aveline-art** [comment]
@sharadgaurav7 @sdimran I just noticed this is marked with 02 milestone, but is explicitly a post MVP issue. Just want to make sure there is not an error.

**Comment by kcoronel** [comment]
Test

**Comment by nooriaali9** [comment]
At the moment HackforLA prefers not to use 3rd party apps for sign in. If this changes, we will open a new ticket accordingly.
