### ISSUE TITLE
Onboarded User Flow for usability test (UX)

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#161]
### Overview

As a UX Designer we to test the Onboarded User Flow prototype to gain necessary data and insights to inform our design decisions and iterations, thereby improving users' experience. For this issue, we will create a limited Onboarded User Flow prototype in Figma and handoff to the UX Researchers to start testing.

**Desktop flow

### Action Items

- [x] Finish each page revisions
- [x] Connect pages in Figma to create prototype
- [x] Share with UXRs to review and do test run
- [x] Make edits accordingly
- [x] Share with UXRs for review

### Resources/Instructions

[Onboarded User Flow (desktop)](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A16)
[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
[Usability Testing - New Volunteers Folder](https://drive.google.com/drive/folders/1NAF5p6IB4y8H5vMqUTuY0p0X_E9I6WI3?usp=drive_link)

**Comment by sdimran** [comment]
@jenchuu @graceerya this ticket hasnt been touched since March 8th but we conducted the testing and already have the results. am i correct in my understanding? if so please update this ticket with the relevent information (links, resources etc) and we can close it

**Comment by kcoronel** [comment]
closing this issue as this has been completed.
