### ISSUE TITLE
Provide Landing Page Image as Single SVG

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#163]
### Dependency

- [x] #73 

### Overview
As a a developer we would like to have a single whole image to work with rather than puzzle pieces so that images are simpler to replace. For this issue we will create a single SVG for the landing page.

#### Designers

- [x] Add to the Figma assets the full background image from the landing page
- [x] Return the issue back into new issue approval for developer clean-up.
- [x] Replace UI role to frontend role.

#### Developers

- [x] Take the newly created background and replace it with the image on our landing page
- [x] This issue can be done in conjunction with #226 as fixing one will likely fix the other

### Resources/Instructions
[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

**Comment by sharadgaurav7** [comment]
@Aveline-art , the dependency with this issue is cleared. Moving this to prioritized backlog, and changing the role to UX Design.

**Comment by NickTSA** [comment]
@jenchuu @Aveline-art Should this have a similar background file for mobile view as well?

**Comment by Aveline-art** [comment]
@jenchuu I'm not sure what happened to this, but @NickTSA pointed out that we also would need to provide the grouped image in mobile as well, since the mobile version is not directly proportionate. I'm sorry; it has completely escaped my mind.

@NickTSA I'm going to unassign you and return this back to design. Feel free to look for another issue to take.

**Comment by jenchuu** [comment]
@NickTSA @Aveline-art No worries! This has been fixed; please take a look at the Figma and let me know if this work for you guys now.
Grouped Light tan and Tan background for both Desktop and Mobile is labeled: Background

Ex below
<img width="619" alt="Background (Light tan and Tan elements)" src="https://user-images.githubusercontent.com/88695763/159592602-e0563a7c-31b6-483d-817f-2e6890e03210.png">
