### ISSUE TITLE
How to join page (UX)

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#164]
### Overview

As a UX Designer, we need to help new potential volunteers understand the steps of how to join Civic Tech Jobs.
We will create an informative How to join page with illustrations and potentially a FAQ section at the bottom for new potential volunteers.

### Action Items

- [x] Ideate via wireframes
- [x] Discuss ideations among designers
- [x] Select and annotate designs
- [x] Present to team
- [x] Decide on hi-fi design
- [x] Add to prototype for testing

### Resources/Instructions

[How to join page (Figma)](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=2423%3A29534)

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

**Comment by jenchuu** [comment]
@sdimran @sharadgaurav7 Can we create new P-feature: How to join page? or should we put under P-feature: Navigation ?

**Comment by sdimran** [comment]
> @sdimran @sharadgaurav7 Can we create new P-feature: How to join page? or should we put under P-feature: Navigation ?

We can create a new feature for the how to join page

**Comment by graceerya** [comment]
These are the designs for the How to Join page as finalized by the design team:

**Desktop:**

- Explored a dark blue background but decided to continue with tan hero image
- Added tooltip next to Step 1 that defines CoP

**Mobile:**

- Kept general design of hero image but removed dots for more space and centered all content
- Also includes tooltip for Step 1 to define CoP
- Line runs through all steps to carry over the "timeline" idea on the desktop version
- Like desktop version, includes "back to top" button

![Frame 893](https://user-images.githubusercontent.com/64109227/155279425-44315bb6-fd6f-4717-9672-00e7c0aa99fb.png)

**Comment by sharadgaurav7** [comment]
@ExperimentsInHonesty, we wanted you to take a look at this concept and let us know if you approve.

**Comment by sharadgaurav7** [comment]
> 

@ExperimentsInHonesty, we wanted you to take a look at this concept and let us know if you approve.

**Comment by sharadgaurav7** [comment]
> These are the designs for the How to Join page as finalized by the design team:
> 
> **Desktop:**
> 
> * Explored a dark blue background but decided to continue with tan hero image
> * Added tooltip next to Step 1 that defines CoP
> 
> **Mobile:**
> 
> * Kept general design of hero image but removed dots for more space and centered all content
> * Also includes tooltip for Step 1 to define CoP
> * Line runs through all steps to carry over the "timeline" idea on the desktop version
> * Like desktop version, includes "back to top" button
> 
> ![Frame 893](https://user-images.githubusercontent.com/64109227/155279425-44315bb6-fd6f-4717-9672-00e7c0aa99fb.png)

@ExperimentsInHonesty , we need you to review this concept and provide you approval.

**Comment by sdimran** [comment]
Hi @jenchuu, we had some discussions with Bonnie today around this issue and have some feedback, please see below. the numbers reflect which step above I am referring too:

1. we can remove the mentions about meeting zoom links from CoP

2. Reviewed this one with Bonnie and reworded the step for clarity. i have included the note in figma as well beside this screen : 
       - Select which roles you are interested in and input your weekly availability to see all your project matches. Explore the 
         results to see if the skills and other details are a good fit.


4. can we change this to : 
Onboarding is a mandatory zoom session which all prospective volunteers must register and attend **prior to observing project meetings and taking part in a project**. (the second sentence can remain the same)

5. Convert this to a checklist and include some line such as "come back to civictechjobs.org and sign in to see full project details"
hyperlink "sign in" to the sign in page
ex.
            - Attend the mandatory onboarding
            - Come back to Civictechjobs.org and sign in to see full project and role descriptions
            - Contact the projects Product manager on slack to observe/join the team meetings (this can be rephrased, open to suggestions) 


FAQ question:
Q: Im logged in, how come I cant see full project details?
A: Have you attended an Onboarding? if you have not then your account will not be able to see the full role details (lets elaborate more on this)

Overall, lets try to trim down on the words for the steps where possible to make it concise and to the point 

Let @sharadgaurav7  or I know if there are any other questions for this feedback

**Comment by ExperimentsInHonesty** [comment]
I gave some rewording to the pms 

2. Select which roles you are interested in and input your weekly availability to see all your project matches.   Explore the results to see if the skills and other details are a good fit.

**Comment by jenchuu** [comment]
@ExperimentsInHonesty @sdimran @sharadgaurav7 Thank you for the feedback. To confirm, we are getting rid of the step asking new volunteers to sign up with an account?

**Comment by sdimran** [comment]
@jenchuu I think this was finalized and your questions were answered on our call. is there anything outstanding for this or can we pass it over to the developers to start working on?

**Comment by kcoronel** [comment]
closing this issue as all action items have been completed.
