### ISSUE TITLE
Expand title and paragraph classes to tags

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#167]
### Overview

As a developer we need to ensure that our website uses SEO by using the correct HTML tags for the job. For this issue we will customize our <h#> tags with the appropriate title mixin, so that they can be used in place of the title classes and ensure SEO.

### Action Items

- [x] In our typography basics, customize the <h#> tags with our title mixin. To keep it simple, use title 1 - 6.
- [x] Replace all instances where the title classes are used with the <h#> tag, **if appropriate**!

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
[How To Use Header Tags: SEO Best Practices](https://www.searchenginejournal.com/on-page-seo/header-tags/)

**Comment by sdimran** [comment]
@poorvarathore05  can i get an update on this issue?
Thanks!

**Comment by poorvarathore05** [comment]
Hello @sdimran 
So sorry for the delay in response. I was having some issues with my web packs and was unable to work on that so I discussed them with Ava a couple of times. Now we resolved the problem and the website is up and running on my system.
and I am working on that issue and it's almost done.

Thanks!
