### ISSUE TITLE
New Footer Image

### ISSUE THREAD

**Issue by slavdefense** [hackforla/CivicTechJobs#169]
### Overview

As a developer, we need images that are easier to center so that they can be easy to format and replace. To this issue we will make edits to the images used on our footer.

### Action Items

- [ ] Find the images specified in resources in the footer for the landing page.
- [ ] Trim extra space from the image.

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
[LandingPage](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A7)

**Comment by kcoronel** [comment]
Closing this issue as it no longer seems relevant with updated designs to wireframes.
