### ISSUE TITLE
Logo feedback google form

### ISSUE THREAD

**Issue by sdimran** [hackforla/CivicTechJobs#17]
### Overview
We need a google form to get input from the team regarding the top Logo designs thus far to move forward with so that we can finalize our logo design and color scheme

### Action Items
- [x] Google form ( https://forms.gle/r9jenNSzW8X8SoXn8 )

### Resources/Instructions
Logo Issue (https://github.com/hackforla/CivicTechJobs/issues/8)

**Comment by ihorng** [comment]
Below is the image file of the logo selection for participants to select from.

![CivicTechJobs-Logos-Poll](https://user-images.githubusercontent.com/63479928/127034167-3d9acca5-4e71-454b-984f-e040593b3168.jpg)

**Comment by sdimran** [comment]
Updated Google form link which contains questions and images. @ihorng just wanted to confirm, is each row one (1) design which can be translated for multiple views and platforms based on our discretion (mobile/web/tablet)?

**Comment by ihorng** [comment]
@sdimran yes, each row is one design translated in multiple views & platform

**Comment by sdimran** [comment]
Olivia had posted our google form on the general channel in Slack and the responses were gathered. final results to be discussed and actioned at 8/17/21 meeting
