### ISSUE TITLE
Disclaimer Banner Component (Design System)

### ISSUE THREAD

**Issue by eva32lee** [hackforla/CivicTechJobs#170]
### Overview

As designers, we need to create components of the disclaimer bar used in our designs (i.e. Qualifier Page, Search Page) to insert into the design system and share with the developer team.

### Action Items

- [x] Create floating disclaimer banner for desktop (Qualifier page)
- [x] Create fixed disclaimer banner for desktop (Search page)
- [x] Create floating disclaimer banner for mobile (Qualifier page)
- [x] Create fixed disclaimer banner for mobile (Search page)
- [x] Review/finalize components
- [x] Integrate components into design system

### Resources/Instructions

[CTJ Design System Page in Figma File](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A2)

**Comment by sdimran** [comment]
@eva32lee do we have any details about which components will be created for this under action items? if possible please break it down by those so we can better see the work effort required for this. Thank you!

**Comment by sdimran** [comment]
@jenchuu  @graceerya  @janzenmolina  this was an issue Eva was working on before she left the team. do we have the final component ready for review? if so please post a screenshot and explanation and we can close this task

**Comment by kcoronel** [comment]
Closing this issue as all action items have been completed and see that the Disclaimer Banner is part of the Design System.
