### ISSUE TITLE
Sticky Bar Component (Design System)

### ISSUE THREAD

**Issue by janzenmolina** [hackforla/CivicTechJobs#172]
### Overview

As designers, we need to create components of the sticky bar used in our design for the qualifier page to share with the research and developer teams, where the approved versions will be added to the design system. For reference, sticky is defined as being fixed in position on the page regardless of the user's scroll position. 

### Action Items

- [x] Create sticky bar component with button disabled (desktop) 
- [x] Create sticky bar component with button disabled (mobile) 
- [x] Create sticky bar component with button enabled (desktop) 
- [x] Create sticky bar component with button enabled (mobile) 
- [x] Review components with team and revise based on feedback
- [ ] Finalize components and implement into design system

### Resources/Instructions

[CTJ Design System Figma Page](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A2)
[Sticky Bar Card in Design System](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=2726%3A30588)

**Comment by sdimran** [comment]
@janzenmolina  do we still need this issue? i recall you mentioning during the team meeting it may not be required

**Comment by janzenmolina** [comment]
@sdimran After meeting with the design team, I believe it's still necessary. I'll update the action items list soon with more details about the components that will be created for this issue.

**Comment by sdimran** [comment]
@janzenmolina can you please add the additional details as mentioned above in your comment and let us know so that we can move this from new issue approval to the prioritized backlog?

**Comment by janzenmolina** [comment]
@sdimran Details added, should be ready to move now

**Comment by sdimran** [comment]
This is good to work on. thanks for adding the details @janzenmolina you can assign this to yourself at your convenience.

**Comment by sdimran** [comment]
@janzenmolina  is this task complete? please provide an update

**Comment by kcoronel** [comment]
closing this issue as wireframes for the qualifier page have incorporated a sticky bar component to designs.
