### ISSUE TITLE
Split Cards into Multiple Components

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#175]
### Overview

As a developer we need to keep our codebase clean by keeping a one file per component rule. For this issue we will separate out our cards into different files so that they are easier to find.

### Action Items

- [ ] Find the components in the specified file below.
- [ ] Split the components into different files, both js and scss, named after the components
- [ ] Make sure that the website still runs by fixing all imports and any other errors that arise.
- [ ] Since this is a refactor, the website's appearance should not change.

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
[Cards.js](https://github.com/hackforla/CivicTechJobs/blob/main/app/frontend/src/components/Cards/Cards.js)
[_Cards.scss](https://github.com/hackforla/CivicTechJobs/blob/main/app/frontend/src/components/Cards/_Cards.scss)

**Comment by sdimran** [comment]
@poorvarathore05  can i get an update on this issue?
