### ISSUE TITLE
Identify CTJ metrics based on CMS user research

### ISSUE THREAD

**Issue by stephaniestahlberg** [hackforla/CivicTechJobs#179]
### Dependency

- [x] #145

### Overview

As a researcher, we need to use user research to help us define metrics for evaluating CTJ. We will discuss with PMs and Leads the problems and challenges they face with the current process for posting roles and recruiting at HfLA, and use these responses to define metrics that we can use to compare the old and new systems.

### Action Items

- [x] Discuss and brainstorm problems that people face with the current process for posting and filling roles at Hack for LA. From the perspective of those doing the recruiting
- [x] Gather responses from PMs and Leads during CMS Phase 1 research
- [x] Draft metrics to discuss with the team
- [x] Define final metrics to be used in a survey for PMs and Leads

### Resources/Instructions

[CMS research script](https://docs.google.com/document/d/16gcCSc6VGFsc7qT8Em6kVny8s2t2aaqV-zU-WtmxljY/edit)
[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

**Comment by stephaniestahlberg** [comment]
What are some of the problems and challenges that people have had with the current process for posting and filling roles at Hack for LA? From the perspective of those posting and recruiting. Please share what you know, and that can help guide our discussion with PMs and Leads in the upcoming CMS research.

One problem I have heard from Bonnie:
* Teams get contacted by many people who are not onboarded or actually available. This wastes their time.

Some hypotheses I have:
* It takes a long time to fill a role, because interested volunteers cannot easily find and browse the posted roles. Github is not easy to use for new people, and the roles pages are not easy to find.
* Teams get contacted with many questions that are not answered in the role posting. That is because the postings do not all follow the exact same template (some are missing meeting times, for example), and postings are missing some categories that are very important to prospective volunteers (such as skills/tools they will use).

What else?

**Comment by stephaniestahlberg** [comment]
@sdimran @sharadgaurav7 We have completed the CMS interviews and I will now work on analyzing the responses that are relevant for metrics discussions. So I will move this issue to "In progress."

**Comment by stephaniestahlberg** [comment]
Findings from CMS research that are relevant for creating CMS metrics that compare the current recruiting system to the new CTJ system:

- HfLA volunteers use a variety of methods for recruiting new team members. So if we ask only about the Github roles board, we might miss their preferred/most used methods.

- Other recruiting methods mentioned during interviews: Slack channels, attending a CoP meeting and announcing it there, referrals and connections, during or after onboarding with Bonnie’s guidance.

- The most common recruiting method in our sample is the Github roles board: 5 out of 11 participants have posted themselves. Among the others, 3 are in a team (Website) that has old Github postings that were never taken down, so there is a constant stream of interest. 1 of them could comment on the Github posts.

**List of problems/challenges that CMS research participants mentioned about the Github roles board, and the number of people who mentioned each:**

With 6 research participants that have first-hand experience plus Stephanie’s own experience with posting.
 
**Out of a total of 7 people:**

4 mentions:
- The Github roles board is hard to find (people don’t see it, can’t find it after onboarding, there are no links to it anywhere).

3 mentions:
- They felt the need to recruit through other means as well (Slack channels, at CoP meeting).
- Github post has character limitations: they need to edit down the information to fit. So important information is left out and then is conveyed via Slack/meetings.

2 mentions:
- Finding the format/template was difficult at first. Had to scroll down a lot.
- There is a learning curve for how to frame the post to get interest from candidates.
- Nobody responded to the Github board posting.

1 mention:
- I didn’t have the right permissions to post there. I had to ask somebody else to post.
- There is no option to add where the project is right now – design phases (candidates are interested in this).
- Did not know what would happen next, after posting – will people contact me? Should I close the issue?
- People reach out before being onboarded.

**Challenges with recruiting on Slack:**

1 mention:
- Channels - postings “disappear”. New people when joining may not see older posts. As opposed to Github, which is static.
- Channels - got no response from CoP channel, then attended CoP meeting to recruit.
- Going back and forth on Slack to chat with candidates is tedious. They ask many questions and I have to respond and copy and paste often.

**Challenges with recruiting in general at HfLA:**

2 mentions:
- I keep posts up on Github indefinitely because I don’t know how long volunteers will stay.

1 mention:
- There is a lot of turnover. People sometimes stop showing up after working for a couple of weeks with the team.
- It’s a waste of time to answer questions from candidates who end up not joining.
- The recruitment timeline could be a bit better defined. People come to meetings but then don’t show up again.
- There is no single source to recruit from. The process is not streamlined.

**Comment by sdimran** [comment]
@stephaniestahlberg im going to move this into the ice box until we have reviewed the findings from #145. please see my comment on it. if we are okay to track the presentation in a separate ticket we can close #145 and clear the dependency on it. but until then i will move this back into the ice box. let me know if you have any questions

**Comment by stephaniestahlberg** [comment]
#145 has been closed now. When you move this issue to prioritized backlog, I will assign myself. Thanks.

**Comment by stephaniestahlberg** [comment]
Metrics that will compare the new Civic Tech Jobs recruiting process to the old recruiting process at Hack for LA:

•	Number of recruiting challenges that people face
•	Satisfaction rate with the recruiting process


Examples of impact that we will be able to claim with these metrics:

•	CTJ reduced the number of recruiting challenges by X% for those doing the recruiting and by X% for those joining the organization
•	CTJ increased the satisfaction rate with the recruiting process by X% for those doing the recruiting and by X% for those joining the organization


Methods to collect data on the metrics:

**4-question survey for all of Hack for LA volunteers who have experience with posting on the Github roles board:**
1)	What is your role at Hack for LA?
o	Product/Project Manager
o	Developer
o	Designer
o	Researcher
o	Data Scientist
o	Ops
o	Other

2)	Have you used the Github roles board to post open roles at Hack for LA?
o	No, never
o	Yes, once
o	Yes, multiple times

If yes…
3)	The following is a list of potential challenges that people may face while recruiting at Hack for LA. Please check ALL of the challenges that YOU personally have faced:
o	I feel that the instructions for posting on the Github roles board are not clear enough
o	The character limitations for the Github roles board postings makes it difficult to include all of the important information
o	Potential candidates contact me with a lot of questions
o	I have been contacted by people who are not eligible for the role (e.g. have not attended onboarding yet)
o	The Github roles board is hard for volunteers to find
o	Nobody responded to my Github roles board posting
o	I have felt the need to use other recruiting methods beyond the Github roles board to fill roles
o	I did not have the right permissions/access to post on the Gihub roles board
o	I feel we do not have a single, streamlined recruiting process at Hack for LA
o	The recruiting process as it currently stands is not clear enough to me
o	Other (please write any other challenges not listed)

4)	How satisfied are you with the current recruiting process at Hack for LA?
o	5-point Likert scale: from “Very satisfied” to “very dissatisfied”

**Survey for new volunteers - TBD**

**Comment by sdimran** [comment]
> #145 has been closed now. When you move this issue to prioritized backlog, I will assign myself. Thanks.

Hi @stephaniestahlberg , my mistake for missing this -- we can move this over to in progress based on our discussion today

**Comment by stephaniestahlberg** [comment]
Our comparative metrics for CMS were finalized during the meeting with the PMs today, and they are listed in my previous comment above. I am closing this issue and will start working on the survey that will collect data for these metrics.
