### ISSUE TITLE
Onboard & Offboard: Product

### ISSUE THREAD

**Issue by sdimran** [hackforla/CivicTechJobs#181]
### Dependency
- When a new PM joins or leaves the team (see this issue for updates on the recruitment process #218 )

### Overview
We need to have a checklist of items to do when a product manager onboard and offboards so that the process can be consistent and fast.

### Date Updated
(insert date you created this issue and keep updating the date each time the org template change are integrated)

### Action Items
- [ ] Check to see if the org template for this process has new steps in it, and if it does, update this  issue and its template with content and add the last date you updated the template below
- [ ] Copy template to comment below
- [ ] Add name of person
- [ ] Check off as done

```
#### Onboard
- [ ] Slack channel membership
  - [ ] #civictechjobs
- [ ] Add to Google calendar invites
   - [ ] [Monthly Sunday - PM + Bonnie meeting]
   - [ ] [Tuesday - UX Research meeting]
   - [ ] [Tuesday - All-team meeting]
   - [ ] [Tuesday - Design team meeting]
- [ ] Add to team page on Wiki
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read team
        - [ ] Change membership to maintainer
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Civic Tech Jobs - PM
       - [ ] Civic Tech Jobs - UI/UX
       - [ ] Zoom vault
       - [ ] Access to Zoom spreadsheet
- [ ] Add to email address(s)
   - [ ] civictechjobs@hackforla.org
- [ ] Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Train how to 
   - [ ] login to team email account (Strongly suggest adding separate Chrome profile)
   - [ ] setup chrome shortcut for adding profile to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] how to setup and edit calendar invite
```
```
#### Offboard
- [ ] Remove from Google calendar invite
   - [ ] [Monthly Sunday - PM + Bonnie meeting]
   - [ ] [Tuesday - UX Research meeting]
   - [ ] [Tuesday - All-team meeting]
   - [ ] [Tuesday - Design team meeting]
- [ ] WIKI
  - [ ] move to new place on team page
- [ ] 1password setup
   - [ ] remove from team vaults
       - [ ] Civic Tech Jobs - PM
       - [ ] Civic Tech Jobs - UI/UX
       - [ ] Zoom vault
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one.
- [ ] Remove from email address(s)
   - [ ] Civictechjobs@hackforla.org

- [ ] Remove from Social Media Accounts with role assignment
   - [ ] Facebook
```

### Resources/Instructions
- [1password.com](https://hackforla-team.1password.com/vaults/t2yhyfr7o2eylg25kks2rfqk7a/allitems/j6344juihhx7hqhb4ve5hribre)
- [Google Drive](https://drive.google.com/drive/u/0/folders/0AMdnUkSXicNCUk9PVA)
- [Team Roster](https://docs.google.com/spreadsheets/d/11gd0TxEjA-bfzQQILkMDm0A01ZGmN7K7GW10yvaIwQQ/edit)
- Check public and 2FA at [people page](https://github.com/orgs/hackforla/people)
- [ GitHub Team URL](https://github.com/orgs/hackforla/teams/civictechjobs)
   - [base (read)]
   - [write](https://github.com/orgs/hackforla/teams/civictechjobs-write)
   - [maintain](https://github.com/orgs/hackforla/teams/civictechjobs-maintain)
   - [triage]
   - [admin](https://github.com/orgs/hackforla/teams/civictechjobs-admin)
   - [other]
- [WIKI team page](https://github.com/hackforla/CivicTechJobs/wiki/The-Team)
- [Figma](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=0%3A1)
- Shortcut for adding a profile to the desktop:  chrome://settings/manageProfile
- Tutorials
  - [Forward emails to team members](https://github.com/hackforla/product-management/wiki/Forward-emails-to-team-members)
---
[org template](https://raw.githubusercontent.com/hackforla/.github/main/.github/ISSUE_TEMPLATE/onboard---offboard--product.md) updated 2022-02-23
[Changelog](https://github.com/hackforla/product-management/wiki/Onboard-Offboard-Changelog)

**Comment by ExperimentsInHonesty** [comment]
Please perform the offboarding for all former pms and confirm that all the steps are done for karen

**Comment by kcoronel** [comment]
#### Offboard Sharad Gaurav
- [ ] Remove from Google calendar invite
   - [ ] [Monthly Sunday - PM + Bonnie meeting]
   - [ ] [Tuesday - UX Research meeting]
   - [ ] [Tuesday - All-team meeting]
   - [ ] [Tuesday - Design team meeting]
- [ ] WIKI
  - [ ] move to new place on team page
- [ ] 1password setup
   - [ ] remove from team vaults
       - [ ] Civic Tech Jobs - PM
       - [ ] Civic Tech Jobs - UI/UX
       - [ ] Zoom vault
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one.
- [ ] Remove from email address(s)
   - [ ] Civictechjobs@hackforla.org

- [ ] Remove from Social Media Accounts with role assignment
   - [ ] Facebook

**Comment by kcoronel** [comment]
#### Onboard Karen Coronel 

- [ ] Slack channel membership
  - [ ] #civictechjobs
- [ ] Add to Google calendar invites
   - [ ] [Monthly Sunday - PM + Bonnie meeting]
   - [ ] [Tuesday - UX Research meeting]
   - [ ] [Tuesday - All-team meeting]
   - [ ] [Tuesday - Design team meeting]
- [ ] Add to team page on Wiki
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read team
        - [ ] Change membership to maintainer
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Civic Tech Jobs - PM
       - [ ] Civic Tech Jobs - UI/UX
       - [ ] Zoom vault
       - [ ] Access to Zoom spreadsheet
- [ ] Add to email address(s)
   - [ ] civictechjobs@hackforla.org
- [ ] Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Train how to 
   - [ ] login to team email account (Strongly suggest adding separate Chrome profile)
   - [ ] setup chrome shortcut for adding profile to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] how to setup and edit calendar invite

**Comment by kcoronel** [comment]
#### Onboard Salima Yacoubi Soussane
- [ ] Slack channel membership
  - [ ] #civictechjobs
- [ ] Add to Google calendar invites
   - [ ] [Monthly Sunday - PM + Bonnie meeting]
   - [ ] [Tuesday - UX Research meeting]
   - [ ] [Tuesday - All-team meeting]
   - [ ] [Tuesday - Design team meeting]
- [ ] Add to team page on Wiki
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read team
        - [ ] Change membership to maintainer
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Civic Tech Jobs - PM
       - [ ] Civic Tech Jobs - UI/UX
       - [ ] Zoom vault
       - [ ] Access to Zoom spreadsheet
- [ ] Add to email address(s)
   - [ ] civictechjobs@hackforla.org
- [ ] Social Media Accounts with role assignment
   - [ ] Facebook
- [ ] Train how to 
   - [ ] login to team email account (Strongly suggest adding separate Chrome profile)
   - [ ] setup chrome shortcut for adding profile to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] how to setup and edit calendar invite

**Comment by kcoronel** [comment]
duplicate with #375
