### ISSUE TITLE
Design Filters for mobile

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#183]
### Overview

As a UX Designer we need to ensure mobile filters are easy to use. For this issue, we will ideate and design the filters for mobile.

### Action Items

- [ ] Gather mobile filter inspiration
- [ ] Ideate mobile filter solutions (wireframe)
- [ ] Annotate wireframes
- [ ] Present to UXD team for feedback
- [ ] Decide mobile filter design

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

https://dribbble.com/

**Comment by sharadgaurav7** [comment]
@jenchuu can you please add the right feature label

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of https://github.com/hackforla/CivicTechJobs/issues/552
