### ISSUE TITLE
Design "Availability" filter

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#184]
### Overview

As a UX Designer we need to ensure users can quickly and intuitively change their availability when on the search results page. For this issue, we will ideate and design the Availability filter.

### Action Items

- [ ] Gather availability scheduler / filter inspiration
- [ ] Ideate mobile filter solutions (wireframe)
- [ ] Annotate wireframes
- [ ] Present to UXD team for feedback
- [ ] Decide Availability filter design

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

https://dribbble.com/

**Comment by sharadgaurav7** [comment]
@jenchuu can you please add the right feature label

**Comment by sdimran** [comment]
Hi @jenchuu what's the difference between #199 and this issue? looks like it covers the same item

**Comment by jenchuu** [comment]
@sdimran 
You're right; it's same but #199 is formatted the same as the other prioritized issues. Closing this one.
