### ISSUE TITLE
Add Secondary Ghost Button to Design System

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#185]
### Overview

As a UX Designer, we need to ensure consistency across the website and design faster. For this issue, we will add the Secondary button (ghost button) variant to the design system.

### Action Items

- [ ] Find where Secondary buttons used in page designs
- [ ] Create components of Secondary button in "Pending Components to Design System" black rectangle
- [ ] Make variants
- [ ] Check with team before moving to prectangle
- [ ] Create new issue for this component (from template created by Dev team) to handoff to Dev team

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

**Comment by sharadgaurav7** [comment]
@jenchuu can you please add the right feature label

**Comment by sdimran** [comment]
@jenchuu could you explain what a ghost button is for clarification?

**Comment by jenchuu** [comment]
@sdimran Sure, ghost button is button that has an outline but no solid fill. Companies sometimes use these as secondary buttons.

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of https://github.com/hackforla/CivicTechJobs/issues/552
