### ISSUE TITLE
Add Tertiary Button to Design System

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#186]
### Overview

As a UX Designer, we need to ensure consistency across the website and design faster. For this issue, we will add the Tertiary button (bolded, underlined copy) variant to the design system.

### Action Items

- [ ] Find where tertiary buttons used in page designs
- [ ] Create components of Tertiary button in "Pending Components to Design System" black rectangle
- [ ] Make variants
- [ ] Check with team before moving to prectangle
- [ ] Create new issue for this component (from template created by Dev team) to handoff to Dev team

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

**Comment by sharadgaurav7** [comment]
@jenchuu , can you please add the right feature label

**Comment by sdimran** [comment]
@jenchuu could you also explain what the tertiary button is? also should the first action item read : Find where Tertiary buttons used in page designs ?

**Comment by jenchuu** [comment]
@sdimran Tertiary button = third level of buttons. Primary, secondary, tertiary
and fixed that thanks!

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of https://github.com/hackforla/CivicTechJobs/issues/552
