### ISSUE TITLE
Presentation of CMS research findings

### ISSUE THREAD

**Issue by stephaniestahlberg** [hackforla/CivicTechJobs#188]
### Dependency

- [x] #145

### Overview

As a researcher, we need to analyze the findings from our research and prepare a presentation that includes insights and recommendations to deliver to the team.

### Action Items

- [x] Analyze the findings from the research
- [x] Prepare a slide deck for presentation
- [x] Present insights and recommendations to the team

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
[CMS Presentation from 4/12/22](https://drive.google.com/drive/u/0/folders/1hioZGbEjIwWMtH1JUoBft6gV-vEuK_Sz)

**Comment by sdimran** [comment]
Included Research presentation recording in the resources sections (google drive link)

**Comment by sdimran** [comment]
@Dendorable @stephaniestahlberg @MariaElizabeth04  great work on putting this together!  Since we have presented the findings we can close this issue. we will refine and add the findings to our CMS issue #53 as requirements as well as add them to our requirements documentation. @sharadgaurav7
