### ISSUE TITLE
Research using Service Workers as a caching mechanism

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#189]
### Dependency

- [x] #78
- [x] #77 
- [ ] login page design issue (tbd)
- [ ] all dev issues concerning qualifer and login page (tbd)

### Overview

As a developer we need to investigate technology that can solve problems for our application. For this issue we will research and forward a proposal for how Service Workers can help us achieve our MVP.

### Action Items

- [ ] Read the instructions below to understand our MVP problem
- [ ] View the resources below to perform the necessary research
- [ ] Draft a proposal (in a comment on this issue) on the viability of using Service Workers to solve our MVP problem
- [ ] In a meeting, get tech lead sign off on proposal

### Resources/Instructions

MVP Problem:

As of now, _permanent_ caching of user data is not possible. If a user enters data in the qualifier page, for example, this data disappears upon browser exit. Although browser caching represents a solution, it is not a reliable one as we do not control browser data. Therefore, this issue is to investigate how we can reliable, permanently save user data!

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
[Using Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers)
[Progressive Web Apps](https://web.dev/progressive-web-apps/)
[Progressive Web Application](https://webpack.js.org/guides/progressive-web-application/#adding-workbox)
[Workbox](https://github.com/GoogleChrome/workbox)

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of #552
