### ISSUE TITLE
Add lazy loading capabilities to our codebase

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#190]
### Dependency

- [x] #50

### Overview

As a developer, we ideally would optimize our website's loading whenever possible. For this issue we will leverage webpack and react to lazily load our assets.

### Action Items

- [ ] Find areas on our website where lazy loading can added
- [ ] Add lazy loading to our codebase

### Resources/Instructions

Note: Although lazy loading is quite powerful, it should not be used lightly, as it can be cumbersome to read. Therefore, keep in mind how readable the code becomes when lazy loading is added. If code becomes too unreadable, certain strategies, such as using a wrapper function, might serve as a happy middle-ground between optimized and readable code.

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
[Code-Splitting](https://reactjs.org/docs/code-splitting.html)
[Lazy Loading](https://webpack.js.org/guides/lazy-loading/)

**Comment by Aveline-art** [comment]
@gjagnoor Is this still in progress?

**Comment by gjagnoor** [comment]
Yes this can be closed. This issue was resolved as part of #50
