### ISSUE TITLE
(Roles) Qualifier page revisions

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#193]
### Overview

As a designer, we will delete the banner to decrease confusion and options user can take on page so user focuses on main task of filling out desired roles.

### Action Items

- [x] Delete banner
- [x] Ideate feedback of what it'll look like when user selects one vs multiple roles
- [x] Log ideations and which are best solution(s) and why in GitHub comments below
- [x] Present for feedback
- [x] Decide and implement in Figma
- [x] Log final design decision here before closing issue

### Resources/Instructions

[Design prioritization/breakdown](https://docs.google.com/spreadsheets/d/1au1yWIGonoE-UQfhGBqBVca-SZ5B-QxRYOKsUdykdi4/edit#gid=1431484352)

**Comment by sdimran** [comment]
@stephaniestahlberg , from the research, was one of the other concerns that users did not understand what the wording of the blurb was referring too while they were on the qualifier page? this would line up with the knowledge gap we discussed regarding "how to join". the current text of "Please log in or attend onboarding with Hack for LA to see full details of available opportunities." without the prior knowledge of how to join might be confusing the users who read it.

**Comment by stephaniestahlberg** [comment]
@sdimran Correct, the text can be difficult to understand without prior knowledge of the "how to join" steps. Clearing up those steps early on might resolve the problem on the banner's language. Another finding was that many users missed the banner altogether. Which is what I understand this issue is about. Drawing more attention to the banner would help remind the user that they will need to attend onboarding to see full details.

**Comment by jenchuu** [comment]
Due to timing, we will be moving forward with the below for MVP.

[Qualifier Role page](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=4247%3A18444)

**Notable changes:**
- Deleted banner
    - Why? Distracts users from 2-step qualifier process. We want users to focus on completing this.
- Changed copy
    - Why? Explain to users they have flexibility in searching for roles (either by typing or selecting from dropdown)
- Two flows shown: FIRST for search by accordion dropdown, SECOND for search by type
    - Why? To show developers how the two searches will work/relate to each other.. also showed "no results" page
    - Some questions for Devs are in Figma comments (I @ Ava)

**Ready for review column:**
@sdimran  @sharadgaurav7  @salimays @Aveline-art  Please advise if approved or if the PMs or Devs have any feedback/concerns before I handoff to Dev team. Thanks

**Comment by sdimran** [comment]
Im okay with the above, no concerns for MVP1 here. @Aveline-art  @jenchuu  if you're both okay then lets move forward with this style for role page. 

@jenchuu were you still intending on uploading the bubble selection we went over in the leads meeting?

**Comment by jenchuu** [comment]
@sdimran Yes, please see new, simpler roles multi-chip selection.

@Aveline-art LMK if any concerns with this; I've added to Dev Handoff page in Figma:
[Roles Qualifier Page DEV Handoff](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=4308%3A24016)

**Comment by Aveline-art** [comment]
@jenchuu For the most part, we can handle displaying the role data once we have a general gist of how the text will be arranged. If interested, the list is here: https://github.com/hackforla/CivicTechJobs/issues/252#issuecomment-1140513933

**Comment by sdimran** [comment]
@jenchuu  please update with a view without the data element (showing the # of positions per role)

**Comment by jenchuu** [comment]
Update below:
![Roles qualifier page V12 HANDOFF 2](https://user-images.githubusercontent.com/88695763/178625264-33d0b003-25b0-4093-8642-8369a1c7dd44.png)

**Comment by stephaniestahlberg** [comment]
@sdimran @jenchuu as requested, here is the list of roles at HfLA we have reviewed with Bonnie in the past: it's the 6th question in the [new volunteer survey](https://docs.google.com/forms/d/e/1FAIpQLSdTM20e-XBD3_fmTPlYfkBKT7cv7aKdO1b2yx_OCrbHLCvLog/viewform). Besides these roles, there was one entry under "Other" in another one of our surveys for "Content."

<img width="593" alt="Screen Shot 2022-07-12 at 10 08 28 PM" src="https://user-images.githubusercontent.com/82672972/178655256-82aca5b6-48cd-4336-b16b-89cd00246707.png">

**Comment by jenchuu** [comment]
Updated based on list of roles provided by Stephanie... can you confirm if I have these in the correct CoP categories? @sdimran @ExperimentsInHonesty 

![Roles qualifier page V12 HANDOFF 3](https://user-images.githubusercontent.com/88695763/181134095-e0bf5f75-6de3-443d-8518-1de77ae0db16.png)

**Comment by jenchuu** [comment]
Per our conversation at team lead planning meeting, we are taking away Lead chips!

@sdimran to confirm what the correct list of roles and which categories they belong in...
Do we add UX Writing?
Create category for Other: Marketing, Writing?

**Comment by sdimran** [comment]
UX writing = writing under UX 
Create new CoP called "Community Management"
                   - community managers
                   - marketing professional
                   - fundraising 
                   - administrative staff

**Comment by sdimran** [comment]
clickable prototype to test each view for what users like best (chip vs dropdown) @hkimsummer @adriennedomasin @jenchuu

**Comment by jenchuu** [comment]
> UX writing = writing under UX Create new CoP called "Community Management" - community managers - marketing professional - fundraising - administrative staff

To confirm from our last meeting, we are NOT creating/adding the new CoP at this time right?

**Comment by jenchuu** [comment]
Below is updated Role chips (and what Gabe is using for the Multi-chip Role prototype):
<img width="1637" alt="Roles qualifier page V12 HANDOFF 4" src="https://user-images.githubusercontent.com/88695763/185002623-47e25a30-b3b9-4b0e-8df6-1b22fa1b176e.png">

**Comment by sdimran** [comment]
Ops is used for devops, can be changed to can be Orchestration, administration, Organizational Development. we can test this

**Comment by jenchuu** [comment]
@sdimran Ops for the CoP? Is it not just short for Operations? Not DevOps in Engineering right?

**Comment by jenchuu** [comment]
Below is updated Role multi-chip design. Changed the outline of the chip from black to dark blue for active unselected state: 

![Screen Shot 2022-09-18 at 7 22 10 PM](https://user-images.githubusercontent.com/88695763/190934350-f0b4e936-9568-497b-b111-633fe48d58c5.png)

**Comment by sdimran** [comment]
Hey Jen, apologies for the ambiguous note. i was taking down notes while talking to bonnie during the meeting and didnt submit the rest of them. I just yesterday started feeling better but here they are below:

to answer your question, Ops is for operations yes but speaking to bonnie a better name was needed so lets discuss which of those 3 names we want to go with at our next team meeting. devOps notes is below but it will need to be a separate CoP

additional feedback after going through the page:

under each CoP, there should be CoP lead role (ie. UX practice Lead, Engineering Practice Lead etc.)

- DevOps should be a separate CoP, with the following roles : https://github.com/hackforla/ops/labels?q=role  + DevOps CoP lead

- data science CoP Should have the following roles :  https://github.com/hackforla/data-science/labels?q=role

Product management should have the following roles : 
https://github.com/hackforla/product-management/labels?q=role


suggestion from bonnie : for the chips, we can add a small empty checkbox in the chip to indicate that it is clickable based on feedback from users.
https://www.hackforla.org/?programs=Citizen+Engagement

**Comment by jenchuu** [comment]
@sdimran Thanks for explaining and links to roles. Unfortunately now there are duplicate roles in several CoPs. Can you advise where each role should be?

Also edited design to make it easier for users to understand these are multi-select chips:
- Added + in front of text for active, unselected chips (with blue outline instead of grey so looks less disabled)
- Kept CHECKMARK in front of text for active, selected chips

![Screen Shot 2022-10-04 at 6 45 26 PM](https://user-images.githubusercontent.com/88695763/193950317-8d1b6e88-3d5c-48bd-8845-4a2bdd8a0079.png)

**Comment by Aveline-art** [comment]
> Ops is used for devops, can be changed to can be Orchestration, administration, Organizational Development. we can test this

@sdimran This is way too long, and would require a lot of lift for this single edge case. What do you mean by test this?

**Comment by salimays** [comment]
> @sdimran @salimays Thanks for explaining and linking to roles. Unfortunately now there are duplicate roles in several CoPs. Can you advise where each role should be?
> 
> Data Engineer role is in Data Science and DevOps now per the links given Special Projects Coordinator role is in Product Management and Org Development (Prev Ops) Fundraising role is in Org Development (Prev Ops) and Community Management
> 
> Also edited design to make it easier for users to understand these are multi-select chips:
> 
> * Added + in front of text for active, unselected chips (with blue outline instead of grey so looks less disabled)
> * Kept CHECKMARK in front of text for active, selected chips
> 
> ![Screen Shot 2022-10-04 at 6 56 01 PM](https://user-images.githubusercontent.com/88695763/193951380-6596dc07-7a14-4425-98d0-1cf461e9e028.png)

@sdimran @jenchuu  After discussing this issue with Bonnie, her input is the following:

- There are instances where a role goes into two different departments and it's ok to have the same role appear twice
- The challenge will be for the hiring team to properly define the scope of the role. There is a document in the works that aims at making this task easier. (To be linked here after asking Bonnie again)

**Comment by kcoronel** [comment]
@jenchuu can we close this issue?
