### ISSUE TITLE
(Calendar) Qualifier page revisions

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#194]
### Overview

As a designer, we need to make it intuitive and easy for users to select their availability on the calendar. Here we will fix the calendar availability blocks / instructions.

### Action Items

- [x] Ideate ways to make it intuitive users are selecting their AVAILABILITY (ex. change block color from blue to green, onboarding tooltip on calendar that says "drag to select hours" guiding new users, add clearer instructions at top, etc.)
- [x] Log ideations and which are best solution(s) and why in GitHub comments below
- [x] Present for feedback
- [x] Decide and implement in Figma
- [x] Log final design decision here before closing issue

### Resources/Instructions

[Design prioritization/breakdown](https://docs.google.com/spreadsheets/d/1au1yWIGonoE-UQfhGBqBVca-SZ5B-QxRYOKsUdykdi4/edit#gid=1431484352)

[Calendar Qualifier Page DEV Handoff](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=4308%3A24708)

**Comment by sdimran** [comment]
Hi @janzenmolina, can you post any updates you have regarding this issue in the comments section. it has been a while since there was any activity on it. are there any questions? can discuss in the team meeting today.

**Comment by jenchuu** [comment]
Due to timing and based on conversations with @sdimran , we will be moving forward with the below for MVP... we will work on creating the other calendar view (adding ranges of time) to test against our current MVP design with UXRs for next release.
[Qualifier Calendar page](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=4038%3A18558)

<img width="1594" alt="Calendar qualifier page V11" src="https://user-images.githubusercontent.com/88695763/176312813-f5f7dfef-14f9-4a54-82f0-54ca19f9959f.png">

Notable changes:
- Deleted banner
    - Why? Distracts users from 2-step qualifier process. We want users to focus on completing this.
- Changed copy and added color code (green = available)
    - Why? to simplify instructions and guide user on how to fill out schedule
- Changed availability block color to green (prev blue)
    - Why? Mental model of color green = available... although blue was our brand color, some users were confused in testing

@sdimran @sharadgaurav7 @salimays @Aveline-art Please advise if approved or if the PMs or Devs have any feedback/concerns before I handoff to Dev team. Thanks

**Comment by stephaniestahlberg** [comment]
Thanks, Jen! Will we have a default time zone based on the users' location? Or will the time zone be blank and they must select one before proceeding?

**Comment by jenchuu** [comment]
@stephaniestahlberg Yes, correct; figuring out how/when to ask for user's current location. There's a note above "Q2 Empty / Time zone activated" page... I'm thinking once either 1) when user comes directly onto the calendar page  or 2) when user clicks on time zone dropdown.

**Comment by Aveline-art** [comment]
Looks good to me!

**Comment by sdimran** [comment]
This is good to hand over to Dev @salimays @jenchuu @Aveline-art

**Comment by jenchuu** [comment]
@sdimran @salimays Thanks!

@Aveline-art Added to Dev page in Figma:
[Calendar Qualifier Page Handoff](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=4308%3A24708)

**Comment by jenchuu** [comment]
Screenshots of V12 calendar qualifier page for handoff documentation:
<img width="1536" alt="Calendar qualifier page V12 HANDOFF 1" src="https://user-images.githubusercontent.com/88695763/178557928-b54cd6e5-a180-466a-9447-33162bfb42fd.png">
<img width="1669" alt="Calendar qualifier page V12 HANDOFF 2" src="https://user-images.githubusercontent.com/88695763/178557933-24f119e7-e066-486d-a788-d9db5e8efa7b.png">

**Comment by Aveline-art** [comment]
Closed because issues are done #274
