### ISSUE TITLE
(Skills) Search results page revisions

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#195]
### Overview

As a designer, we need to ensure new volunteers understand what skills are required and what skills they'll learn through volunteering on the project cards on the search results page. We will replace or change the tooltip to a tertiary button tooltip ("Are skills required?") or use similar language of CMS pages ("required" or "willing to learn").

### Action Items

- [ ] Ideate ways to communicate different types of skills (ex. tertiary button tooltip "Are skills required?" or use similar language of CMS pages "required" or "willing to learn")
- [ ] Log ideations and which are best solution(s) and why in GitHub comments below
- [ ] Present for feedback
- [ ] Decide and implement in Figma
- [ ] Log final design decision here before closing issue

### Resources/Instructions

[Design prioritization/breakdown](https://docs.google.com/spreadsheets/d/1au1yWIGonoE-UQfhGBqBVca-SZ5B-QxRYOKsUdykdi4/edit#gid=1431484352)

**Comment by stephaniestahlberg** [comment]
The CMS research has some findings that are relevant for the language around Skills. Let's discuss after we present.

**Comment by sharadgaurav7** [comment]
@stephaniestahlberg , please update this issue with the findings so the UX team will keep records of what was included and why.

**Comment by stephaniestahlberg** [comment]
Findings from CMS research on Skills section:
* Not everyone liked calling this category “Skills”. Some preferred “Technology” or “Tools”.
* Some teams/roles have required skills/tools, while others would place everything under "Willing to learn."

Recommendations based on these findings:
* Allow poster to select between "Skills" or "Technologies and Tools"
* Allow for “required skills” and “willing to learn” to be left empty as needed

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of https://github.com/hackforla/CivicTechJobs/issues/552
