### ISSUE TITLE
(Banner) Search results page revisions

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#197]
### Overview

As a designer, we need users to read the banner to ensure they understand the next steps to join as a volunteer. We will fix the banner and its copy to draw more attention to it and give better clarity over next steps in "how to join" process.

### Action Items

- [x] Ideate ways to draw more attention to banner (ex. change color, tooltip, change banner to alert, change copy to "This is limited view. Create an account and attend onboarding to see full opportunities" and anchor link to step 3 and 4 on How to join page, CTA in banner opens new window with How to join page)
- [x] Log ideations and which are best solution(s) and why in GitHub comments below
- [x] Present for feedback
- [x] Decide and implement in Figma
- [x] Log final design decision here before closing issue

### Resources/Instructions

[Design prioritization/breakdown](https://docs.google.com/spreadsheets/d/1au1yWIGonoE-UQfhGBqBVca-SZ5B-QxRYOKsUdykdi4/edit#gid=1431484352)

**Comment by kcoronel** [comment]
Design wireframes for Search Page are updated with banner for how users can join Hack for LA 

![image](https://github.com/hackforla/CivicTechJobs/assets/38144130/58ddb8c4-34b5-40b4-8343-d69928c6feed)
