### ISSUE TITLE
(Filter) Search results page revisions

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#198]
### Overview

As a designer, we need to present applied filters in digestible way and ensure not too lengthy. We will design what the applied filter section looks like when many time availabilities and other filters are selected (and iterate on applied filter design if necessary).

### Action Items

- [x] Design applied filters based on availability filled out on calendar
- [x] Ideate ways to keep applied filter section concise
- [x] Log ideations and which are best solution(s) and why in GitHub comments below
- [x] Present for feedback
- [x] Decide and implement in Figma
- [x] Log final design decision here before closing issue

### Resources/Instructions

[Design prioritization/breakdown](https://docs.google.com/spreadsheets/d/1au1yWIGonoE-UQfhGBqBVca-SZ5B-QxRYOKsUdykdi4/edit#gid=1431484352)
[Search Page Wireframes](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?type=design&node-id=1-12&mode=design)

**Comment by sdimran** [comment]
Hi Jen, before I approve this one, was this revision based on any particular feedback from the usability testing? I saw on our figma we were using the below notation. is there a reasoning behind the revision? 

![image](https://user-images.githubusercontent.com/7094304/162335544-3e5f8ef6-f169-44dd-8d5e-8b1df1baaf02.png)

**Comment by jenchuu** [comment]
@sdimran No specific feedback from usability test, BUT I'd like to create applied filters as close to what real product will look like.. especially for next usability test. We want to start designing as close to "real life" as possible.

**Comment by sdimran** [comment]
Thanks @jenchuu  for clarifying. this is good to work on.

**Comment by kcoronel** [comment]
Closing this issue as Action Steps have been completed and Search Page wireframes can be found under resources.
