### ISSUE TITLE
(Availability filter) Search results page revisions

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#199]
### Overview

As a designer, we need to allow new volunteers to easily and quickly change their availability from the search page. We will design the Availability filter.

### Action Items

- [x] Ideate ways for user to easily change availability via filter (ex. modal pop up window with calendar, in filter drop down list days and can enter time ranges manually, etc.)
- [x] Log ideations and which are best solution(s) and why in GitHub comments below
- [x] Present for feedback
- [x] Decide and implement in Figma
- [x] Log final design decision here before closing issue

### Resources/Instructions

[Design prioritization/breakdown](https://docs.google.com/spreadsheets/d/1au1yWIGonoE-UQfhGBqBVca-SZ5B-QxRYOKsUdykdi4/edit#gid=1431484352)

**Comment by sdimran** [comment]
@jenchuu  what is the difference between #184  and this issue? looks to cover the same functionality

**Comment by jenchuu** [comment]
@sdimran #184 has been deleted.

**Comment by kcoronel** [comment]
All Action Items have been completed. Wireframes below

![image](https://github.com/hackforla/CivicTechJobs/assets/38144130/16646c3c-060e-4969-b734-d59207ac3aeb)
