### ISSUE TITLE
React 18 migration

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#200]
### Dependency

- [x] #74 
- [x] #96 

### Overview

As a developer, we should utilize the newest technologies as it is more performant and offer enhanced features to support our work. For this issue, we will migrate from React 17 to 18.

### Action Items

- [x] Read the resources below to get updates on React18.
- [x] Migrate over the React18, making code changes as needed. These changes are required:
  - [ ] Use the `useId()` hook to create keys for map rendering, as using index may cause memory leaks in the long term
  - [x] Update react-testing-library to v13+, since it will break after migration (see [note](https://github.com/testing-library/react-testing-library/releases/tag/v13.0.0))

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
[How to Upgrade to React 18](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html)
[React v18.0](https://reactjs.org/blog/2022/03/29/react-v18.html)
[React 18 provides useId API for generating...](https://blog.saeloun.com/2021/12/09/react-18-useid-api)

**Comment by Aveline-art** [comment]
Note to team: migrating to React18 will break our product on Internet Explorer (the browser). Please consider that before moving this issue forward.

**Comment by sdimran** [comment]
@Aveline-art  can you still add the necessary labels before we put this into the icebox -- sharad and i can then review it accordingly for the details. Thanks!

**Comment by Aveline-art** [comment]
There's probably no need to review it now since it is in the icebox and details are liable to change. Can I hold off on this until dependencies are done?

**Comment by Aveline-art** [comment]
Also, it seems to have been moved into new issue approval. Should I move it back? I'm not sure it is ready for approval yet.

**Comment by sdimran** [comment]
Hi Ava my apologies for the late response, I moved it into new issue approval because even if we are not working on this currently, it will be worked on down the line and we should ensure that the necessary details and labels (at the minimum the role and features, and an estimate size which could be changed later) are included for whoever does pick this up when the dependencies are completed. we can discuss in detail at the planning meeting tomorrow if needed as well

**Comment by Aveline-art** [comment]
Returning this back into the icebox due to a new dependency
