### ISSUE TITLE
Collect data and analyze results for CTJ metrics survey - CMS 

### ISSUE THREAD

**Issue by stephaniestahlberg** [hackforla/CivicTechJobs#206]
### Dependency

- [x] #180

### Overview

As a researcher, we need to analyze the results from the survey for PMs and Leads on Hack for LA's current process for filling open roles in their teams to inform our CTJ metrics.

### Action Items

- [x] Advertise the survey until we get enough responses (aiming for at least 30)
- [x] Analyze overall survey results
- [x] Prepare a summary to present to the team
- [x] Share results with the team

### Resources/Instructions

[Research Plan](https://docs.google.com/document/d/1Ke5jL6BBfyC0MRZ5hNJO6dM8lmLgwkq2sbOcliPEQXQ/edit#)
[Survey for volunteers with experience recruiting](https://docs.google.com/forms/d/e/1FAIpQLSdYjRFgj1ahExPelJBXV1OPjOJzuLT2JI50NwazopMPVV2Dgg/viewform)
[Google Sheet with Responses](https://docs.google.com/spreadsheets/d/1RHKozeL1XNb1TuDGtlcEc1uw5_1gUivD0wVV0s2f4pM/edit#gid=1859340605)

**Comment by sdimran** [comment]
thanks for creating this @stephaniestahlberg, I saw the dependency so we can move this into the icebox.

**Comment by sdimran** [comment]
@stephaniestahlberg i noticed the dependency on this has been cleared. therefore I have moved this back into the backlog to be worked on by the research team. Someone from your team can pick this up as neccesary

**Comment by stephaniestahlberg** [comment]
We have a total of 8 responses so far, after advertising the survey in the CoP channels. Bonnie had offered to help by directly messaging people that she knows have recruited at HfLA, and I sent her the message to be forwarded, but I don't know if she has done that. Today I also went on every team's channel on Slack and advertised the survey.

**Comment by hkimsummer** [comment]
- We will conclude this data collection at this point (16 responses). 
- There have been modifications made to the original analysis plan. To run an ANOVA test with this survey design, we would need 240-400 responses, which is unrealistic given the time constraints. Therefore, data will be analyzed in terms of percentages and counts. 
- @sdimran I can present findings from this survey this Tuesday. It will be a fairly short presentation; 10-15 minutes.

**Comment by sdimran** [comment]
Thanks Summer,  lets have another recorded session today on Zoom for our teams reference and findings and also attach the findings presentation to this issue and in the shared drive afterwards

**Comment by hkimsummer** [comment]
On a survey based on 15 responses: 
- The System Usability Scale score was 46.33. This is low; anything below 70 is a cause for concern. However, this simply confirms the need for a new, streamlined system (i.e., CTJ!). 
- Current level of satisfaction with the recruiting process is 2.67/5.00 
- Participants wanted additional features such as tracking views, easier ways to recruit, and easier ways to access open role postings from one's own team (this will be possible with CTJ). 

Slide deck: [link](https://docs.google.com/presentation/d/1eqpe_dNv8K9MP-DAC1D5TNYvR-hZ1MesEXhvVQJ7FV0/edit?usp=sharing)

Presented to the team on August 16; recording available in drive.
