### ISSUE TITLE
(How to join steps) Landing page revisions

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#208]
### Overview

We need to ensure new volunteers understand the correct order of steps when joining Civic Tech Jobs. We will edit landing page or flow to clearly communicate steps on how to join.

### Action Items

- [ ] Ideate ways to communicate "how to join" (ex. GIF animation, summary of concise steps, OR add extra step in flow that shows steps before starting qualifier pages)
- [ ] Log ideations and which are best solution(s) and why in GitHub comments below
- [ ] Present for feedback
- [ ] Decide and implement in Figma
- [ ] Log final design decision here before closing issue

### Resources/Instructions

[Design prioritization/breakdown](https://docs.google.com/spreadsheets/d/1au1yWIGonoE-UQfhGBqBVca-SZ5B-QxRYOKsUdykdi4/edit#gid=1431484352)

**Comment by kcoronel** [comment]
Closing this issue because it has a duplicate in #244
