### ISSUE TITLE
(Steps) How to join page revisions

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#212]
### Overview

We need to ensure new volunteers understand the correct order of steps when joining Civic Tech Jobs. We will edit the How to join page to clearly communicate steps on how to join.

### Action Items

- [ ] Edit steps (combine step 1 and 2, making "browse CoP" a subsection of "choose role and select availability")
- [ ] Ideate ways for user to easily achieve each step (checkbox list that saves, links to each step for easy access, etc.)
- [ ] Log ideations and which are best solution(s) and why in GitHub comments below
- [ ] Present for feedback
- [ ] Decide and implement in Figma
- [ ] Log final design decision here before closing issue

### Resources/Instructions

[Design prioritization/breakdown](https://docs.google.com/spreadsheets/d/1au1yWIGonoE-UQfhGBqBVca-SZ5B-QxRYOKsUdykdi4/edit#gid=1431484352)

**Comment by kcoronel** [comment]
duplicate issue in #244
