### ISSUE TITLE
(Redesign Footer) Landing page revisions

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#216]
### Overview

We need to redesign the footer to communicate our affiliation with Hack for LA and useful resources/info for users. We will add our affiliation with Hack for LA and the Hack for LA logo to the footer... and also figure out if we need to take away the Donate button?
*Per Bonnie, HfLA logo needs to be somewhere on website.. either footer, in an About page, or both.

### Action Items

- [x] Come up with ideations for footer
- [x] Log ideations and which are best solution(s) and why in GitHub comments below
- [x] Present for feedback
- [x] Decide and implement in Figma
- [x] Log final design decision here before closing issue

### Resources/Instructions

[Design prioritization/breakdown](https://docs.google.com/spreadsheets/d/1au1yWIGonoE-UQfhGBqBVca-SZ5B-QxRYOKsUdykdi4/edit#gid=1431484352)

**Comment by sdimran** [comment]
@jenchuu since the  affiliation with HfLA is an Org level requirement, in your discussion with bonnie, did she mention that we NEED to have this even for the initial landing page? if so then this should be a P1 level priority and actioned accordingly. please let me know

**Comment by jenchuu** [comment]
@sdimran Oh, you're right! Please change milestone appropriately then.

**Comment by sdimran** [comment]
Thanks @jenchuu, lets get the Affiliation logo into the footer of our website for the initial landing page. will you need to change the description and action items due to this?
