### ISSUE TITLE
Recruit: Product Manager

### ISSUE THREAD

**Issue by sdimran** [hackforla/CivicTechJobs#218]
### Dependancy
for when we need to recruit a PM

### Overview
We need to recruit a product manager to join the pm team in order to have a pair and a spare.

### Action Items

- [ ] Draft a job posting and put in the comments below

> - [ ]  Get signoff

- [ ]  Update project info on HfLA website (include link here)
- [ ]  Create job posting on Product job board
- [ ]  Post message in CoP slack channel
- [ ]  Speak to org lead and Product CoP lead
- [ ]  https://github.com/hackforla/CivicTechJobs/issues/181

### Resources
[open roles board](https://github.com/hackforla/product-management/projects/8#card-76509448)

**Comment by sdimran** [comment]
onboarding @salimays. have added her to the google drive as well as team roster. @sharadgaurav7  will be assisting with getting her caught up on the project on Sunday based on their availability

**Comment by kcoronel** [comment]
There is a new process for recruitment that utilizes issues within this Kanban board. In order to not cause confusion, I will close this issue.
