### ISSUE TITLE
Recruit UI/UX Researcher

### ISSUE THREAD

**Issue by sdimran** [hackforla/CivicTechJobs#219]
### Dependancy

For when we need to recruit a UX Researcher

### Overview

We need to recruit a UI/UX Researcher who will assist and contribute to the project goals so that we can successfully work towards our MVP and Post MVP

### Action Items

- [ ] Copy the existing post and update the draft to fit the new format for recruitment. Put a comment in this issue.
- [ ] Create job posting on UI/UX job board
- [ ] Copy the template below, and add to a comment and check off as you go on each recruitment

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)
Open Roles board https://github.com/hackforla/UI-UX/projects/2

**Comment by kcoronel** [comment]
There is a new process for recruitment that utilizes issues within this Kanban board. In order to not cause confusion, I will close this issue.
