### ISSUE TITLE
Hero Image for CivicTechJobs for HackforLA website

### ISSUE THREAD

**Issue by sdimran** [hackforla/CivicTechJobs#22]
We need a Hero image for CivicTechJobs which will be displayed as the backdrop on the project card on the HackforLA website. this should be independant of the logo but also embody the project

Action Items
- [x] Hero image  ()

Resources 
https://www.hackforla.org/projects/ballot-nav (see backdrop of ballotnav)

Size requirement
1500 x 700

**Comment by cherrijeong** [comment]
@sdimran we are trying to assign Grace (new designer) to work on the hero image. Jen and Grace are listed as h4la members but have limited access.  Do you mind looking into this and assigning Grace to this task? I also moved the task to In Progress. Their git handles are @jenchuu @graceerya

**Comment by sdimran** [comment]
I have added Jen and Grace to the github repo as contributors and assigned them to the task now!

**Comment by graceerya** [comment]
Hello, here are the hero images! (I'm not sure if this is necessary, but I centered all the images slightly above center in hopes of it working better with the blue gradient that seems to overlay the hero images on the website, just in case.)
![civictechjobs-heroimage-doodles-yellow](https://user-images.githubusercontent.com/64109227/130367741-07a22523-a40a-4868-9ddf-ec442df7c51a.png)
![civictechjobs-heroimage-network-mint](https://user-images.githubusercontent.com/64109227/130367749-770bab7f-e7ae-4dbe-9991-3f94cf363633.png)
![civictechjobs-heroimage-network-blue](https://user-images.githubusercontent.com/64109227/130367753-1eccf1a2-04e8-4582-8d45-7eeaa01b1678.png)
![civictechjobs-heroimage-doodles-mint](https://user-images.githubusercontent.com/64109227/130367756-c9b85b6f-81d2-4d7a-b2d0-c65b3fde9bf8.png)

**Comment by arghmatey** [comment]
Hero images have a size requirement of 1500 x 700.

**Comment by jenchuu** [comment]
Grace and I working on finding new FREE hero image possibly from
https://www.vecteezy.com/
https://thenounproject.com/
https://www.freepik.com/

**Comment by graceerya** [comment]
Here is a hero image for the Hack for LA website I made based on illustrations that we are also considering using for the CTJ page. This illustration is free to use with attribution.
![NEW-civictechjobs-heroimage-doodle-mint](https://user-images.githubusercontent.com/64109227/133344958-b8981eb2-dd28-43f4-a7f8-b6fbbfca7662.png)

**Comment by graceerya** [comment]
Here is a new hero image for the Hack for LA website I made; the illustration is one that we are also considering using for the hero image on the CTJ website. It is free to use with attribution. (There are three other illustrations we are brainstorming for the CTJ website hero image which could also be used for this hero image.) ![NEW-civictechjobs-heroimage-doodle-mint](https://user-images.githubusercontent.com/64109227/133345883-b72d2ba6-dedc-4508-b6b2-323f8cb140fb.png)

**Comment by jenchuu** [comment]
Adding another hero image option. Free with attribution:
<a href='https://www.freepik.com/vectors/business'>Business vector created by freepik - www.freepik.com</a>


![CivicTechJobs hero image](https://user-images.githubusercontent.com/88695763/133351498-28db72f0-51e3-4519-a555-a9d73c5dc662.png)

**Comment by sdimran** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSeNgEtFt63FWJaClnkjbbUnYO8lEhO69J-IDAvxOfZgAQJYGg/viewform

**Comment by Aveline-art** [comment]
Here are how the images appear on the website with their current dimensions.

<details>
<summary>Title</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/135208514-86e2d6b9-bcd9-4478-91c4-5d5a36b2f43e.png" width="600" length="300" />
<br>
</details>

<details>
<summary>Title</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/135208523-9bcca1db-303f-40bf-ba8a-97c884ca7dd7.png" width="600" length="300" />
<br>
</details>

**Comment by sdimran** [comment]
Thank you @Aveline-art  for these mock ups! @sharadgaurav7  please take a look at the rendered images above for the hero image on the hackforLA site

**Comment by sdimran** [comment]
> Here is a new hero image for the Hack for LA website I made; the illustration is one that we are also considering using for the hero image on the CTJ website. It is free to use with attribution. (There are three other illustrations we are brainstorming for the CTJ website hero image which could also be used for this hero image.)
> 
> Background color is subject to change. ![NEW-civictechjobs-heroimage-doodle-mint](https://user-images.githubusercontent.com/64109227/133345883-b72d2ba6-dedc-4508-b6b2-323f8cb140fb.png)

@graceerya is it possible to get a mockup of this image with the same color scheme as the CivicTechJobs logo that was decided? one feedback that I would have is if we can include some imagery around "technology" similar to what we have in the second mockup with a woman holding a laptop. let me know your thoughts!

**Comment by jenchuu** [comment]
@sdimran 
That is an older version of the illustration with less diversity. Please see the updated illustration in the link below (Option A). Would you like us to update this illustration with the CTJ color palette? Also I see there is a laptop on the top right (next to the woman's head). Does that work? Or we can make it larger/emphasize it.. let us know!

https://docs.google.com/forms/d/1T_byAc_Qson4rBJnUNArud4aIvDK7c2kPSrZn6TAa1c/edit?ts=6152b05
<img width="1173" alt="Option A" src="https://user-images.githubusercontent.com/88695763/136119642-ddae7360-6498-409f-bdb7-e6fd7e467a51.png">
5

**Comment by sdimran** [comment]
> @sdimran That is an older version of the illustration with less diversity. Please see the updated illustration in the link below (Option A). Would you like us to update this illustration with the CTJ color palette? Also I see there is a laptop on the top right (next to the woman's head). Does that work? Or we can make it larger/emphasize it.. let us know!
> 
> https://docs.google.com/forms/d/1T_byAc_Qson4rBJnUNArud4aIvDK7c2kPSrZn6TAa1c/edit?ts=6152b055 <img alt="Option A" width="1173" src="https://user-images.githubusercontent.com/88695763/136119642-ddae7360-6498-409f-bdb7-e6fd7e467a51.png">

Hi @jenchuu , my apologies for the late response, my travel was delayed and just got back last night. yeah please can we update this option with the CTJ color palette to see what it would look like? also agree with your point to emphasize the laptop above the woman's head to make it more apparent.  @sharadgaurav7  if you have any additional feedback please let us know.

Thanks again!
