### ISSUE TITLE
Design a survey for new volunteers for CTJ metrics

### ISSUE THREAD

**Issue by stephaniestahlberg** [hackforla/CivicTechJobs#221]
### Overview

As a researcher, we need to create a survey for new volunteers so they can evaluate the Hack for LA process for joining teams. These survey responses will generate scores on the CTJ metrics we have defined and can be compared to how people evaluate the joining process using CTJ in the future. 

### Action Items

- [x] Brainstorm ideas for collecting data on metrics
- [x] Write a research plan
- [x] Design the survey
- [x] Finalize CTJ metrics for new volunteers with PMs/team
- [x] Make sure that survey questions would serve as appropriate metrics for both the old and new processes
- [x] Discuss the draft survey with the team and HfLA org
- [x] Edit the survey accordingly
- [x] Test the survey with 2 participants
- [x] Make any final edits needed
- [ ] Send the survey to target respondents

### Resources/Instructions

[Research Plan](https://docs.google.com/document/d/1nTG6pui2fhB9JrQLVJjCwlRA-nhmRkFacZmtE4QD4QM/edit?usp=sharing)
[Survey in Google Forms](https://forms.gle/gVvXyud9sk7fJqA86)

**Comment by MariaElizabeth04** [comment]
Here is the link for the current version of the survey https://forms.gle/PaGERmAthzo3RMUEA

**Comment by MariaElizabeth04** [comment]
@sdimran @sharadgaurav7 This issue has been updated. The research plan and survey have been created and added to resources for you to review and comment on.

**Comment by sdimran** [comment]
some notes : 
in Q1
- the first and last statement are the opposite, so would answering one of them not answer the other? ex. if someone's response was "Strongly agree" for "The steps for joining a project were clear to me." then wouldn't that mean that their response for "Parts of the project joining process were confusing to me." would be "Strongly disagree"? do we need to have both questions

in Q2
- can we make the phrasing "Rate the level of effort it took for you to join a project from 1-5"

we can review with bonnie on sunday

**Comment by stephaniestahlberg** [comment]
Thank you @sdimran. I incorporated your suggestions, and also added a screener question to check that respondents have joined a project in the last 6 months, and therefore are more likely to remember the process well. It's ready for Bonnie's review tomorrow.

**Comment by stephaniestahlberg** [comment]
We reviewed this with Bonnie today and it's good to go. The only change to be made is to remind respondents in question 6 that we're asking about their experience *after* onboarding. @MariaElizabeth04 and I will test the survey with 2 participants this week, and when it's ready Bonnie said she can personally post this on Slack channels to elicit more responses.

**Comment by MariaElizabeth04** [comment]
This survey has been sent to Bonnie and will now be sent to participants!

**Comment by MariaElizabeth04** [comment]
Some of the feedback that we received after testing it with 3 participants:

Participant 1- Recently joined Hack for LA (within 3 months):
