### ISSUE TITLE
New User Flow Prototype (Desktop) for usability test V2

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#222]
### Dependency
Page revisions from first usability test/UXR insights:
- [ ] #209 
- [ ] #210 
- [ ] #211 
- [ ] #217 

### Overview

As a UX Designer we to test our V2 New User Flow prototype to gain necessary data and insights to inform our design decisions and iterations, thereby improving users' experience.

###  Details
 For this issue, we will create a limited New User Flow prototype in Figma and handoff to the UX Researchers for second round of testing.

**Desktop flow only

### Action Items

- [ ] Finish each page revisions
- [ ] Connect pages in Figma to create prototype
- [ ] Share with UXRs to review and do test run
- [ ] Make edits accordingly
- [ ] Share with UXRs for review

### Resources/Instructions

New User Flow Prototype (desktop) TBD

**Comment by jenchuu** [comment]
@stephaniestahlberg Hi this has been created!

**Comment by kcoronel** [comment]
closing this issue as in 2024 we are now using a new user flow found in Figma.
