### ISSUE TITLE
New User Flow Desktop v2 - Usability Testing

### ISSUE THREAD

**Issue by stephaniestahlberg** [hackforla/CivicTechJobs#223]
### Dependency

- [ ] #222

### Overview

As a researcher, we need to test the updated "new volunteer user flow" desktop prototype to identify any pain points and blockers before the pages are fully developed.

### Action Items

- [ ] Discuss goals for usability testing with the team
- [ ] Write a research plan
- [ ] Review the prototype and discuss any questions with the design team
- [ ] Set up Calendly and Zoom link
- [ ] Recruit participants 
- [ ] Conduct research

### Resources/Instructions

[Resources](https://github.com/hackforla/CivicTechJobs/wiki/Resources)

**Comment by sdimran** [comment]
Hi @stephaniestahlberg, is this issue related to Post MVP research as it relies on the completion of #222

**Comment by kcoronel** [comment]
closing this issue as in 2024 we are now using a new user flow found in Figma.
