### ISSUE TITLE
Sign up / Log in pages for MVP

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#231]
### Overview

As a designer, we need to document handoff of MVP Log in and Sign up pages to developers (so they can reference this issues to breakdown and organize dev side into GitHub issues.)

### Action Items

- [ ] Document pages for MVP hand off here

### Resources/Instructions

[MVP Volunteer Log in and Sign up pages](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=3744%3A19748)

Previous UX work towards Log in and Sign up pages:
#122

**Comment by jenchuu** [comment]
Login in pages (desktop and mobile):
<img width="890" alt="Log in (desktop)" src="https://user-images.githubusercontent.com/88695763/165635037-01a659cb-bcea-4015-9b6e-dc67c1b6268c.png">

<img width="346" alt="Log in (mobile)" src="https://user-images.githubusercontent.com/88695763/165635049-09adf591-cdeb-4b3e-840e-91ed88692b7f.png">

**Comment by jenchuu** [comment]
Sign up pages (desktop and mobile):
<img width="1216" alt="Sign up (desktop)" src="https://user-images.githubusercontent.com/88695763/165635171-5672ec4f-be81-4dd6-a064-6df392522943.png">

<img width="538" alt="Sign up (mobile)" src="https://user-images.githubusercontent.com/88695763/165635184-9d1cd066-7bd6-4ec3-b00b-818caa4e86b9.png">

**Comment by jenchuu** [comment]
Assets for Log in and Sign up pages:
<img width="1058" alt="Assets_CTJ Log in and Sign up page" src="https://user-images.githubusercontent.com/88695763/165635234-8bdb5e71-8e23-4c53-9500-91eac9ce72d3.png">

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of https://github.com/hackforla/CivicTechJobs/issues/552
