### ISSUE TITLE
Collect data and analyze results for the CTJ metrics survey - New volunteers

### ISSUE THREAD

**Issue by stephaniestahlberg** [hackforla/CivicTechJobs#238]
### Dependency

- [x] #221

### Overview

As a researcher, we need to analyze the results from the survey on new volunteers' experience with joining a project at HfLA to inform our CTJ metrics.

### Action Items

- [x] Advertise the survey until we get enough responses (aiming for at least 50)
- [x] Analyze overall survey results
- [x] Prepare a summary to present to the team
- [ ] Share results with the team

### Resources/Instructions

[Research Plan](https://docs.google.com/document/d/1nTG6pui2fhB9JrQLVJjCwlRA-nhmRkFacZmtE4QD4QM/edit)
[Survey for volunteers](https://docs.google.com/forms/d/e/1FAIpQLSfGhaaGko52AxkLlbehRKj3YTooQZSKeb-RePUTec8hJFmRlg/viewform)
[Google Sheet with Responses](https://docs.google.com/spreadsheets/d/1yYAJcVRN_5VYCLZRES3CsBPY4uvgTRyOUp6UZgWBQfk/edit#gid=1459904488)

**Comment by stephaniestahlberg** [comment]
Bonnie offered to help with advertising the survey on Slack, and we got 18 responses after she posted in the general channel. I am handing this issue off to @Maria Elizabeth now. Maria Elizabeth, when looking at the number of responses received, please note that several marked "No" in the eligibility question (whether they had joined a project in the last 6 months), so we don't actually have responses for those individuals. Our total for valid responses is 20 now.

**Comment by stephaniestahlberg** [comment]
@MariaElizabeth04 when you are back, can you advertise this survey on Slack again? Thanks.

**Comment by sdimran** [comment]
moving this back into the backlog

**Comment by hkimsummer** [comment]
- Assess what the results are by Aug 2, and decide whether to continue data collection. 
- Ask in #admin channel if we can join onboarding sessions to recruit participants

**Comment by kcoronel** [comment]
Closing this issue as Action Items have been completed.
