### ISSUE TITLE
Search Page Design (UX)

### ISSUE THREAD

**Issue by ihorng** [hackforla/CivicTechJobs#24]
### Dependency

- [x] #285 
- [x] #289

### Overview

We need to design a search page with filters so that a user (potential volunteer) can easily find a volunteer opportunity that fits their skills or aspirations.

### Action items

- [x] Ideate in hi-fi
- [x] Present to design team
- [x] Iterate
- [x] Present to all team
- [x] Iterate to design final
- [x] Handoff to Devs

### Resources/Instructions
[Requirements](https://docs.google.com/spreadsheets/d/1VcDLJnDA5CE7euzaZxOcqS3LLgyUFVLeqvdZx2sFGQk/edit#gid=477987515)

**Comment by sharadgaurav7** [comment]
@jenchuu , please refer to issue #52 . We should either modify this issue to be more detailed on the specifics, or use the issue #52

**Comment by jenchuu** [comment]
@sharadgaurav7 edited this further.

**Comment by jenchuu** [comment]
[V2 Search page designs](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A12)
@graceerya and I created 4 project card options... open to feedback at our next meeting.
<img width="1147" alt="V2 LIMITED and FULL search results page" src="https://user-images.githubusercontent.com/88695763/148711714-0364d560-cdef-4773-8d8b-80a0fd494d30.png">

**Comment by sharadgaurav7** [comment]
@jenchuu , we left the following comments on the figma file for the Search Page design:

Product Team’s comments 1/16 

- Change “Start Onboarding..” to “Attend Onboarding” 
- We would sugegst we have one page design for the  limited page and the Full View page. In the limited page, the  project details, and “join us on Slack” will be masked/redacted. Once someone logs back in with their credentials, the same  masked/redacted info will be visible.  This way we just design one page!

 

Project card design Must Haves:

- Role Name
- Role Overview
- Responsibilities & requirements
- Meeting Times
- and other tags from the filter options, such as Technology area
- REDACTED if Not logged in a. Project Name b. Project Overview c. “Join us on Slack”

We can have a quick chat on slack if you need any clarifications. Please let us know if there's anything else that is blocking you on the Search Page Design
Thanks

**Comment by jenchuu** [comment]
@sharadgaurav7 @sdimran 

@graceerya and I have made the changes per your comments above and designs are ready for feedback:
[V3 Search page designs (Figma)](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A12)

<img width="1651" alt="Limited and full view search results page" src="https://user-images.githubusercontent.com/88695763/150043455-3c1add32-75a5-4eef-9198-252d819aa4a0.png">

**Comment by eva32lee** [comment]
We iterated upon our design based on feedback we received in a previous team meeting as well as preliminary user testing conducted with @janzenmolina.

In order to clarify that
> a) Listed technologies/languages are not required, but will be practiced
> b) All roles (besides developers) do not necessarily utilize technologies and skills

we combined technologies and languages into a more general "skills" headline, and added a tooltip informing prospective volunteers that skills aren't required, but can be beneficial to know beforehand


<img width="890" alt="Screen Shot 2022-02-23 at 11 55 26 AM" src="https://user-images.githubusercontent.com/76968000/155398057-6a68afed-278c-4130-a484-8e033cff7927.png">

**Comment by eva32lee** [comment]
We made changes to the mobile version mirroring those of desktop, including:

- combining languages and technologies into a more general "skills" section
- adding a tooltip to indicate that skills are not required but preferred

<img width="947" alt="Screen Shot 2022-03-07 at 12 57 10 PM" src="https://user-images.githubusercontent.com/76968000/157116881-3c470700-2f51-42aa-bbf8-0b601a514038.png">

**Comment by jenchuu** [comment]
@eva32lee  Please add updated final designs with the changed copy banner for both desktop and mobile designs.

**Comment by fenglugithub** [comment]
@jenchuu  and I working on search page designs. Here's Filter on top version:

- Different variations for filters on the top
- Unfolded look when Roles filter opened
- Body layouts for the page

<img width="1545" alt="Screen Shot 2022-07-31 at 7 15 58 PM" src="https://user-images.githubusercontent.com/43657452/182059475-05ce59b8-134b-44e3-a59b-c47af931d01d.png">

**Comment by fenglugithub** [comment]
Based on team feedback, will working on the followings:

- Simplify the information on search cards
- Make top filter one line on the top

<img width="883" alt="Screen Shot 2022-07-31 at 7 23 14 PM" src="https://user-images.githubusercontent.com/43657452/182060247-c29a22eb-d293-47bb-a317-6887763392b4.png">

Open to feedback at our next meeting.

**Comment by sdimran** [comment]
@fenglugithub  i like the design here with the filters up top and quick view cards on the side. 

Questions:
1. is the right side view locked to the page when a user scrolls on the left side to view other roles?
2. is there any value in having role descriptions in every smaller card if we will be showing it in the larger card? most roles would have the same description (front end dev on one project will be the same description as a front end dev on another project) although the exact responsibilities would differ. for a potential volunteer the experience level and meeting times should be the most relevant information in a quick glance as if they don't line up, the role description will not have much impact. they would find more value in having instead the "skills you will learn" section in the quick view instead. can we see this left side card view without the role overview to better condense the information and one view with the "skills you will develop" instead?
3. for the filters on the top, if i click the availability filter will there be a modal that pops up as an overlay on the screen or is it a drop down into the full calendar view? if it is the former should there be a "+" sign rather than a downwards arrow?

Thanks!

**Comment by jenchuu** [comment]
@fenglugithub and I worked on search page designs.

Below are my ideations for filters on side version:
Option 1 shows selected filters as chips on top left side.
Option 2 shows selected filters as number badges in each filter section.
<img width="1417" alt="Filters on side options" src="https://user-images.githubusercontent.com/88695763/182492046-b4ab834d-cb78-4c50-afde-16c96c88f49f.png">

Below are my ideations for filter "badges":
Option 1 shows white number in blue circle badge.
Option 2 shows blue number in parentheses.
<img width="593" alt="Filter badge options" src="https://user-images.githubusercontent.com/88695763/182492187-d8d631d0-7f91-4204-bcc3-4363ea4e8c80.png">

Below are my ideations for Roles filter when opened:
Option 1 shows list of checkboxes for all roles.
Option 2 shows modal window with role chips (same UI from Qualifier page).
<img width="1499" alt="Role filter open options" src="https://user-images.githubusercontent.com/88695763/182492359-c5840627-3b1c-4449-a3da-db09924c402b.png">

**Comment by jenchuu** [comment]
The designers met on Sunday and had a great discussion.
We decided to combine Lu and my designs somewhat: we will have filters on TOP with MODAL (pop up) window when user clicks on a filter.

We are working on combining the design.

**Next step for us:**
split up designing what the other open filters will look like.

@sdimran Can you confirm the filters for the LIMITED search results page? is it:

- Roles
- Availability
- Experience Level
- Technologies
- Program Area (***Is this one necessary? What does this even entail?)

**Comment by jenchuu** [comment]
Per team leads monthly discussion, cut info shown in open role card... Definitely show:
- Skills you'll develop
- Mandatory meeting times

**Comment by fenglugithub** [comment]
> @fenglugithub i like the design here with the filters up top and quick view cards on the side.
> 
> Questions:
> 
> 1. is the right side view locked to the page when a user scrolls on the left side to view other roles?
> 2. is there any value in having role descriptions in every smaller card if we will be showing it in the larger card? most roles would have the same description (front end dev on one project will be the same description as a front end dev on another project) although the exact responsibilities would differ. for a potential volunteer the experience level and meeting times should be the most relevant information in a quick glance as if they don't line up, the role description will not have much impact. they would find more value in having instead the "skills you will learn" section in the quick view instead. can we see this left side card view without the role overview to better condense the information and one view with the "skills you will develop" instead?
> 3. for the filters on the top, if i click the availability filter will there be a modal that pops up as an overlay on the screen or is it a drop down into the full calendar view? if it is the former should there be a "+" sign rather than a downwards arrow?
> 
> Thanks!

Thanks @sdimran  
Here are the answers:
1. Yes. The right side view locked to the page when a user scrolls on the left side. If the user click the other role card on the left side. then the right side page changed accordingly.
2. That’s a good point! @jenchuu and I are working on simplified version for the smaller card. I agree the description show on both cards unnecessary and not efficiency for a quick glance. Will condense the information here and have “skills you will develop” instead.
3. Thanks for bring that up. We are working on the availability and the other filters on Top with pop up window.

Thanks!

**Comment by jenchuu** [comment]
Updated Roles filter modal window:
- Changed view of multi-select chips to differentiate it from the single-select chips: added checkmark icon in front

<img width="652" alt="Roles filter open V2" src="https://user-images.githubusercontent.com/88695763/183779400-c7d4f71d-2fd8-44a9-8bfa-8beb56ff3646.png">

**Comment by jenchuu** [comment]
Ideations for Experience Level filter when open:
Based on our UXD meeting yesterday, we are leaning towards one of the last 2 options.

<img width="1669" alt="Experience Level filter open options" src="https://user-images.githubusercontent.com/88695763/183779569-6122e8af-46c1-465c-b609-fc3b824fcb67.png">

**Comment by jenchuu** [comment]
Ideations for the Small role card options (small cards on left side):
We're trying to condense the info down even further than this. Will explore more ideas.

<img width="1655" alt="Small role cards options" src="https://user-images.githubusercontent.com/88695763/183779651-cbba5cdb-447e-42eb-9e8a-d5d3f89caecd.png">

**Comment by fenglugithub** [comment]
Ideations for the full card on the right side.
We are trying to add icons and organize the hierarchy of content. 
Will place with the content hierarchy more and have the text/color styles and icon library consistent. 

[Full card options](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=4564%3A34429)
<img width="555" alt="Screen Shot 2022-08-09 at 4 58 24 PM" src="https://user-images.githubusercontent.com/43657452/183781820-966103f4-78b7-4bc2-9432-3aeb8603bd78.png">

**Comment by fenglugithub** [comment]
Ideations for Availability filter when open.
Referred to Qualifier page, we are working on the calendar in popup window.
Based on the meeting discussion, will condense the vertical space of the calendar and explore how that looks. 

[Availability filter when open](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A12)
<img width="1593" alt="Screen Shot 2022-08-09 at 6 03 23 PM" src="https://user-images.githubusercontent.com/43657452/183787830-b1c61730-7e2d-439f-8de6-2abf1f6dac46.png">

**Comment by fenglugithub** [comment]
Ideations for full card designs.
Based on our UX meeting, we may explore more for version B (the one in the middle).

[Full card options](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A12)
<img width="1302" alt="Screen Shot 2022-08-15 at 7 30 16 PM" src="https://user-images.githubusercontent.com/43657452/184785624-3440485f-bbe0-4cfa-980d-2ee567273baf.png">

**Comment by fenglugithub** [comment]
Updated Availability filter based on our pervious discussion. 
Condense the vertical space of the calendar and make it less scroll.

[Availability filter when open](https://www.figma.com/file/G5bOqhud6azbxy
<img width="616" alt="Screen Shot 2022-08-15 at 7 31 37 PM" src="https://user-images.githubusercontent.com/43657452/184786054-03d746fc-a161-4506-a5ea-bcc647c2f245.png">
R9El9Ygp/Civic-Tech-Jobs?node-id=1%3A12)

**Comment by sdimran** [comment]
> Updated Availability filter based on our pervious discussion. Condense the vertical space of the calendar and make it less scroll.
> 
> [Availability filter when open](https://www.figma.com/file/G5bOqhud6azbxy) <img alt="Screen Shot 2022-08-15 at 7 31 37 PM" width="616" src="https://user-images.githubusercontent.com/43657452/184786054-03d746fc-a161-4506-a5ea-bcc647c2f245.png">

i like this view @fenglugithub great work! @jenchuu @Aveline-art were there any result from your discussions from this past week around the sticky day row at the top of the calendar?

**Comment by sdimran** [comment]
> 

@fenglugithub @jenchuu  hoping to get your thoughts on this perspective but we should be displaying the most important information at the beginning of the full card view which i think in this case would be the responsibilities (since we already show the mandatory meeting times in the preview on the left we can move this down in the list). can we order the information displayed in the following order of priority :

1. overview 
2. responsibilities
3. skills you'll develop
4.  mandatory meeting times
5. experience level

if you have suggestions otherwise please let me know!

**Comment by sdimran** [comment]
> Ideations for full card designs. Based on our UX meeting, we may explore more for version B (the one in the middle).
> 
> [Full card options](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A12) <img alt="Screen Shot 2022-08-15 at 7 30 16 PM" width="1302" src="https://user-images.githubusercontent.com/43657452/184785624-3440485f-bbe0-4cfa-980d-2ee567273baf.png">



@fenglugithub @jenchuu  hoping to get your thoughts on this perspective but we should be displaying the most important information at the beginning of the full card view which i think in this case would be the responsibilities (since we already show the mandatory meeting times in the preview on the left we can move this down in the list). can we order the information displayed in the following order of priority :

1. overview 
2. responsibilities
3. skills you'll develop
4.  mandatory meeting times
5. experience level

if you have suggestions otherwise please let me know!

**Comment by fenglugithub** [comment]
@jenchuu and I worked on the search page designs. We made iterations for both cards (smaller cards on the left side and full cards on the right ) and adjusted spacing for the layouts.

[Search Page V10](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=4993%3A40250)

Below is our design iteration A
- We edited full card designs and played with icons, header with important info.
- We edited smaller cards with less info, filter chips with selected/unselected state 
<img width="764" alt="Screen Shot 2022-08-29 at 6 29 33 PM" src="https://user-images.githubusercontent.com/43657452/187327749-3c6a08e6-f3bc-4521-9779-dba6b6c46f04.png">



Below is our design iteration B
- We edited full card designs, played with less info in the header and moved button to the bottom.
- We edited smaller cards with more info.
<img width="703" alt="Screen Shot 2022-08-29 at 6 30 14 PM" src="https://user-images.githubusercontent.com/43657452/187327837-7f4cbb43-db5d-48d1-b177-520f3ee62758.png">

**Comment by fenglugithub** [comment]
Based on UX meeting feedback, @jenchuu and I worked on an Ideation for search page to show the top portion of large card is sticky when user scrolling. Below is our design iteration
[Search Page V10](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=4993%3A40250)

- Full view for the large card

<img width="792" alt="Screen Shot 2022-09-18 at 4 57 24 PM" src="https://user-images.githubusercontent.com/43657452/190933605-b3d1b6cf-f840-471f-b0d9-7ab2a88921e4.png">


- 1024px height view, when user scrolling:

<img width="800" alt="Screen Shot 2022-09-18 at 4 58 12 PM" src="https://user-images.githubusercontent.com/43657452/190933634-dfc2f3e9-9813-4fe4-b889-b03d550fb9be.png">

**Comment by fenglugithub** [comment]
@jenchuu and I worked on Search Page filters. We made 2 iterations for the filter menu and the detailed subpages.

[Search Page Filters](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=4993%3A40250)

**Below is our design iteration A**

- We edited All Filters to More Filters in the menu. 

<img width="708" alt="Screen Shot 2022-10-16 at 6 15 15 PM" src="https://user-images.githubusercontent.com/43657452/196069489-a780f2bf-68cf-42e3-8916-ff32811303ca.png">

- When user click more filters, it will take to Program Areas and Languages/Technologies popup window for details.

<img width="643" alt="Screen Shot 2022-10-16 at 6 23 14 PM" src="https://user-images.githubusercontent.com/43657452/196070026-dff3a03e-2ccf-43a1-acbe-05ca59569e9d.png">


**Below is our design iteration B**
- We edited the filter menu and keep all the filters showing separately. Users could scroll right and left to explore.

<img width="752" alt="Screen Shot 2022-10-16 at 6 24 28 PM" src="https://user-images.githubusercontent.com/43657452/196070110-ee055f7c-34cf-4bbc-be02-f89c981d61ff.png">
<img width="748" alt="Screen Shot 2022-10-16 at 6 24 39 PM" src="https://user-images.githubusercontent.com/43657452/196070133-293e9bcf-cf70-4b6e-97b4-31b67e06a055.png">

- We made two variations for the detailed subpages for the filter.

   1. Chips to show the options

<img width="1146" alt="Screen Shot 2022-10-16 at 6 28 27 PM" src="https://user-images.githubusercontent.com/43657452/196070439-3548a1d1-4a58-48ba-9a8a-f434cee2de64.png">

   2. Check-box to show the options

<img width="1142" alt="Screen Shot 2022-10-16 at 6 28 44 PM" src="https://user-images.githubusercontent.com/43657452/196070463-a9d9ab1b-8e64-4037-983b-6f5c7e4ba102.png">


Based on our UX meeting feedbacks, we will work on the following:

- Organize the chips in detailed page, try alphabetical order，or any better grouping/categories for the chips.
- Add Apply/Confirm button at the bottom of each filter.
- Add shadow or blur to the Filter menu to make the scroll transition looks smoothers.

**Comment by jenchuu** [comment]
Handed off these to Devs:
![Screen Shot 2023-05-16 at 7 06 06 PM](https://github.com/hackforla/CivicTechJobs/assets/88695763/2fcd2b78-428d-4e8b-b011-234ae8738657)
![Screen Shot 2023-05-16 at 7 06 52 PM](https://github.com/hackforla/CivicTechJobs/assets/88695763/b0263ff9-0a10-4af7-92d4-c9d56752e3d2)
![Screen Shot 2023-05-16 at 7 07 03 PM](https://github.com/hackforla/CivicTechJobs/assets/88695763/51187812-6b6b-4ed7-a3ee-c895b447381b)

**Comment by jenchuu** [comment]
**May need to reopen and change due to changing requirements for Skills which may affect Languages/technologies.
