### ISSUE TITLE
Accessibility: Update Dialog component 

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#241]
### Overview

As a developer, we need to make sure that our components are accessible as much as humanly possible. For this issue we will update our Dialog component for accessibility.

### Action Items

- [ ] Read the accessibility guidelines for dialogs
- [ ] Edit the dialog until it is accessible based on the guidelines
  - [ ] One guideline that needs to be updated is to have the modal exit when certain keys are pressed
  - [ ] Another is to keep the tab within the dialog

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)
[WAI-ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/)

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of #552
