### ISSUE TITLE
Create a program to run super-linter locally

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#243]
### Overview

As a developer, we need to make sure that we get fast feedback when developing. For this issue we will add super-linter locally so that we do not need to make pushes to get feedback on our code.

### Action Items

- [ ] See the docs below.
- [ ] Implement this as part of our codebase.
- [ ] Add or link steps to run these tests in our documentation.

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)
[Run Super-Linter locally to test your branch of code](https://github.com/github/super-linter/blob/main/docs/run-linter-locally.md)

Note: The ideal set-up would not involve including the entire built docker image into our codebase (which is 1.8GB), but would contain instructions (either steps, or some script) for downloading that image. I.E, this feature should be opt-in for developers.

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of #552
