### ISSUE TITLE
How to join steps on Landing page

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#244]
### Overview

As a designer we need to ensure new volunteers understand the correct order of steps when joining a project from Civic Tech Jobs. We will add an overview of "how to join" steps on the Landing page to clearly communicate how to join.

### Action Items

- [x] Add overview of how to join steps
- [x] Check with team / Bonnie about taking out step 2: Creating an account
- [x] Handoff to devs

### Resources/Instructions

[Landing page V11](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=3348%3A33608)

**Comment by jenchuu** [comment]
Added "how to join" steps to landing page. We took out step of creating an account... pending approval of new, leaner MVP flow by Bonnie.

<img width="393" alt="Landing page V11" src="https://user-images.githubusercontent.com/88695763/167756058-de4355a5-ae39-437e-8853-eaec8caba5b4.png">

**Comment by jenchuu** [comment]
@sdimran @sharadgaurav7 @ExperimentsInHonesty 
Are we ok taking out the "create an account" step for MVP?

**Comment by sdimran** [comment]
@sharadgaurav7 please advise and confirm, I may have missed the conversation that day when taking the account creation out of MVP was discussed.

Thanks,

**Comment by kcoronel** [comment]
All tasks for this issue were completed.
