### ISSUE TITLE
Front and Backend environmental setup

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#25]
### Dependency

- [x] #26

### Overview
As a developer, we need to be prepared for when projects come in. For this issue, we will initialize the project to create the scaffolding needed to begin front and back end work.

### Action Items

- [x] Initiate the app with docker, which is configured to django.
- [x] Set up the frontend/backend directories
- [x] Add a JSX preprocessor (rather than use create-react-app or the cnd) as this is determined to be the preferred front-backend interface by @Aveline-art and @arghmatey 
- [x] Create a test front page
  - [x] This page should have at least one line to text, just so we know that visually, everything is set up correctly.
- [ ] Release dependency on:
  - [ ] #48  
  - [ ] #49 
  - [ ] #50
- [x] When releasing dependencies, be sure to look over those issues and update any action items or resources with additional information that arisen from working with this issue

### Resources/Instructions
[Quickstart: Compose and Django](https://docs.docker.com/samples/django/)
[Add JSX to a Project ](https://reactjs.org/docs/add-react-to-a-website.html#add-jsx-to-a-project)
[schema](https://github.com/hackforla/CivicTechJobs/issues/13#issuecomment-886323790)
[related comment #1](https://github.com/hackforla/CivicTechJobs/issues/26#issuecomment-911895918)
[related comment #2](https://github.com/hackforla/CivicTechJobs/issues/26#issuecomment-913929912)

**Comment by Aveline-art** [comment]
1. How long would it take to get this out and usable by other teams?
2. Will you be storing every piece of information we need, including job postings and other assets that are ONLY used by the CTJ project?
3. How will images we stored and retrieved?

**Comment by arghmatey** [comment]
Initial environmental setup has been pushed to repo. Testing was completed prior and post upload.

Wiki needs to be updated with instructions for developers on setting up the project for the first time. Issues created for updating the wiki: #19, #54. Issue for developer specific documentation: #48.

**Comment by Aveline-art** [comment]
Closed because the setup is completed
