### ISSUE TITLE
Component: Create Checkbox component

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#250]
### Overview

As a developer we need to develop components that help us reuse code. For this issue, we will make the checkbox component on the login page.

### Action Items

- [ ] Find checkbox in figma
- [ ] Create it
- [ ] Make sure it is accessible
- [ ] Make sure it is reusable

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)
[Figma](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A2)

**Comment by sdimran** [comment]
@jenchuu  please take a look at Ava's comments on figma and advise
