### ISSUE TITLE
Epic: CMS Wireframes (Role Posting + Dashboard)

### ISSUE THREAD

**Issue by graceerya** [hackforla/CivicTechJobs#255]
### Overview

We need to design the different aspects of the CMS (role posting flow, dashboard, etc.) to efficiently ideate and revise towards high-fidelity screens.

### Action Items

- [x] Wireframe dashboard
- [ ] Wireframe role posting flow
- [ ] Wireframe self-test (TBD if this should go here or on Search results page)

### Resources/Instructions

- [ ] #326 
- [ ] #327 
- [ ] #357 
- [ ] #358
- [ ] #360 

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)
[Figma](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=114%3A51437)

**Comment by sdimran** [comment]
@graceerya will you be working on this by yourself or will other designers be helping out as well since this is a 5 point story. if it helps you, we can break up the action items into individual stories to take on at a time. otherwise we can leave this as is. let me know and I can milestone it accordingly

**Comment by sdimran** [comment]
@graceerya just following up on the above comment

**Comment by graceerya** [comment]
@sdimran I'm working on this with the other designers!

**Comment by graceerya** [comment]
Currently working on V1 of dashboard and role posting flow wireframes. We have used the insights gathered by researchers to ideate for the dashboard and role posting flow and mapped out the different elements of each page.

**Role Posting Flow Wireframes:**
<img width="1575" alt="CMS Role Posting Wireframes A" src="https://user-images.githubusercontent.com/64109227/170625493-596728ee-129d-4309-b2ce-d93047a16569.png">
<img width="1134" alt="CMS Role Posting Wireframes B" src="https://user-images.githubusercontent.com/64109227/170625484-d352d113-eae2-414a-8de2-ccb4bd3e8bea.png">
<img width="1605" alt="CMS Role Posting Wireframes C" src="https://user-images.githubusercontent.com/64109227/170625486-77843fea-6b3a-46e1-beff-9297df50b840.png">

**Dashboard Wireframes:**
<img width="609" alt="CMS Dashboard Wireframes A" src="https://user-images.githubusercontent.com/64109227/170625488-474c5504-72fc-44ca-9b91-4738fe6140f3.png">
<img width="1660" alt="CMS Dashboard Wireframes B" src="https://user-images.githubusercontent.com/64109227/170625491-2396728d-1853-439c-9da4-dc1732da8399.png">
<img width="364" alt="CMS Dashboard Wireframes C" src="https://user-images.githubusercontent.com/64109227/170625492-98b4a5b5-92a4-4743-9e77-1b063ec53f43.png">

**Comment by sdimran** [comment]
Thanks @graceerya, i've moved it into the prioritized backlog so you can assign yourself to the issue and continue.

**Comment by sabheasley** [comment]
Hello @jenchuu! Can you please provide an update here prior to our Tuesday meeting:
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by kcoronel** [comment]
Hi @jenchuu can you please provide updates answering the following questions prior to our meeting, ty! 
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by kcoronel** [comment]
Spoke with Jen about the progress of this epic issue, now that it has moved onto UXR for testing, this issue can be closed.
