### ISSUE TITLE
Content Management System (CMS)

### ISSUE THREAD

**Issue by graceerya** [hackforla/CivicTechJobs#257]
### Dependency

- [x] #255 

### Overview

We need to create a Content Management System (CMS) to allow project managers and team leads to post, manage, and analyze role openings.

### Action Items

- [x] Brainstorm CMS features
- [x] Create #255 
- [x] Revise and pick out wireframes
- [x] Create high-fidelity screens

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)
[Figma](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=114%3A51437)

**Comment by sdimran** [comment]
@graceerya we cant move past a certain step until #255  is complete so lets add that as a dependancy until the wireframe issue has been completed. will move this into the icebox

Thanks!

**Comment by kchotani** [comment]
Followed up with Lu for an update for if this issue is ready to move to the prioritized backlog.

**Comment by kcoronel** [comment]
this has been completed with designs on Figma. We will be updating the designs with an added section for project managers to input what skills they are looking for.
