### ISSUE TITLE
Adjust tab focus outline size

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#261]
### Overview

As a developer we need our product to be accessible to people who uses keyboard for navigation. For this issue we will fix the tab focus of our footer.

### Action Items

- [x] Locate Footer
- [x] The tab focus outline of the `<a>` element in the logo does not surround the image
- [x] Edit the code so that the tab focus outline is around the image

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by bzzz-coding** [comment]
I tried examining the site on Chrome, Safari, and Firefox, but wasn't able to reproduce the issue. 

- On Chrome, the tab focus outline of the logo appears to be surround the image:
  - Small screen:
    <img width="464" alt="Screenshot 2023-04-05 at 12 00 32 AM" src="https://user-images.githubusercontent.com/86077274/230009612-bff4ce66-056c-4eed-8c8d-3b9c049b05a7.png">
  - Medium screen:
    <img width="476" alt="Screenshot 2023-04-05 at 12 00 47 AM" src="https://user-images.githubusercontent.com/86077274/230009670-897b5dd3-862e-4ca2-9596-d0b501ea9b1f.png">
  - Large Screen:
    <img width="597" alt="Screenshot 2023-04-05 at 12 01 16 AM" src="https://user-images.githubusercontent.com/86077274/230009736-21d0e28d-5a2d-4f07-b395-68d5ccc17257.png">

- On Safari, the tab focus outline of the logo also appears to be surround the image:
  - Small screen:
    <img width="269" alt="Screenshot 2023-04-05 at 12 02 44 AM" src="https://user-images.githubusercontent.com/86077274/230009875-9db68b6d-f312-4deb-af83-67671cdf95fd.png">
  - Medium screen:
    <img width="296" alt="Screenshot 2023-04-05 at 12 02 56 AM" src="https://user-images.githubusercontent.com/86077274/230009925-d335c303-7e4f-461b-bb18-f4a7373c7b57.png">
  - Large screen:
    <img width="558" alt="Screenshot 2023-04-05 at 12 01 52 AM" src="https://user-images.githubusercontent.com/86077274/230009994-4eee66a4-eb7d-49ff-92b3-e935fcae5131.png">

- On Firefox, the tab focus doesn't seem to work on any element on the web page. The tab focus only worked on some Firefox UI elements:
  <img width="443" alt="Screenshot 2023-04-05 at 12 24 10 AM" src="https://user-images.githubusercontent.com/86077274/230010763-bdbd2095-4e79-46b5-88d7-b506a41a190f.png">


@Aveline-art I would appreciate your input on this. Thank you for your help in advance!

**Comment by Aveline-art** [comment]
Ahh, thank you for catching this! It looks to be [a long time macOS firefox default setting](https://stackoverflow.com/questions/11704828/how-to-allow-keyboard-focus-of-links-in-firefox). I didn't notice this when making the ticket as I was using Win at the time.

Looks like setting `accessibility.tabfocus` to 7 on `about:config` worked:

<img width="800" alt="Screenshot 2023-04-05 at 3 25 27 PM" src="https://user-images.githubusercontent.com/62368440/230225409-1a122c60-6ebd-4a62-b442-9a7a8e61a06d.png">

This is what I am seeing now:

<img width="800" alt="Screenshot 2023-04-05 at 3 27 54 PM" src="https://user-images.githubusercontent.com/62368440/230225535-11637c2b-6386-40c2-ab7a-390df501d333.png">

**Comment by bzzz-coding** [comment]
Ah I see, so it was Firefox! Okay I made sure I have the same setting and can now see the problem. I'll work on the issue! Thanks, Ava!
