### ISSUE TITLE
Product Feature Requirements and MVP V1.0

### ISSUE THREAD

**Issue by sharadgaurav7** [hackforla/CivicTechJobs#27]
### Overview
Upload the discussion about the requirements and the MVP so that the team can watch the video and learn about the feature and design requirements for the product (civictechjobs.org)

### Action Items
Bonnie to upload the recording of the discussion with Sharad and Danish. Meeting date Sunday, August 29

### Resources/Instructions
Zoom meeting recording

**Comment by ExperimentsInHonesty** [comment]
@sharadgaurav7 I have the files ready, I need the link to the folder you want this to be put in.

**Comment by sharadgaurav7** [comment]
@ExperimentsInHonesty , can you please upload here: https://drive.google.com/drive/folders/1hXxvpC8W5Uuzjqo4CxnjDpAMI7sbVnq8

Thanks

**Comment by ExperimentsInHonesty** [comment]
I have uploaded to this folder [2021-08-29 - with Bonnie](https://drive.google.com/drive/folders/1iceakNrTNmElIR4geBQ3Tyq1RHLRoIy2?usp=sharing)
