### ISSUE TITLE
Credit Page Wireframes

### ISSUE THREAD

**Issue by sdimran** [hackforla/CivicTechJobs#273]
### Dependency
- [x] #283 
- [x] #284

### Overview

As an organization, I need to make sure that we note down where we are getting our images and links from in order to give credit to the owners and sources. 

this issue will focus on the wireframes for the credits page, which is a key page to be launched as part of MVP1

### Action Items

- [x] review www.HackforLa.org/credits 
- [x] create wireframes using the above as a baseline (do not need images, simply a quick view of the format and style we can go with)
- [x] review with PM's
- [x] create Visual designs (will be a different ticket)

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)
[HfLA Credits page](https://www.hackforla.org/credits/)

**Comment by jenchuu** [comment]
@sdimran can we delete this issue? Since you have two open that are the same I think? #123

**Comment by kcoronel** [comment]
Closing this issue as [Credits Page in Figma](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?type=design&node-id=1-27&mode=design) has the wireframes for the Credit Page
