### ISSUE TITLE
Epic: Calendar Page

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#274]
### Dependency

- [x] #275
- [x] #276
- [x] #277
- [x] #278

### Overview
This an an epic for the calendar page. Once the above is done, continue with the action items.

### Action Items

- [ ] Create the Calendar page from figma.

### Resources/Instructions
[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by Aveline-art** [comment]
@jenchuu Since I know you look at these issues to see how we design/create components, here's a breakdown of them:

- Progress bar: from figma, self-explanatory
- Dropdown menu: from figma, self-explanatory
- Calendar: from figma, self-explanatory
- Icon Button: this is probably the one that seems the most "out there". Basically, this represents the "back arrow" button that is on the bottom of the calendar page. Since it works very similarly to the close button on the CopCard, I've opted to combine them into a single "Icon Button" component.

Let me know if you have any queries on how these things are named or broken down.

**Comment by Aveline-art** [comment]
@sdimran After the last couple of months and review, not much for this issue has changed. Should I move this to `in progress` directly?

**Comment by sdimran** [comment]
@Aveline-art yes that sounds good thanks
