### ISSUE TITLE
Credits Page design (UX) Gabe's Version

### ISSUE THREAD

**Issue by geibu** [hackforla/CivicTechJobs#283]
### Overview

As a designer, we need to site and provide credit to the assets we are using so we will not be plagiarizing content. For this issue, we will design a credits page.

### Action Items

- [ ] Wireframe
- [ ] Get feedback
- [ ] Present to team
- [ ] Iterate based on team feedback
- [ ] Present to team

### Resources/Instructions

[Figma Credits Page Wireframe](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=4421%3A20038)
[Requirements](https://docs.google.com/spreadsheets/d/1VcDLJnDA5CE7euzaZxOcqS3LLgyUFVLeqvdZx2sFGQk/edit#gid=477987515)

**Comment by geibu** [comment]
Questions regarding the requirements for the credit page: 
- Are the requirements within the user stories set to stone?

<img width="1106" alt="Screen Shot 2022-08-02 at 5 11 58 PM" src="https://user-images.githubusercontent.com/107892670/182497565-4add8657-bc74-4e26-91d1-37e7af663afb.png">

**Comment by geibu** [comment]
Version 2: show all page
<img width="710" alt="Screen Shot 2022-08-09 at 1 41 14 PM" src="https://user-images.githubusercontent.com/107892670/183756839-bad348c6-5118-40e1-b02a-f39225887318.png">

Version 2.1: using a tab design
<img width="697" alt="Screen Shot 2022-08-09 at 1 41 22 PM" src="https://user-images.githubusercontent.com/107892670/183757203-94ee0788-63b8-45f5-a6cd-7eb57de95ea7.png">

**Comment by geibu** [comment]
Version 3:
- Added checkbox to filter through
- Added external text link in cards

Vertical formatting
<img width="762" alt="Screen Shot 2022-08-09 at 9 25 04 PM" src="https://user-images.githubusercontent.com/107892670/183815672-26f941bf-8258-4476-af9f-a530fef77869.png">

Horizontal formatting
<img width="768" alt="Screen Shot 2022-08-09 at 9 25 28 PM" src="https://user-images.githubusercontent.com/107892670/183815686-6d1b1b93-59b0-4a5a-a326-e912889bbd95.png">


HackforLA section:
- Minimized HfLA Logo
- Changed CTA button color and external text link
<img width="761" alt="Screen Shot 2022-08-09 at 9 25 36 PM" src="https://user-images.githubusercontent.com/107892670/183815689-08a784ee-d50d-4227-80ba-5139b0efb5e5.png">

**Comment by sdimran** [comment]
@TCUX  @geibu lets review the issues together during our meetings before we mark them as closed!

**Comment by geibu** [comment]
Final Credit Page Design:
Worked with Tin to finalize design for credit page
<img width="1215" alt="Screen Shot 2022-09-05 at 8 03 23 PM" src="https://user-images.githubusercontent.com/107892670/188538468-b05c4e46-73aa-4325-a15f-a302bb4ec823.png">

**Comment by sdimran** [comment]
great work @geibu , closing this issue as we will continue in @TCUX 's issue. i have left my comments there as well.

**Comment by jenchuu** [comment]
test

**Comment by geibu** [comment]
Final design for the credits page:

Illustrations
<img width="564" alt="Screen Shot 2022-09-13 at 6 20 44 PM" src="https://user-images.githubusercontent.com/107892670/190037390-619d7d13-2df8-4494-949a-d6b9b36f7d50.png">

Iconograpghy
<img width="450" alt="Screen Shot 2022-09-13 at 6 20 56 PM" src="https://user-images.githubusercontent.com/107892670/190037398-15b686ee-1459-4e04-8f14-e79f7842407c.png">
