### ISSUE TITLE
Credits Page design (UX) Tin's Version

### ISSUE THREAD

**Issue by TCUX** [hackforla/CivicTechJobs#284]
### Overview

As a designer, we need to site and provide credit to the assets we are using so we will not be plagiarizing content. For this issue, we will design a credits page.

### Action Items

- [x] Wireframe
- [x] Present
- [x] Get Feedback
- [x] Iterate
- [x] Present

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)
[Requirement](https://docs.google.com/spreadsheets/d/1VcDLJnDA5CE7euzaZxOcqS3LLgyUFVLeqvdZx2sFGQk/edit#gid=477987515)
[Figma-Tin's Design](https://www.figma.com/proto/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?page-id=1%3A27&node-id=4365%3A20449&viewport=301%2C442%2C0.25&scaling=min-zoom)

**Comment by TCUX** [comment]
The layouts and descriptions are similar to current HackforLA page.  
What are the minimum description are required to have on credit page?
![CREDIT PAGE V1](https://user-images.githubusercontent.com/105838543/183356778-7ae62adf-4387-482d-909e-5989bd0362d6.PNG)

**Comment by TCUX** [comment]
Credit page V2.1 : Show all digital assets cards layout with cards in horizontal layout

![CREDIT PAGE V2 1](https://user-images.githubusercontent.com/105838543/183778342-810cb6de-1375-4232-998c-22f850ad9135.PNG)

Credit Page V2.2 : Show all digital assets cards layout with cards in Vertical layout

![CREDIT PAGE V2 2](https://user-images.githubusercontent.com/105838543/183778502-c0e2b5cb-562e-4d2b-99c7-d435aa9021bf.PNG)

Credit Page V3.1 : Show digital assets card by each pages where are being used with menu bar 

![CREDIT PAGE V3 1](https://user-images.githubusercontent.com/105838543/183778680-261bb19d-d6d4-40c5-b0ab-4da7c0785357.PNG)

**Comment by TCUX** [comment]
Worked with Gabe to finalize credit page design. 

![Credit Page_Final Version](https://user-images.githubusercontent.com/105838543/188538873-8ee82cf6-8db6-4d62-a82e-458758d54fe9.PNG)

**Comment by sdimran** [comment]
great work @TCUX @geibu. im good with this design and implementation. please put a red box around the final design in figma so we can hand it off to @Aveline-art  and the dev team,

one question, do these two pages encapsulate all illustrations and iconographies from civic tech jobs?

**Comment by kcoronel** [comment]
closing this issue as all tasks have been completed
