### ISSUE TITLE
Accessibility: Edit Dropdown Component for accessibility

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#286]
### Overview

As a developer we need to make sure our components are accessible. For this issue, we will examine the Dropdown component.

### Action Items

- [ ] Make sure our dropdown is accessible

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)
[A good place to start](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/listbox_role)

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of #552
