### ISSUE TITLE
Search result page - Jen's design

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#289]
### Overview

As a designer, we need to create a search page with filters so that users can easily find volunteer opportunities that fit their skills or goals.

### Action Items

- [x]  Ideate
- [x]  Present to design team
- [x]  Iterate based on feedback
- [x]  Present to whole team

### Resources/Instructions

[Requirements](https://docs.google.com/spreadsheets/d/1VcDLJnDA5CE7euzaZxOcqS3LLgyUFVLeqvdZx2sFGQk/edit#gid=477987515)
[Jen's design - Figma](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=4404%3A20373)

**Comment by kcoronel** [comment]
Closing this issue as all action items have been completed and a link to Jen's designs of the search results page is included above.
