### ISSUE TITLE
Qualifier Page - Role Prototype (Accordion)

### ISSUE THREAD

**Issue by TCUX** [hackforla/CivicTechJobs#293]
### Overview

As a designer, we need to figure out which way to select roles is better/easier for users. For this issue, we will create a clickable Figma prototype for accordion / type search option to test with users to decide.

### Action Items

- [x]  Create prototype in Figma
- [x]  Send prototype link to UXR team for review
- [ ]  Help UXRs with leading/transcribing usability sessions

### Resources/Instructions

[Role Qualifier page - Accordion options ](https://www.figma.com/proto/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?page-id=1%3A29&node-id=4676%3A34801&viewport=1490%2C271%2C0.5&scaling=min-zoom&starting-point-node-id=4676%3A34801&hotspot-hints=0)

**Comment by TCUX** [comment]
[Role Qualifier Page - Accordion / Type search prototype ](https://www.figma.com/proto/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?page-id=1%3A29&node-id=4676%3A34801&viewport=1490%2C271%2C0.5&scaling=min-zoom&starting-point-node-id=4676%3A34801&hotspot-hints=0)

- The prototype is aimed for Engineer user to select whether Full stack developer or Front end developer role through type search or accordion method.

**Comment by TCUX** [comment]
[Role Qualifier Page - Accordion / Type search prototype V2 ](https://www.figma.com/proto/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?page-id=1%3A29&node-id=4676%3A34801&viewport=755%2C472%2C0.25&scaling=min-zoom&starting-point-node-id=4676%3A34801)

**Comment by jenchuu** [comment]
@sdimran This has been completed by Tin and is ready to be closed.
