### ISSUE TITLE
Qualifier Page - Role Prototype (Multi-chip)

### ISSUE THREAD

**Issue by geibu** [hackforla/CivicTechJobs#295]
### Overview

As a designer, we need to figure out which way to select roles is better/easier for users. For this issue, we will create a clickable Figma prototype for the qualifier page with a multi-chip option to test with users.

### Action Items

- [ ] Create prototype in Figma
- [ ] Send prototype link to UXR team for review
- [ ] Help UXRs with leading/transcribing usability sessions

### Resources/Instructions

[Role Qualifier Page - (Multi-chip) Prototype](https://www.figma.com/proto/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=4775%3A37098&scaling=min-zoom&page-id=1%3A28&starting-point-node-id=4775%3A37098&show-proto-sidebar=1)

**Comment by geibu** [comment]
Prototyped the multi-chip options for the engineering CoP section
<img width="1550" alt="Screen Shot 2022-08-15 at 7 09 27 PM" src="https://user-images.githubusercontent.com/107892670/184783447-fd12c7a6-70a3-4651-88a5-7069cd99d408.png">

**Comment by jenchuu** [comment]
@sdimran This has been completed by Gabe and is ready to be closed.
