### ISSUE TITLE
Add jest tests for Calendar component

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#301]
### Overview

As as a developer, we need to test our code to ensure that it is maintainable. For this issue, we will add tests to our calendar component.

### Action Items

- [x] Locate `calendar.test.js`
- [x] Add jest tests for the component in the file

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by sabheasley** [comment]
Hello @t-will-gillis! Can you please provide an update here prior to our Tuesday meeting:

- [ ] Progress
- [ ] Blockers
- [ ] Availability
- [ ] ETA

**Comment by kcoronel** [comment]
Hi @t-will-gillis can you please provide updates by answering the following before our meeting - ty!
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by sabheasley** [comment]
Hi @t-will-gillis can you please provide updates by answering the following before our meeting - ty!

1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by t-will-gillis** [comment]
Hi @sabheasley apologies for not removing myself from this issue- I have let @kcoronel know that I am not able to continue with CTJ at this time.
