### ISSUE TITLE
Qualifier Page - Availability Prototype (Calendar)

### ISSUE THREAD

**Issue by fenglugithub** [hackforla/CivicTechJobs#306]
### Overview

As a designer, we need to figure out availability time range for users. For this issue, we will create a clickable Figma prototype for availability calendar option to test with users to decide.

### Action Items

- [x] Create prototype in Figma
- [x] Send prototype link to UXR team for review
- [ ] Help UXRs with leading/transcribing usability sessions

### Resources/Instructions

[Availability Qualifier Page - Calendar](https://www.figma.com/proto/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?page-id=1%3A30&node-id=4903%3A38437&viewport=420%2C606%2C0.28&scaling=scale-down&starting-point-node-id=4903%3A38437)

**Comment by fenglugithub** [comment]
Prototype availability time range (calendar) for user testing
[Availability Qualifier Page - Calendar](https://www.figma.com/proto/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?page-id=1%3A30&node-id=4903%3A38437&viewport=420%2C606%2C0.28&scaling=scale-down&starting-point-node-id=4903%3A38437)

<img width="1010" alt="Availability Qualifier Page - Calendar" src="https://user-images.githubusercontent.com/43657452/187104914-d6363d55-2eed-4ec5-a245-e4a0fb74ddf9.png">

**Comment by jenchuu** [comment]
@sdimran This has been completed by Lu and is ready to be closed.
