### ISSUE TITLE
Qualifier Page - Availability Prototype (Range input)

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#308]
### Overview

As a designer, we need to test and discover which way is better/easier for users to input their availability. For this issue, we will create a clickable Figma prototype for the qualifier page with time range inputs to handoff to the UXRs and test with users.

### Action Items

- [x]  Create prototype in Figma
- [x]  Get feedback during UXD meeting
- [x]  Make final edits to prototype
- [x]  Send prototype link to UXR team for review
- [ ]  Help UXRs with leading/transcribing usability sessions

### Resources/Instructions

[Availability Qualifier Page (Range) Prototype](https://www.figma.com/proto/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?page-id=1%3A31&node-id=4951%3A40103&viewport=740%2C957%2C0.4&scaling=min-zoom&starting-point-node-id=4951%3A40103)

**Comment by jenchuu** [comment]
Logging prototype used for testing:
<img width="503" alt="Availability qualifer page (Range) prototype" src="https://user-images.githubusercontent.com/88695763/189502165-3435c9f5-b146-473b-94bb-2a74d449530a.png">

**Comment by jenchuu** [comment]
@sdimran This is done and ready to be closed.

**Comment by kcoronel** [comment]
@jenchuu closing this issue now - thank you!
