### ISSUE TITLE
Analyze and Present Results from Usability Testing - Qualifier Page

### ISSUE THREAD

**Issue by hkimsummer** [hackforla/CivicTechJobs#311]
### Dependency

- [x] #291 

### Overview

As a research team, we need to analyze the findings from the usability testing and  prepare a presentation that includes insights and recommendations to deliver to the team.

### Action Items

- [x] Analyze participant responses 
- [x] Prepare a slide deck for presentation
- [x] Present insight and recommendations to the team

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)
[HfLA UX Research-Phase 2-Qualifier Page-Role Selection & Availability](https://docs.google.com/presentation/d/1xTcAyVMfW2MjhLkDiIQw1owPYxwgHj1_fMybVL1SDWs/edit?usp=drive_link)

**Comment by kcoronel** [comment]
Closing this issue as Action Items have been completed.
