### ISSUE TITLE
Accessibility Research

### ISSUE THREAD

**Issue by hkimsummer** [hackforla/CivicTechJobs#312]
### Overview

As a research team, we need to examine the accessibility aspect of our product for inclusive design. 

### Action Items

- [ ] Research best practices for accessibility research for website design
- [ ] Devise a plan for research and testing 

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of #552
