### ISSUE TITLE
Search Page Usability Testing

### ISSUE THREAD

**Issue by hkimsummer** [hackforla/CivicTechJobs#313]
### Dependency

- [x] #24  

### Overview

As a research team, we need to test the revised role selection component of the search page to identify any pain points and blockers before the release of the MVP.

### Action Items

- [ ] Discuss goals for usability testing with the team
- [ ] Write a research plan
- [ ] Review the prototype and discuss any questions with the design team
- [ ] Set up Calendly and Zoom link
- [ ] Recruit participants
- [ ] Conduct research

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by hkimsummer** [comment]
Need to check Dependency

**Comment by sdimran** [comment]
@BethBethBeth  can we attach the search page issue under the dependancy column and then I can put this in to the backlog

**Comment by BethBethBeth** [comment]
Hi @sdimran - still learning Github, sorry for the delay. I asked Summer about this and she said updated the issue and that it's ready for prioritized backlog.

**Comment by kchotani** [comment]
Followed up with Lu for an update for if this issue is ready to move to the prioritized backlog.

**Comment by kcoronel** [comment]
closing this issue because our Design team will be conducting a joint usability test between our Search Page and Skills Matrix. Our team would like to test a user actually going through one/a part of our journey.
