### ISSUE TITLE
Create CD/CI Pipeline for staging deployment

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#314]
### Overview

As a developer, we should make sure that our deployment pipeline is automated so that developers can spend more time on critical issues rather than repetitive work. For this issue, we will leverage GHAs in order to create a CD/CI pipeline into our staging aws environment.

### Action Items

- [x] Create a GitHub action that automatically deploys the code from our `main` branch into our aws instance
  - [x] Make sure that our secrets are [injected in via our GitHub Secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow)

### Resources/Instructions

Note: In the future we will probably move `main` to deploy into a production instance, and move staging deployment into a `staging` branch.

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by sdimran** [comment]
@Aveline-art  good to work on now

**Comment by Aveline-art** [comment]
@Enzyme3 This issue is ready for you to pick up whenever you are ready

**Comment by Aveline-art** [comment]
This was previously completed by #329 by @Enzyme3 . Will close this.
