### ISSUE TITLE
List All Roles from the Roles Qualifier Page

### ISSUE THREAD

**Issue by salimays** [hackforla/CivicTechJobs#315]
### Overview

For clarity purposes and after an ask from Dev, we need to list all the jobs by category in text form. 

### Action Items

- Make a list out of the Jobs Drop Down Menu for clarity purposes

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by salimays** [comment]
Roles:
- Engineering: Front End, Back End, Full Stack, Software
- Development: 
- UX/UI: Research, Design, 
- Operations: Product Management, Project Management

**Comment by kcoronel** [comment]
@salimays please review to see if we can close this issue

**Comment by kcoronel** [comment]
@salimays to review and close out if needed

**Comment by kcoronel** [comment]
reviewed with Salima, and due to conversations around having a skills matrix, we can close this issue.
