### ISSUE TITLE
## [10/4/22]  Meeting Agenda

### ISSUE THREAD

**Issue by salimays** [hackforla/CivicTechJobs#316]
## [10/4/22]  Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Jen](https://github.com/hackforla/CivicTechJobs/issues/assigned/jenchuu)
       - [ ] [Gabe](https://github.com/hackforla/CivicTechJobs/issues/assigned/geibu)
       - [ ] [Lu](https://github.com/hackforla/CivicTechJobs/issues/assigned/fenglugithub)
       - [ ] [Tin](https://github.com/hackforla/CivicTechJobs/issues/assigned/TCUX)
       - [ ] [Summer](https://github.com/hackforla/CivicTechJobs/issues/assigned/hkimsummer)
       - [ ] [Adrienne](https://github.com/hackforla/CivicTechJobs/issues/assigned/adriennedomasin)
       - [ ] [Ava](https://github.com/hackforla/CivicTechJobs/issues/assigned/Aveline-art)
       - [ ] [Kevin](https://github.com/hackforla/CivicTechJobs/issues/assigned/Enzyme3)
       - [ ] [Poorva](https://github.com/hackforla/CivicTechJobs/issues/assigned/poorvarathore05)
       - [ ] [Danish](https://github.com/hackforla/CivicTechJobs/issues/assigned/sdimran)
       - [ ] [Salima](https://github.com/hackforla/CivicTechJobs/issues/assigned/salimays)
       - [ ] [Danish](https://github.com/hackforla/CivicTechJobs/issues/assigned/sdimran)
- [ ] update visual roadmap
- [ ] update October roadmap in CTJ Planning Meeting
- [ ] review Roles Qualifier issue #193

### FYIs
-

### Notes from Meeting
Ask Bonnie:
Icons in Roles Qualifier Page for DevOps and Community Management 
Where to place roles cf Issue #193
Compiled list of roles Issue #315
Are there more roles coming?

Additional Meeting Notes in October page from CTJ Planning Meeting xcl doc

### Next week's Deliverables
Jen: 
Each page with filters 
Limited search page 

Ava:
Close outstanding requirements and backend work
Start issues related to Role Qualifier page
Address AWS permissions

Melinda
Ask Bonnie research behind role selection/title roles
Hire for usability testing

**Comment by salimays** [comment]
> ### Recurring items: Happens on the ________ meeting
> 
> 
> * [ ]  review any issues that are in the [new issue approval column]
> 
> * [ ]  Accountability and Support Check.
>   
>   * [ ]  Review assignments for each Team member
>     
>     * [ ]  [Jen](https://github.com/hackforla/CivicTechJobs/issues/assigned/jenchuu)
>     * [ ]  [Gabe](https://github.com/hackforla/CivicTechJobs/issues/assigned/geibu)
>     * [ ]  [Lu](https://github.com/hackforla/CivicTechJobs/issues/assigned/fenglugithub)
>     * [ ]  [Tin](https://github.com/hackforla/CivicTechJobs/issues/assigned/TCUX)
>     * [ ]  [Summer](https://github.com/hackforla/CivicTechJobs/issues/assigned/hkimsummer)
>     * [ ]  [Adrienne](https://github.com/hackforla/CivicTechJobs/issues/assigned/adriennedomasin)
>     * [ ]  [Ava](https://github.com/hackforla/CivicTechJobs/issues/assigned/Aveline-art)
>     * [ ]  [Kevin](https://github.com/hackforla/CivicTechJobs/issues/assigned/Enzyme3)
>     * [ ]  [Poorva](https://github.com/hackforla/CivicTechJobs/issues/assigned/poorvarathore05)
>     * [ ]  [Danish](https://github.com/hackforla/CivicTechJobs/issues/assigned/sdimran)
>     * [ ]  [Salima](https://github.com/hackforla/CivicTechJobs/issues/assigned/salimays)
>     * [ ]  [Danish](https://github.com/hackforla/CivicTechJobs/issues/assigned/sdimran)
> 
> * [ ]  update visual roadmap
> 
> * [ ]  update October roadmap in CTJ Planning Meeting
> 
> * [ ]  review Roles Qualifier issue [(Roles) Qualifier page revisions #193](https://github.com/hackforla/CivicTechJobs/issues/193)
> 
> 
> 
> ### FYIs
> 
> 
> 
> 
> 
> ### Notes from Meeting
> 
> Ask Bonnie:
> Shall we add skills to the roles page? 
> 
> 
> Additional Meeting Notes in October page from CTJ Planning Meeting xcl doc
> 
> 
> ### Next week's Deliverables
> 
> Jen: 
> Finishing Search Page by next Tuesday Oct 18
> Gabe and Tim work on the wireframes
> Creating last two filters for program and tech/language
> 
> Ava:
> Waiting to obtain AWS permissions, hopefully by Thursday Oct 20
> Qualifier - Progress on the Chips Page
> Back End Schema in progress
> Search Page - waiting for figma prototype
> 
> Melinda
> Research usability testing is the priority, by Tuesday Oct 25
> Recruited new UXR member, full team now
> Team is building context and going through old research
> Transcription of the Program Manager meetings Aug/Sept 2021 - project kick-off and requirements

**Comment by kcoronel** [comment]
linked this issue to #16
