### ISSUE TITLE
CMS Dashboard Wireframes - Gabe

### ISSUE THREAD

**Issue by geibu** [hackforla/CivicTechJobs#326]
### Overview

As a designer, we need to create a Content Management System (CMS) to allow project managers and team leads to post, manage, and analyze role openings. For this issue, we will create wireframes to efficiently ideate and revise toward high-fidelity screens.

### Action Items

- [x]  Wireframe dashboard
- [x]  Wireframe other additional pages

### Resources/Instructions

[Figma](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=5561%3A47941)

**Comment by geibu** [comment]
<img width="952" alt="Screen Shot 2022-10-17 at 11 44 50 AM" src="https://user-images.githubusercontent.com/107892670/196259677-95b520d7-16ac-4608-9fb9-8e89f615454e.png">

**Comment by geibu** [comment]
<img width="613" alt="Screen Shot 2022-10-17 at 11 17 15 PM" src="https://user-images.githubusercontent.com/107892670/196350770-53a8a5b2-4b0f-4169-afdf-33b378244fb0.png">

<img width="602" alt="Screen Shot 2022-10-17 at 11 17 18 PM" src="https://user-images.githubusercontent.com/107892670/196350781-bd91fa38-0b97-48cf-92ef-fa5f26ec2569.png">

<img width="607" alt="Screen Shot 2022-10-17 at 11 17 29 PM" src="https://user-images.githubusercontent.com/107892670/196350796-b292235a-2220-4658-a618-d73bf9b49e95.png">

<img width="603" alt="Screen Shot 2022-10-17 at 11 17 33 PM" src="https://user-images.githubusercontent.com/107892670/196350812-a7f5530f-41ad-4f0b-8195-71f0efe9cf44.png">

**Comment by geibu** [comment]
Wireframes for role posting

Role information
<img width="430" alt="Screenshot 2023-02-07 at 16 44 03" src="https://user-images.githubusercontent.com/107892670/217399886-ac3525eb-a9c1-44f3-8846-480607cc91da.png">

Meeting information
<img width="429" alt="Screenshot 2023-02-07 at 16 44 13" src="https://user-images.githubusercontent.com/107892670/217399901-d4e37679-4444-4ebf-8a30-efe393a6d036.png">

Contact information
<img width="424" alt="Screenshot 2023-02-07 at 16 44 23" src="https://user-images.githubusercontent.com/107892670/217399939-6bb81bb1-b113-4281-81d6-ea0292b69ea9.png">

Role posting review
<img width="424" alt="Screenshot 2023-02-07 at 16 44 36" src="https://user-images.githubusercontent.com/107892670/217399956-2d0f5c6b-52c9-46f9-ab51-55ac3536bf51.png">

**Comment by geibu** [comment]
More CMS ideations

<img width="572" alt="Screenshot 2023-05-08 at 20 24 46" src="https://user-images.githubusercontent.com/107892670/236986318-2f35fae6-18bc-46ef-a61c-3621cadc167b.png">

<img width="572" alt="Screenshot 2023-05-08 at 20 24 52" src="https://user-images.githubusercontent.com/107892670/236986325-53f6f036-fedd-48ec-ad0d-3b65cc4120bf.png">

Notes:
- Simplify more and reuse components already in place

**Comment by geibu** [comment]
<img width="468" alt="Screenshot 2023-05-23 at 14 03 22" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/1fe29111-9119-4a24-9132-e0ecd4e407bb">

<img width="475" alt="Screenshot 2023-05-23 at 14 03 32" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/440efa90-a5ba-4611-bc9a-6d88e947fbfc">

<img width="473" alt="Screenshot 2023-05-23 at 14 03 38" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/35e52f72-fe93-4208-b49c-3d7273acc5dc">

<img width="465" alt="Screenshot 2023-05-23 at 14 03 45" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/18fd25c2-3b3e-4dd4-813c-cbf3761e52b3">

<img width="480" alt="Screenshot 2023-05-23 at 14 03 50" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/1897fc61-6336-4c55-97d9-c4f44240c69d">

<img width="481" alt="Screenshot 2023-05-23 at 14 03 58" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/691c06eb-a1ce-4dfb-833d-fd183fd0f0de">

**Comment by geibu** [comment]
<img width="410" alt="Screenshot 2023-05-30 at 16 01 19" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/ac2ff30d-cafd-4287-ad15-b78b35a6ded6">
<img width="408" alt="Screenshot 2023-05-30 at 16 01 23" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/ff3cb0a1-67b5-4f3a-91f1-fdb95eb677a5">
<img width="410" alt="Screenshot 2023-05-30 at 16 01 31" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/0325b731-21d4-448b-8123-c84865ebc68d">
<img width="408" alt="Screenshot 2023-05-30 at 16 01 42" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/4d710dc9-0a58-44dc-82c0-1832ab73e935">
<img width="408" alt="Screenshot 2023-05-30 at 16 01 49" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/6511a1df-8c7c-449c-b69c-8141e0eabe53">
<img width="413" alt="Screenshot 2023-05-30 at 16 01 56" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/41bc25f3-d988-4ab1-b3d8-9de543003c7d">
<img width="411" alt="Screenshot 2023-05-30 at 16 02 03" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/56013403-ca7d-4d7d-8c1c-ca14fb05f6a4">
<img width="405" alt="Screenshot 2023-05-30 at 16 02 10" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/19f38e4d-0403-4081-8ae2-8ef4bc7122d9">
<img width="411" alt="Screenshot 2023-05-30 at 16 02 17" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/b4da761b-7538-48b9-aa70-50346e292ad4">
<img width="413" alt="Screenshot 2023-05-30 at 16 02 27" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/39fd3e00-cc0f-400f-a20d-36b764690911">
<img width="410" alt="Screenshot 2023-05-30 at 16 02 34" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/23613035-30b5-45c6-86f5-896ae54790fd">
<img width="408" alt="Screenshot 2023-05-30 at 16 02 41" src="https://github.com/hackforla/CivicTechJobs/assets/107892670/105e2aa7-943f-4de9-aa0b-7c3341f8cf79">

**Comment by sabheasley** [comment]
Hello @geibu! Can you please provide an update here prior to our Tuesday meeting:
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by geibu** [comment]
1. Currently finalizing research plan and prototype for testing
2. N/A

**Comment by kcoronel** [comment]
Hi @geibu can you please provide updates answering the following questions prior to our meeting, ty! 
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by geibu** [comment]
Update: Finalized and reviewed prototype with UXR team, finished pilot testing, and now getting ready for user testing

**Comment by sabheasley** [comment]
> Hi @geibu can you please provide updates answering the following questions prior to our meeting, ty!
> 
> 1. Progress
> 2. Blockers
> 3. Availability
> 4. ETA

Please edit this comment to give us an update! @geibu

**Comment by kcoronel** [comment]
All tasks completed, check #453 for more details regarding usability testing and results.
