### ISSUE TITLE
CMS Dashboard Wireframes - Tin

### ISSUE THREAD

**Issue by TCUX** [hackforla/CivicTechJobs#327]
### Overview

As a designer, we need to create a content management system to allow project managers and team leads to post, edit, manage, and analysis roles for Civic Tech Jobs. For this issue, we will create wireframes to ideate and revise toward high-fidelity screens. 

### Action Items

- [x] Wireframe Dashboard
- [x] Dashboard Review
- [x] Wireframe other additional pages if needed. (not needed) 

### Resources/Instructions

[Figma](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=114%3A51437)

**Comment by TCUX** [comment]
![DASHBOARD - ROLE - V1](https://user-images.githubusercontent.com/105838543/196372278-63586b69-568e-4479-8bce-ca485a3e22fd.PNG)
![DASHBOARD - ROLE - V2](https://user-images.githubusercontent.com/105838543/196372315-cf4e10a4-d1d0-45bb-8604-d0256a5893d1.PNG)

**Comment by TCUX** [comment]
![Role Posting - General Information](https://user-images.githubusercontent.com/105838543/218335843-68c228f4-6f0d-4550-9424-1d6e79f164bb.PNG)
![Role Posting - Techinical Requirement](https://user-images.githubusercontent.com/105838543/218335845-408c2d1c-38d4-4db0-91c7-8aaddccd597e.PNG)
![Role Posting - Contact Information](https://user-images.githubusercontent.com/105838543/218335847-36f95cd1-907d-4e17-9d3e-81432d990336.PNG)
![Role Posting - Review](https://user-images.githubusercontent.com/105838543/218335848-2d276c93-fa4a-48c1-aab1-d4f2f8597206.PNG)

**Comment by TCUX** [comment]
![open role dashboard](https://user-images.githubusercontent.com/105838543/223572483-72ff8727-a279-467e-a024-b7be1a737f5a.PNG)

**Comment by kcoronel** [comment]
Hi @TCUX  can you please provide updates answering the following questions prior to our meeting, ty! 
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by sabheasley** [comment]
Hi @TCUX can you please provide updates answering the following questions prior to our meeting, ty!

1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by sabheasley** [comment]
> Hi @TCUX can you please provide updates answering the following questions prior to our meeting, ty!
> 
> 1. Progress
> 2. Blockers
> 3. Availability
> 4. ETA


@TCUX please edit this comment to give us an update!

**Comment by kcoronel** [comment]
Closing this issue as it looks like all Action Steps have been completed and screenshots for CMS wireframes are above.
