### ISSUE TITLE
Blurb/copy to go with hero image on landing page

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#33]
We need a SHORT blurb/copy to go with the hero image on the CivicTechJobs' landing page.

It must communicate:
-our value proposition
-the value of them, the volunteers... that our work is thanks to the power of volunteers

Action Items:
- [ ] draft blurb
- [ ] run it by someone (like Bonnie)

Resources:
https://www.hackforla.org/

**Comment by patula006** [comment]
I can work on the welcoming blurb/copy for hero section of landing page.

**Comment by patula006** [comment]
Working version - feedback welcome!

Hello from CivicTechJobs where all are welcome to help create civic impact that matters! We bring together civic-minded volunteers such as YOU to help build digital products, programs, and services. Thanks to the power of our volunteers, we are able to partner with local communities and governments to address a range of issues in the Los Angeles region and beyond.

**Comment by Aveline-art** [comment]
Hi @patula006, the wording on [the blurb](https://github.com/hackforla/CivicTechJobs/issues/33#issuecomment-929715792), especially the last sentence, feel a little clunky. I am wondering if we can split or recombine the sentences/phrases so that we can get a greater impact?

**Comment by patula006** [comment]
**Thank you, Ava! Updated blurb for feedback:**
Hello from CivicTechJobs where all are welcome to help create civic impact that matters! We bring together civic-minded volunteers such as YOU to help build digital products, programs, and services for local communities and governments. Thanks to the power of our volunteers, we can positively impact the Los Angeles region and beyond.

**Comment by sdimran** [comment]
@patula006, please see below for an extract from our one sheet which outlines the goal and vision of Civic Tech Jobs, specifically the bolded section. can we incorporate some of the items from below into your updated blurb? let me know if you have any thoughts or feedback around it!

The goal of CivicTechJobs is to give technology practitioners interested in having civic impact the tools and opportunity to find jobs or volunteer opportunities from a central hub of listings. **The first phase of the project will focus on providing the potential volunteers a platform to find a project at HackforLA, connecting ambitious and like minded individuals together to help build digital products, programs, and services.** For this phase, the website’s key features would include a list of open volunteer positions for projects undertaken by HackforLA and a self-filter option to find the best match for the volunteer’s skills, interest, and availability. The website will then guide the volunteer to the onboarding process to join the project of their interest.

**Comment by sharadgaurav7** [comment]
@sdimran , we should not include the write up from the one sheet, please. The audience is different for the landing page.

**Comment by patula006** [comment]
Thank you ... to confirm - this working version (still open to feedback) is ok?
Thanks for letting me know if I should use the sheet or not. Patty

_Hello from CivicTechJobs where all are welcome to help create civic impact that matters! We bring together civic-minded volunteers such as YOU to help build digital products, programs, and services for local communities and governments. Thanks to the power of our volunteers, we can positively impact the Los Angeles region and beyond._

**Comment by patula006** [comment]
Thanks, Jen!
