### ISSUE TITLE
Epic: Credits Page

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#332]
### Dependency

- [x] #333 
- [x] #361

### Overview

This is an epic for the development of the credits page.

### Action Items

- [x] Find the credits page in figma.
- [x] Create it.

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by kcoronel** [comment]
@Aveline-art will create a new issue after splitting this issue for what can be worked on by someone else and what Ava has already done

**Comment by Aveline-art** [comment]
This ticket was split to #361 which was [merged in](https://github.com/hackforla/CivicTechJobs/pull/362).
