### ISSUE TITLE
404 result page

### ISSUE THREAD

**Issue by fenglugithub** [hackforla/CivicTechJobs#334]
### Overview

We need to design a 404 result page so that a user will get a visual notice when they there's no search result found.

### Action Items

- [x] Ideate
- [x] Present to the team
- [x] Feedback
- [x] Iterate
- [x] Present to the team

### Resources/Instructions

[Requirements](https://docs.google.com/spreadsheets/d/1VcDLJnDA5CE7euzaZxOcqS3LLgyUFVLeqvdZx2sFGQk/edit#gid=477987515)

**Comment by fenglugithub** [comment]
Ideations for the 404 error page. 
Based on our UX meeting, 1. we selected left and right layout, 2. trying more colors. 3. make sure illustration style consistency (source from: storyset/pana)

[404 Error Page](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=5875%3A52346&t=gfuzzeLGZejYNyzW-1)

<img width="851" alt="Screen Shot 2022-11-15 at 7 33 50 PM" src="https://user-images.githubusercontent.com/43657452/202077233-0c5e9262-96eb-44ac-96e0-20adcd8474e2.png">
YNyzW-1)

<img width="874" alt="Screen Shot 2022-11-15 at 7 33 37 PM" src="https://user-images.githubusercontent.com/43657452/202077273-1f4b899e-20be-42ef-970b-396e4ddffa71.png">

<img width="875" alt="Screen Shot 2022-11-15 at 7 33 24 PM" src="https://user-images.githubusercontent.com/43657452/202077493-84f98801-dfb0-4afe-aee4-ab72f92758b6.png">

<img width="867" alt="Screen Shot 2022-11-15 at 7 33 30 PM" src="https://user-images.githubusercontent.com/43657452/202077315-4d7cb1aa-0e49-4acd-8f16-883e882cdc9c.png">

**Comment by fenglugithub** [comment]
@salima This issue is done and ready to be closed.

[404 Error Page final version](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=5875%3A52977&t=oRjnV3sAuviLn0PI-1)
<img width="672" alt="Screen Shot 2022-11-27 at 6 19 11 PM" src="https://user-images.githubusercontent.com/43657452/204177666-28537fe2-132f-474b-a059-49222ffa23a4.png">

**Comment by kcoronel** [comment]
Closing this issue as we have completed this page.
