### ISSUE TITLE
Data Sourcing

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#335]
### Overview

As a developer, we need to make sure that we can source our data, and that we have a plan to retrieve that data. For this ticket, we will start a research sprint into where we can and cannot find our data.

### Action Items

- [ ] See below for a list of data we need
- [ ] For each data, find the source for our data
- [ ] Create a plan to retrieve that data

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by kcoronel** [comment]
@Aveline-art added a dependency label and moved it to the Ice Box because we have a dependency on teams such as VRMs and People Depot

**Comment by Aveline-art** [comment]
Closing this since this ticket is a repeat of the backend ticket such as #220
