### ISSUE TITLE
Coming Soon Page

### ISSUE THREAD

**Issue by salimays** [hackforla/CivicTechJobs#336]
### Overview

We need to create a Coming Soon page so when traffic comes to civictechjobs.org the users will see the coming soon page instead of nothing.  This will also allow us to point the domain name.

#### Details
The URL https://staging.civictechjobs.org is going to show to dev instance of the website.  In the future, prod will be seen by visiting civictechjobs.org.  In the meantime we need a coming soon page, and it does not have to be hosted on our code base, or built by devs. 

We can't point the staging.civictechjobs.org without have a place for the traffic to the civicitechjobs.org to go.

### Action Items
- [x] Create a Coming Soon page (this can be on Mailchimp or any other free location that has a website builder)
  - [ ] This can include a mailing list or not
- [x] Once the URL and page layout for the new coming soon page is built, then Development will create an index page that loads the coming soon page in an iframe.  
  - [ ] If you need a seperate repo for this, go ahead and create one called civictechjobs-prelaunch

### Resources/Instructions
- [Resources](https://hackforla.github.io/CivicTechJobs/resources/)
- [DRAFT Coming Soon Options](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=6294%3A65136&t=uXIgO7VKCUQlyuiq-0)

#### Example from another project
index.html: https://github.com/100Automations/landingpage/blob/main/index.html
the Mailchimp page it loads in its iframe: https://mailchi.mp/6f150ef215c6/100automations
[MailChimp Link of Landing Page](https://mailchi.mp/6e199f5c087f/civic-tech-jobs)

#### Examples of Sites with HackforLA Logo/give credit
https://expungeassist.org/#/
https://about.ballotnav.org/
https://100automations.org/

**Comment by kcoronel** [comment]
Taken from Slack between @jenchuu @salimays @me: 

From Jen: 
Gabe made two versions of the Coming Soon page - can be found on Figma,[ here](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=6294%3A65136&t=uXIgO7VKCUQlyuiq-0) 
We discussed at our UX meeting are making some changes/improvements this week.
QUESTION: Do we also need to set up the entire thing including the final welcome email sent out after subscribing ?

From Salima: 
Bonnie only wanted the coming soon page so we can tackle the email next.

**Comment by geibu** [comment]
<img width="2128" alt="Screenshot 2023-02-28 at 5 18 29 PM" src="https://user-images.githubusercontent.com/107892670/222020163-42ac95a9-0ef1-4d69-bef2-f367889d1be3.png">

Here's the coming soon page created via MailChimp!

**Comment by geibu** [comment]
<img width="2116" alt="Screenshot 2023-02-28 at 5 21 06 PM" src="https://user-images.githubusercontent.com/107892670/222020507-e12c6c9a-7995-475c-b90c-bdf916e636c1.png">

Took out the subscribe and email portion since it is not needed at the moment.

**Comment by kcoronel** [comment]
Jen will chat with Gabe.

**Comment by kcoronel** [comment]
@jenchuu Bonnie and I were working on activating the URL for the coming soon page. Here are a few edits (please note I'm referring to what is on MailChimp now) 
- We don't want folks emailing us but rather want them to input their email 
- We don't need to link to 1-page but we can link to our Hack for LA project page 
- We need to add Hack for LA logo

**Comment by kcoronel** [comment]
@jenchuu friendly ping about the above comments

**Comment by jenchuu** [comment]
Updated since Gabe was out last week! Let me know if this works.
![CTJ Coming Soon page on Mailchimp](https://user-images.githubusercontent.com/88695763/234428241-8f85215a-4517-43d9-97fe-eda4b7d3db2a.png)

**Comment by jenchuu** [comment]
@kcoronel @geibu 
Can you confirm the emails entered on the page are linked to our Gmail ?
