### ISSUE TITLE
Cookies Policy Page

### ISSUE THREAD

**Issue by TCUX** [hackforla/CivicTechJobs#337]
### Overview

As a UX designer, we need to add cookies policy page and pop-up card to ensure the users understand how their data is collected, shared, and used.

### Action Items

- [x] Find cookies template
- [x] Ask for PMs cookies policy writing for policy page
- [x] 1st Round Review
- [x] Iterate
- [x] Final Review

### Resources/Instructions

[Resources](http://civictechindex.org/privacy)
[Figma](https://www.figma.com/proto/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?page-id=1%3A34&node-id=5913%3A50930&viewport=321%2C210%2C0.13&scaling=scale-down)

**Comment by TCUX** [comment]
![Cookie Policy Card_S1](https://user-images.githubusercontent.com/105838543/213032287-2077e0e8-8732-40fe-bed0-3d08dff414e5.PNG)

![Cookie Policy Card_S2](https://user-images.githubusercontent.com/105838543/213032346-004838a9-21ae-4612-a261-1cc416d95a40.PNG)
![Cookie Policy Card_S3](https://user-images.githubusercontent.com/105838543/213032362-43f9f491-b418-4903-bc3a-edffa374a83e.PNG)
![Privacy Policy Page](https://user-images.githubusercontent.com/105838543/213032371-437fa4cd-7812-4b3f-8a9f-5039dd161506.PNG)

**Comment by TCUX** [comment]
![Cookies A](https://user-images.githubusercontent.com/105838543/214437059-329e54ac-056a-484b-90e2-af97265aac9f.PNG)

![Cookies B](https://user-images.githubusercontent.com/105838543/214437079-6b855e67-6039-4f9e-b620-28146fad3a07.PNG)

![Cookies C](https://user-images.githubusercontent.com/105838543/214437094-07a11cba-9b7a-49b6-bb8c-b65af388a567.PNG)

![Privacy Policy Page V2](https://user-images.githubusercontent.com/105838543/214437104-6f439348-4955-419f-ba18-a81983c01f4c.PNG)

**Comment by kcoronel** [comment]
Closing as all Action Items have been completed.
