### ISSUE TITLE
Editing Calendars

### ISSUE THREAD

**Issue by salimays** [hackforla/CivicTechJobs#339]
### Overview

For the December break, we need to pause the Civic Tech Jobs meetings. This issue will explain how to do it. 

### Action Items

- Step 1: accessing the civctechjobs@gmail.com account through 1password 
- Step 2: editing the calendar 1

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by kcoronel** [comment]
Outdated issue
