### ISSUE TITLE
Epic: Search Results Page

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#340]
### Dependency

- [x] #333 
- [x] #342
- [x] #341

### Overview

This is an epic for the development of the search results page.

### Action Items

- [ ] Find the search results page in figma.
- [ ] Create it.
- [ ] Note: there are new images/icons on this page, so make sure to upload them to our assets.

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by ExperimentsInHonesty** [comment]
I moved this to new issue approval because all the dependency are clear

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of #552
