### ISSUE TITLE
 Component: Create the notification bar component

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#342]
### Overview

As a developer we need to develop components that help us reuse code. For this issue, we will make the chevron scroll component.

### Action Items

- [ ] Find notification bar in figma under design system
- [ ] Create it
- [ ] Make sure it is accessible
- [ ] Make sure it is reusable
- [ ] This component is rather simple, but one optional improvement would be to have different modes:
  - [ ] Stay on the page mode.
  - [ ] Disappear after a set period mode (this should accept any animations created via [react-transition](https://reactcommunity.org/react-transition-group/))

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by kcoronel** [comment]
Hey @gjagnoor are you actively working on this? If not, can we move this to the Ice Box?
