### ISSUE TITLE
Storage for wiki images

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/CivicTechJobs#346]
### Dependency
When its needed.

### Overview
We need to have a place to store images we use in the wiki or other places that are not the code for the website

### Action Items
- [ ] Add image and details about where it is used

**Comment by ExperimentsInHonesty** [comment]
Used on the job [posting board for product ](https://github.com/hackforla/product-management/projects/8#card-84843586)
![image](https://user-images.githubusercontent.com/37763229/216711442-d23388f1-3195-4420-b342-2b3ad4ff041f.png)

**Comment by Aveline-art** [comment]
We do not need this. We will not do or maintain this.
