### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#350]
### Overview

As a developer, we should create new pages. For this issue, let's make the 404 page.

### Action Items

- [x] Find 404 page in Figma.
- [x] Create it.
- [x] Add it to react router as a 404 page.
- [x] Make sure that Django renders the 404 page, when we visit an invalid page.

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)
[Django's doc on views](https://docs.djangoproject.com/en/4.1/ref/views/)
[ReactRouter v6 doc on error element](https://reactrouter.com/en/main/start/tutorial#not-found-data)

**Comment by MattPereira** [comment]
Stashing additional links that may be helpful

- https://docs.djangoproject.com/en/4.2/topics/http/views/#django.http.Http404
