### ISSUE TITLE
mouseup event does not register accurately in the Calendar component (used in How To Join)

### ISSUE THREAD

**Issue by gjagnoor** [hackforla/CivicTechJobs#351]
### Overview

When the mouse is moved really fast, the `mouseup` event does not register accurately in the `Calendar` component that is used in `How to Join`. As a result, cells keep getting selected.  The bug does not appear consistently, it happens once in a while. 

Hypothesis: The mouse moving rapidly causes a race condition with the JS stack. 

### Action Items

- [ ] Understand how the Calendar and accompanying components work together to select/deselect cells in the calendar. 
- [ ] Find the code that is causing this potential race condition or mouseup event not to register
- [ ] Test fixes. Confirm that with the fix, select on click and select on mouse move features are still functional.  

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by nooriaali9** [comment]
This issue is out of scope - closing it out
