### ISSUE TITLE
CMS Role Posting Wireframes - Gabe

### ISSUE THREAD

**Issue by geibu** [hackforla/CivicTechJobs#357]
### Overview

As a designer, we need to create the Role Posting Flow for the Content Management System (CMS) to allow project managers and team leads to manage posts (create, view, and archive) for role openings. For this issue, we will create wireframes to efficiently ideate and revise toward high-fidelity screens.

### Action Items

- [ ]  Wireframe role posting flow
- [ ]  Wireframe other additional pages

### Resources/Instructions

[Figma](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=6543%3A63371&t=HvmRTDySIuPH8pOe-1)

**Comment by geibu** [comment]
Side bar limited to just what we need for the mvp, which is to:
- Create a role
- Access open roles
- Access archive

Added a drop-down for the different CoPs so that role selection would be easier
- Drop down from roles would auto-populate depending on what CoP is chosen

“?” modal shows differences in level so that OPs can reference
- Question: if the “Lead” role is chosen (e.g. Engineering Practice Lead, UX Practice Lead, etc.), would the level default to a higher level?

Larger text inputs: maybe we can keep a few?
- Not sure what the maximum character limit is yet

<img width="606" alt="Screenshot 2023-02-28 at 10 23 25 AM" src="https://user-images.githubusercontent.com/107892670/221944981-f791147a-078d-4122-9ccd-fd8a65ee4f3f.png">

---------

"Add notes" for minimal noting purposes - which then displayed in italics under that meeting schedule
- Changes to "edit note" when a note is added
- Character limit for meeting notes text input would be small compared to the role description text input

"Supplemental" - other optional meeting times not directly related to the role posted 

<img width="606" alt="Screenshot 2023-02-28 at 10 23 43 AM" src="https://user-images.githubusercontent.com/107892670/221945020-fb68d76d-560a-4844-aff3-3e6a9b48cc7d.png">

---------

Is the "additional description" necessary?
*Switched things up a bit to reflect the hierarchy of the input fields*

*Edit icon looks a little weird being just in the air without a divider*
--- Clicking the edit icon will just take them back to the previous step

*Do we maybe need a save borderless button?*

<img width="606" alt="Screenshot 2023-02-28 at 10 23 55 AM" src="https://user-images.githubusercontent.com/107892670/221945052-304713b3-1152-4ba6-a60f-239d0af34b59.png">

**Comment by geibu** [comment]
Side bar limited to just what we need for the mvp, which is to:
- Create a role
- Access open roles
- Access archive

Added a drop-down for the different CoPs so that role selection would be easier
- Drop down from roles would auto-populate depending on what CoP is chosen

“?” modal shows differences in level so that OPs can reference
- Question: if the “Lead” role is chosen (e.g. Engineering Practice Lead, UX Practice Lead, etc.), would the level default to a higher level?

Larger text inputs: maybe we can keep a few?
- Not sure what the maximum character limit is yet

<img width="606" alt="Screenshot 2023-02-28 at 10 23 25 AM" src="https://user-images.githubusercontent.com/107892670/221944981-f791147a-078d-4122-9ccd-fd8a65ee4f3f.png">

---------

"Add notes" for minimal noting purposes - which then displayed in italics under that meeting schedule
- Changes to "edit note" when a note is added
- Character limit for meeting notes text input would be small compared to the role description text input

"Supplemental" - other optional meeting times not directly related to the role posted 

<img width="606" alt="Screenshot 2023-02-28 at 10 23 43 AM" src="https://user-images.githubusercontent.com/107892670/221945020-fb68d76d-560a-4844-aff3-3e6a9b48cc7d.png">

---------

Is the "additional description" necessary?
*Switched things up a bit to reflect the hierarchy of the input fields*

*Edit icon looks a little weird being just in the air without a divider*
--- Clicking the edit icon will just take them back to the previous step

*Do we maybe need a save borderless button?*

<img width="606" alt="Screenshot 2023-02-28 at 10 23 55 AM" src="https://user-images.githubusercontent.com/107892670/221945052-304713b3-1152-4ba6-a60f-239d0af34b59.png">

**Comment by sabheasley** [comment]
Hello @geibu! Can you please provide an update here prior to our Tuesday meeting:
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by geibu** [comment]
1. Currently finalizing research plan and prototype for testing
2. N/A

**Comment by kcoronel** [comment]
Hi @geibu can one of you please provide updates answering the following questions prior to our meeting, ty! 
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by geibu** [comment]
Update: Finalized and reviewed prototype with UXR team, finished pilot testing, and now getting ready for user testing

**Comment by sabheasley** [comment]
> Hi @geibu can you please provide updates answering the following questions prior to our meeting, ty!
> 
> 1. Progress
> 2. Blockers
> 3. Availability
> 4. ETA

Please edit this comment to give us an update!

**Comment by kcoronel** [comment]
All tasks completed with this issue. Check Issue #453 for more details on usability testing.
