### ISSUE TITLE
CMS Role Posting Wireframes - Lu

### ISSUE THREAD

**Issue by fenglugithub** [hackforla/CivicTechJobs#358]
### Overview

As a designer, we need to create the Role Posting Flow for the Content Management System (CMS) to allow project managers and team leads to manage posts (create, view, and archive) for role openings. For this issue, we will create wireframes to efficiently ideate and revise toward high-fidelity screens.

### Action Items

- [x] Wireframe CMS role posting
- [x] Feedbacks from Team
- [x] Ideate CMS role posting
- [x] Feedbacks from Team
- [ ] Ideate CMS role posting

### Resources/Instructions

- [x] #255 

[Figma](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=6525%3A63177&t=JQQy5W1y1N218alV-1)

**Comment by fenglugithub** [comment]
Working on role posting flow, based on the feedback from our UX meeting, I updated basic info input page.

- Add note function for MEETING TIMES
- Update CONTACT US
- Dropdown menu for PROJECT, ROLE TITLE, SKILLS, EXPERIENCE LEVEL

<img width="848" alt="Screenshot 2023-02-28 at 5 20 09 PM" src="https://user-images.githubusercontent.com/43657452/222021239-2bad9c81-799b-4bc1-a6d6-e18f2361304a.png">
<img width="849" alt="Screenshot 2023-02-28 at 5 20 32 PM" src="https://user-images.githubusercontent.com/43657452/222021242-ecd0765c-a5d3-4e3f-8bbd-2ab1e45729bd.png">
<img width="841" alt="Screenshot 2023-02-28 at 5 20 44 PM" src="https://user-images.githubusercontent.com/43657452/222021244-3825d551-71cd-4a88-816f-f8866e628c2c.png">

Will keep working on Role Description and Preview page.

For Role Description page
- Simplify type editing for text input
- Add maximum characters

<img width="785" alt="Screenshot 2023-02-28 at 5 27 52 PM" src="https://user-images.githubusercontent.com/43657452/222021383-5e1351d2-1d42-4c14-a26c-2087104dde8e.png">

For Preview Page
- Preview page design mimic UI for Role Posting page
- Editing page for user would like editing the information on Preview page.

<img width="662" alt="Screenshot 2023-02-28 at 5 28 09 PM" src="https://user-images.githubusercontent.com/43657452/222021414-76f282bf-5a1f-410c-b385-125d134f5319.png">

**Comment by fenglugithub** [comment]
Ideate Role posting - preview page
[CMS Role posting](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?type=design&node-id=7086%3A70707&t=AA2blYJyUqyNqVuU-1)

<img width="611" alt="Screenshot 2023-05-15 at 1 30 31 PM" src="https://github.com/hackforla/CivicTechJobs/assets/43657452/05eb6161-863f-4858-8acb-bc22339f8504">


<img width="607" alt="Screenshot 2023-05-15 at 1 30 50 PM" src="https://github.com/hackforla/CivicTechJobs/assets/43657452/6e27c6ef-e911-4410-8f90-4f14b647a0c9">


<img width="532" alt="Screenshot 2023-05-15 at 1 31 13 PM" src="https://github.com/hackforla/CivicTechJobs/assets/43657452/89168e7d-a788-47f9-b2e7-cb3981fcf449">


<img width="554" alt="Screenshot 2023-05-15 at 1 31 26 PM" src="https://github.com/hackforla/CivicTechJobs/assets/43657452/9d13f0f1-9e09-4db2-b1f9-b24acc5253e3">

I've got feedback from team, will work on the updates.

**Comment by sabheasley** [comment]
Hello @fenglugithub! Can you please provide an update here prior to our Tuesday meeting:

- [ ] Progress
- [ ] Blockers
- [ ] Availability
- [ ] ETA

**Comment by kcoronel** [comment]
Hi @fenglugithub can you please provide updates answering the following questions prior to our meeting, ty! 
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by sabheasley** [comment]
Hi @fenglugithub can you please provide updates answering the following questions prior to our meeting, ty!

1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by sabheasley** [comment]
> Hi @fenglugithub can you please provide updates answering the following questions prior to our meeting, ty!
> 
> 1. Progress
> 2. Blockers
> 3. Availability
> 4. ETA

@fenglugithub please edit this comment to provide an update!
