### ISSUE TITLE
CMS Role Posting Wireframes - Tin

### ISSUE THREAD

**Issue by TCUX** [hackforla/CivicTechJobs#360]
### Overview
As a designer, we need to create a content management system to allow project managers and team leads to post, edit, manage, and analysis roles for Civic Tech Jobs. For this issue, we will create wireframes to ideate and revise toward high-fidelity screens.

### Action Items

- [x] Wireframe Job Posting wireframe and flow 
- [x] Dashboard Review
- [x] Wireframe other additional pages if needed.

### Resources/Instructions

[Figma](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=114%3A51437)

**Comment by TCUX** [comment]
![ADD NEW ROLE FIRST PAGE](https://user-images.githubusercontent.com/105838543/223573531-9ddebc9c-f06f-415c-9207-c04e609016a1.PNG)

![JOB POSTING 1](https://user-images.githubusercontent.com/105838543/223573746-f5f77757-cd95-452b-bc90-cc6ff6636659.PNG)


![skill selection as](https://user-images.githubusercontent.com/105838543/223573767-7c3f5ce9-f686-494d-97db-335a08a6b398.PNG)

![skill selection b](https://user-ima
![review page](https://user-images.githubusercontent.com/105838543/223573818-e07838a2-d9b5-45fd-9fad-5439ebdfa883.PNG)
ges.githubusercontent.com/105838543/223573789-860f3dee-945b-4c16-bf27-f35f18aa1d9f.PNG)

**Comment by TCUX** [comment]
![CMS - ROLE POSTING A](https://user-images.githubusercontent.com/105838543/234403830-123e38d1-64be-4a1b-9a2f-c2666a9a35a9.PNG)
![CMS - ROLE POSTING - SKILL SELECTION](https://user-images.githubusercontent.com/105838543/234403855-3ec78bc5-3a71-44b7-a330-443e263d7c7a.PNG)
![CMS - ROLE POSTING MEETING INFO](https://user-images.githubusercontent.com/105838543/234404115-1ef1eb53-c033-4968-98e5-052ac93ae93c.PNG)
![CMS - ROLE POSTING - PREVIEW](https://user-images.githubusercontent.com/105838543/234404138-ee31a6fa-d6f4-4bdb-8637-c881aa61cbc1.PNG)

**Comment by sabheasley** [comment]
Hello @TCUX! Can you please provide an update here prior to our Tuesday meeting:

- [ ] Progress
- [ ] Blockers
- [ ] Availability
- [ ] ETA

**Comment by kcoronel** [comment]
Hi @TCUX can you please provide updates answering the following questions prior to our meeting, ty! 
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by sabheasley** [comment]
Hi @TCUX can you please provide updates answering the following questions prior to our meeting, ty!

1. Progress 
3. Blockers 
4. Availability 
5. ETA

**Comment by sabheasley** [comment]
> Hi @TCUX can you please provide updates answering the following questions prior to our meeting, ty!
> 
> 1. Progress
> 2. Blockers
> 3. Availability
> 4. ETA

@TCUX please edit this comment to give us an update!

**Comment by kcoronel** [comment]
Tin did not close out this issue before taking a break from the project due to a heavier workload. After reviewing the project Figma, I can see that the above images were Tin's submissions for what the CMS page should look like.
