### ISSUE TITLE
Skills Matrix

### ISSUE THREAD

**Issue by salimays** [hackforla/CivicTechJobs#363]
### Overview

~This is the Skills Matrix we'll use to onboard new volunteers:~
~- The job poster checks the skills that will be flexed in the job.~
~- The volunteer checks the skills they already have.~

We need to add screens for role seekers to self evaluate skills and role posters to indicate what they need in the person filling the role.

### Details
- Role titles are hard to use because they mean different things to different people and organizations
- We need an objective way to connect people with roles

### Action Items

- [ ] Share the Skills Matrix with the team
- [ ] Define how it will be integrated in the MVP
~- [ ] Draft a PM Skills Matrix (@salimays)~
~- [ ] Draft a Dev Skills Matrix (@kcoronel)~

### Resources/Instructions
- [Resources](https://hackforla.github.io/CivicTechJobs/resources/)
- [Skills and experience matrix example](https://docs.google.com/spreadsheets/d/1_sCd8Kc2Tlhe--8UJLkgyDoqyQw_eZxhie3QTOwTHrM/edit#gid=1739253474)
- [UX design roles](https://docs.google.com/presentation/d/1qEnWq4rPxZm0ZtEsa1T0HoNpjuLxvJU2SlweiLYugwo/edit#slide=id.gcb3d64b1bf_1_0) -  example of too many titles that no one understands
  - This list grew out of the original [Experience Profile issue that new UI/UX CoP members make](https://github.com/hackforla/UI-UX/issues/new?assignees=&labels=experience+profile&template=template-for-UX-Experience-Profile.md&title=UX%2FUI+Experience+Profile%3A+YOUR+NAME_)

**Comment by kcoronel** [comment]
Notes from informal conversation with Bonnie 3/17 after PM meeting 

**If it is not a fit for purpose then it is not MVP**

There is a need for the Civic Tech Jobs tool to: 
- make it easier for open roles to be posted 
- to enforce organizational requirements i.e. Kanban board management (one classic project board for the team) and label criteria on issues 

Pros for Skills Matrix: 
- Helps navigate the number of job titles that disciplines have i.e. 

review job postings


teach teams for how to not go crazy on the boxes
small chunks as possible
not enterprise model
raise myself on exposure level

link for posting - all issues person is eligible to work on
backend/frontend links to issues (filtered view from prioritized backlog)
enforce discipline

looking for a role - and not have any issues for them

“what do you want to do”
api that searches
label automatically
api could let us know what label
reenforce standard of not single board
has size, and skill level labels

**Comment by kcoronel** [comment]
@salimays removing you from this issue and closing it up as the issue #383 will be replacing this task.
