### ISSUE TITLE
Reviewing MVP Requirements for Any Emergent Requirements 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/CivicTechJobs#365]
### Overview

With the project underway and an emergent requirement for skills to be a part of the MVP, we need to determine if there are any other emergent requirements that the team should be aware of. 

### Action Items

- [x] Update Requirements current excel format to a more readable and editable format 
- [x] Review current requirements with Bonnie for any emergent requirements 
- [ ] Update roadmap 
- [ ] Review updates with team 

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)
[CTJ Requirements](https://docs.google.com/spreadsheets/u/5/d/1VcDLJnDA5CE7euzaZxOcqS3LLgyUFVLeqvdZx2sFGQk/edit#gid=477987515)

**Comment by nooriaali9** [comment]
Since _Update roadmap_ is being worked on in issue 569 - closing this out
