### ISSUE TITLE
CoP Descriptions for landing page MVP

### ISSUE THREAD

**Issue by sdimran** [hackforla/CivicTechJobs#37]
We need to collect or create CoP descriptions to include under the landing page so that users who come to civictechjobs.org can get additional information about what we offer

**Comment by patula006** [comment]
It's a bit slow going trying to get feedback on the COP descriptions. Here are the ones that I've been able to complete so far (engineering and UI/UX). Feedback welcome! Thank you, Patty

The Engineering Community of Practice (COP) is a space for developers to share effective practices and set development standards and give and receive mentorship. Recent projects include career advancement strategy workshops and small tech talks including an architecture paradigm, testing, and a new technology series.

The Engineering Community of Practice (COP) is a space for developers to share effective practices and set development standards and give and receive mentorship. Recent projects include career advancement strategy workshops and small tech talks including an architecture paradigm, testing, and a new technology series.

**Comment by patula006** [comment]
whoops - UI/UX

The User Interface / User Experience (UI/UX) Community of Practice (COP) is a space for UI and UX designers and research professionals to share effective practices, and give and receive mentorship, set design and research standards, and to create guides for new projects. Recent projects include testing the interface of a new transportation management portal for the City of Los Angeles, designing the interface of the new volunteer opportunities website, and testing the usability of finding and signing up for new volunteer opportunities through Hack for LA website.

**Comment by sdimran** [comment]
Looks good @patula006 ! Please let me know which CoP's you have yet to get a response from and I can follow up with the leads. if there are further difficulties we can engage Bonnie
