### ISSUE TITLE
Update outdated GitHub actions deps

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#379]
### Overview

As a developer, let's update our code. For this we will update our dependencies.

### Action Items

- [x] Find the warnings from our build pipeline [here](https://github.com/hackforla/CivicTechJobs/actions/runs/4614562636).
- [x] Make the warnings go away.

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

<img width="800" alt="Screenshot 2023-04-06 at 3 33 47 PM" src="https://user-images.githubusercontent.com/62368440/230506048-e12a483b-4693-4a99-b3cd-0143f8475e83.png">

I suspect that some of the dependencies from our build pipeline still uses `set-output` which is deprecating in about 2 months, so updating them to latest should fix them. There is a concern that a version migration is needed, so a quick glance at a migration guide might be useful.

**Comment by MattPereira** [comment]
Both warnings appear to be occurring in the `Configure AWS credentials` step that uses `v1` of the `aws-actions/configure-aws-credentials`

![image](https://user-images.githubusercontent.com/73561520/230513802-ead4fd70-34a1-4b20-ae5e-f8d73b785402.png)


![image](https://user-images.githubusercontent.com/73561520/230513604-fcf0f9d2-51a3-4f73-99df-1f8a013c61d2.png)

**Comment by MattPereira** [comment]
`v2` of `configure-aws-credentials` seems to be using the updated environment file implementation so I think it should fix the `set-output` warning

<details><summary>See github.blog instructions for using set-output</summary>

![image](https://user-images.githubusercontent.com/73561520/230515353-ca3de0ad-3768-4ff5-bce6-89be37c4ed2a.png)

</details>


[See how v2 uses set-output ](https://github.com/aws-actions/configure-aws-credentials/search?q=set-output)with new `GITHUB_OUTPUT` environment file
