### ISSUE TITLE
Document Civic Tech Jobs  team meeting times and who Must/Should/Can attendMeeting times for different teams

### ISSUE THREAD

**Issue by sharadgaurav7** [hackforla/CivicTechJobs#38]
### Overview
We need accurate information about all team's meetings so that we can design a system that will allow potential volunteers to filter the roles by teams that meet when its convenient for them.

### Action Items
- [x] provide details about the each meeting in a comment by using a copy of the check boxes below
- [x] post a link to this issue on Survey all the teams in order to build an effective data model hackforla/CivicTechJobs#35 in a comment letting the civic tech jobs team know you are done.

### Resources/Instructions
```
- [ ] day
- [ ] start_time
  - [ ] AM
  - [ ] PM
- [ ] duration_in_min
- [ ] name_of_meeting
- [ ] who_must_attend
  - [ ] pm
  - [ ] all_leads
  - [ ] design_lead
  - [ ] research_lead
  - [ ] frontend lead
  - [ ] data_science_lead
  - [ ] design
  - [ ] research
  - [ ] frontend
  - [ ] backend
  - [ ] data_science
  - [ ] other: please explain
- [ ] who_should_attend
  - [ ] pm
  - [ ] all_leads
  - [ ] design_lead
  - [ ] research_lead
  - [ ] frontend lead
  - [ ] data_science_lead
  - [ ] design
  - [ ] research
  - [ ] frontend
  - [ ] backend
  - [ ] data_science
  - [ ] other: please explain
- [ ] who_can_attend
  - [ ] pm
  - [ ] all_leads
  - [ ] design_lead
  - [ ] research_lead
  - [ ] frontend lead
  - [ ] data_science_lead
  - [ ] design
  - [ ] research
  - [ ] frontend
  - [ ] backend
  - [ ] data_science
  - [ ] other: please explain
```

**Comment by sharadgaurav7** [comment]
- [ x] day
   - [x ] start_time
      - [ ] AM
      - [ x] PM
   - [ x] duration_in_min: 60
   - [ x] name_of_meeting: All Team Meeting
   - [ x] who_must_attend
      - [ x] pm
      - [ x] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] data_science
      - [ ] other: please explain
   - [ x] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ x] design
      - [ x] research
      - [ x] frontend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] data_science
      - [ ] other: please explain

**Comment by sharadgaurav7** [comment]
- [ ] day: Tuesday
   - [ ] start_time: 5PM PDT
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min: 60
   - [ ] name_of_meeting: UI/UX Meeting
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain

**Comment by sharadgaurav7** [comment]
- [ ] day: Sunday
   - [ ] start_time: 4PM, PDT
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min: 60 min
   - [ ] name_of_meeting: Product Managers Meeting
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain

**Comment by sdimran** [comment]
- [ ] day Tuesday
- [ ] start_time
  - [ ] AM
  - [ ] PM
- [ ] duration_in_min : 60 
- [ ] name_of_meeting: UI/UX Meeting
- [ ] who_must_attend 
  - [ ] pm
  - [ ] all_leads
  - [ ] design_lead
  - [ ] research_lead
  - [ ] frontend lead
  - [ ] data_science_lead
  - [ ] design
  - [ ] research
  - [ ] frontend
  - [ ] backend
  - [ ] data_science
  - [ ] other: please explain
- [ ] who_should_attend
  - [ ] pm
  - [ ] all_leads
  - [ ] design_lead
  - [ ] research_lead
  - [ ] frontend lead
  - [ ] data_science_lead
  - [ ] design
  - [ ] research
  - [ ] frontend
  - [ ] backend
  - [ ] data_science
  - [ ] other: please explain
- [ ] who_can_attend
  - [ ] pm
  - [ ] all_leads
  - [ ] design_lead
  - [ ] research_lead
  - [ ] frontend lead
  - [ ] data_science_lead
  - [ ] design
  - [ ] research
  - [ ] frontend
  - [ ] backend
  - [ ] data_science
  - [ ] other: please explain
