### ISSUE TITLE
SkillS Matrix Design for Qualifier Page - Lu

### ISSUE THREAD

**Issue by fenglugithub** [hackforla/CivicTechJobs#390]
### Overview

As a member of Civic Tech Jobs, we need to design a Skills Matrix page stepper to replace the Roles page stepper of the Qualifier Page since it it a new Org requirement.

### Action Items

- [x] Ideate and wireframe
- [x] Feedback from team
- [x] Ideate V2 based on feedback
- [x] Feedback from team
- [x] Ideate V3 based on feedback

### Resources/Instructions

[Skills Matrix Figma Designs](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=7061%3A70375&t=O7vRvoay4wXYjI0y-1)

- [ ] #388

**Comment by fenglugithub** [comment]
#388

**Comment by fenglugithub** [comment]
Work on Skill Matrix Page slider version. Here's the first round designs.
[Skill Matrix Page V1](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?type=design&node-id=7061%3A70375&t=AA2blYJyUqyNqVuU-1)

<img width="660" alt="Screenshot 2023-05-15 at 1 15 34 PM" src="https://github.com/hackforla/CivicTechJobs/assets/43657452/bc807b4e-7b35-4926-93c7-2f0b59eea463">
<img width="636" alt="Screenshot 2023-05-15 at 1 15 51 PM" src="https://github.com/hackforla/CivicTechJobs/assets/43657452/8f7b2903-6b47-4d85-ad6e-d5feca8cec5b">

**Comment by fenglugithub** [comment]
Work on Skill Matrix Page slider Ideation V2. 
[Skill Matrix Page V2 ](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?type=design&node-id=7307%3A77941&t=AA2blYJyUqyNqVuU-1)

The default page:
<img width="384" alt="Screenshot 2023-05-15 at 1 18 46 PM" src="https://github.com/hackforla/CivicTechJobs/assets/43657452/ce0c6765-2479-458d-b95e-e6cf1c433533">

The actived page:
<img width="386" alt="Screenshot 2023-05-15 at 1 19 48 PM" src="https://github.com/hackforla/CivicTechJobs/assets/43657452/cab2c477-7c7c-40d1-ad6c-fbf461c33b75">

Different slider states:
<img width="481" alt="Screenshot 2023-05-15 at 1 20 17 PM" src="https://github.com/hackforla/CivicTechJobs/assets/43657452/bc72c59c-ec35-48b5-848e-36257d5bbb68">

I've got the feedback from team, will update the designs.

**Comment by sabheasley** [comment]
Hello @fenglugithub! Can you please provide an update here prior to our Tuesday meeting:

- [ ] Progress
- [ ] Blockers
- [ ] Availability
- [ ] ETA

**Comment by kcoronel** [comment]
Hi @fenglugithub can you please provide updates answering the following questions prior to our meeting, ty! 
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by sabheasley** [comment]
Hi @fenglugithub can you please provide updates answering the following questions prior to our meeting, ty!

1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by sabheasley** [comment]
> Hi @fenglugithub can you please provide updates answering the following questions prior to our meeting, ty!
> 
> 1. Progress
> 2. Blockers
> 3. Availability
> 4. ETA

@fenglugithub please edit this comment to provide an update!

**Comment by kcoronel** [comment]
Lu acknowledged that issue was complete at All Team Meeting 2/20/2024.
