### ISSUE TITLE
SkillS Matrix Design for Qualifier Page - Tin

### ISSUE THREAD

**Issue by TCUX** [hackforla/CivicTechJobs#391]
### Overview

As a member of Civic Tech Jobs, we need to design a Skills Matrix page stepper to replace the Roles page stepper of the Qualifier Page since it it a new Org requirement.

### Action Items

- [x]  Ideate and wireframe - Round 1
- [x] Review with design team
- [x] Ideate and wireframe - Round 2
~~- [ ] Review with design team~~
~~- [ ] Ideate and wireframe - Round 3~~
~~- [ ] Present to all hands meeting~~

### Resources/Instructions

[Skills Matrix Figma Designs](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=7061%3A70375&t=O7vRvoay4wXYjI0y-1)

- [ ] #388

**Comment by TCUX** [comment]
![SKILL MATRIX - PAGE 1](https://user-images.githubusercontent.com/105838543/235809150-dabbe6cf-3533-4e3e-887b-8b5155ede875.PNG)
![SKILL MATRIX - PAGE 2](https://user-images.githubusercontent.com/105838543/235809162-b95eac80-0c87-45d1-86ad-b1751e4760ce.PNG)
![SKILL MATRIX - PAGE 3](https://user-images.githubusercontent.com/105838543/235809183-f69d7298-bb66-4138-b55e-845e7bc69b81.PNG)
![SKILL MATRIX - PAGE 4](https://user-images.githubusercontent.com/105838543/235809194-d1c899e9-32c7-4b27-bc03-f281cf3daa21.PNG)
![SKILL MATRIX - PAGE 5](https://user-images.githubusercontent.com/105838543/235809201-12e4c0d1-8676-4c32-b478-1795e5e9b337.PNG)

**Comment by TCUX** [comment]
![image](https://github.com/hackforla/CivicTechJobs/assets/105838543/e5f050b5-920e-40c1-85de-c5dd27894677)

![image](https://github.com/hackforla/CivicTechJobs/assets/105838543/81604056-ff68-44b0-969c-2f0e38736cd4)

![image](https://github.com/hackforla/CivicTechJobs/assets/105838543/83e3a3ce-38e6-4df2-b51b-0386160d308c)

![image](https://github.com/hackforla/CivicTechJobs/assets/105838543/57381024-b5f0-45eb-b8c9-e9b99ae72f82)

**Comment by TCUX** [comment]
![image](https://github.com/hackforla/CivicTechJobs/assets/105838543/9f0d855e-816c-4d17-bfb4-a9c0c55c8e17)

![image](https://github.com/hackforla/CivicTechJobs/assets/105838543/c9e71f44-947e-468d-b4e1-98f6e25ee435)

![image](https://github.com/hackforla/CivicTechJobs/assets/105838543/35a89164-bb39-414c-85ce-00fe8a5b2152)

![image](https://github.com/hackforla/CivicTechJobs/assets/105838543/b25d8fad-0db3-4c17-9fea-aa8a612eea22)

**Comment by TCUX** [comment]
![image](https://github.com/hackforla/CivicTechJobs/assets/105838543/1a5379ab-ad0a-4afa-8ed6-d8e42e98bcfe)

![image](https://github.com/hackforla/CivicTechJobs/assets/105838543/ab56c760-9b4f-4992-89eb-7df40bb6d8ef)

![image](https://github.com/hackforla/CivicTechJobs/assets/105838543/acdb9b7f-d21d-4c20-824a-3f8bef1751a0)

**Comment by sabheasley** [comment]
Hello @TCUX! Can you please provide an update here prior to our Tuesday meeting:

Progress
Blockers
Availability
ETA

**Comment by kcoronel** [comment]
Hi @TCUX can you please provide updates answering the following questions prior to our meeting, ty! 
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by sabheasley** [comment]
Hi @TCUX can you please provide updates answering the following questions prior to our meeting, ty!

1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by sabheasley** [comment]
> Hi @TCUX can you please provide update (as a comment in this thread) answering the following questions prior to our meeting, ty!
> 
> 1. Progress
> 2. Blockers
> 3. Availability
> 4. ETA

@TCUX please edit this comment to give us an update!

**Comment by kcoronel** [comment]
I updated this issue's Action Items by placing a strikethrough through the items that were not able to be completed by Tin as he left the project at the end of November of 2023 due to workload increasing. Tin's designs for Skills Matrix can be seen above and wireframes can be found in our Figma.
