### ISSUE TITLE
Create a commit status for our jest tests

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#399]
### Overview

As a developer, let's make our code base easier to maintain. For this, we will enforce testing checks before allowing merges.

### Action Items

- [ ] For our jest test github action, create a commit status based on whether the tests failed to suceeded

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)
[commit-status-octokit](https://octokit.github.io/rest.js/v19#repos-create-commit-status)
[Create a commit status](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status)

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of #552
