### ISSUE TITLE
Use poetry dependency manager for our mkdocs site

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#404]
### Overview

As a developer, let's use the same build technologies across our services. For this ticket, we will convert our mkdocs site to using poetry.

### Action Items

- [ ] Convert our mkdocs site to use poetry

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

Note: We probably cannot do this via docker, so the easiest way to do this is to download poetry locally and use it to configure the .toml and .lock files. Then, we should change the mkdocs dockerfile to build using those files.

**Comment by kcoronel** [comment]
Hackfor LA has standardized on MK Docs - we need to install the extensions from material for MKDocs
