### ISSUE TITLE
Cost savings: Host static in s3 bucket

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#408]
### Overview

As a developer, we should keep our product scalable and cost effective. For this ticket, we will try to save on hosting costs by hosting our static in s3.

### Action Items

- [ ] Find a way to upload webpack bundled static onto s3 in staging and production (dev should continue to serve static locally)
- [ ] Also find a way to upload django collectstatic onto s3 in staging and production
- [ ] Configure django in staging and production to look for static from an s3 bucket

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

This is a good ticket to have in our back pocket when we need to cut costs. Since the frontend and backend directory is mostly independent of one another, we can further reduce our reliance on connecting them by serving our static via s3 rather than keeping them in our servers. This will reduce costs since hosting on s3 is dirt cheap.

**Comment by sabheasley** [comment]
@alexlaw528 Can you please give provide an update for this issue by answering the following:

Progress:
Blockers 
Availability:
ETA:

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of #552
