### ISSUE TITLE
build login/signup page layout

### ISSUE THREAD

**Issue by MattPereira** [hackforla/CivicTechJobs#440]
### Overview
We want to begin work on the Login in/ Sign up pages. For this issue, we will setup the new component layout and route.

### Action Items
- [x] Create page component for authentication page
- [x] Add "/login" and "/signup" paths to router
- [x] Enable tailwind css for the authentication page component
- [x] Update navbar so it looks like figma when user is visiting login or signup page

### Resources/Instructions
- [Figma Designs](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?type=design&node-id=1-26&mode=design&t=Py7eAJ2nlHoaLAfL-0)

**Comment by blulady** [comment]
https://github.com/hackforla/peopledepot/wiki/Cognito-authentication-workflow-(pre-deployment)
https://github.com/hackforla/peopledepot/blob/main/docs/architecture/authentication.md
https://github.com/hackforla/peopledepot/blob/main/docs/how-to/add-model-and-api-endpoints.md
https://djangostars.com/blog/bootstrap-django-app-with-cognito/
