### ISSUE TITLE
Add input validations to login and sign up forms

### ISSUE THREAD

**Issue by MattPereira** [hackforla/CivicTechJobs#445]
### Overview
We want to validate the inputs for the Log in and Sign up pages to help users provide the proper information.

### Action Items
- [x] Add react hook form package
- [x] Use react hook form to manage the state of the form inputs for `LoginForm` and `SignupForm` components
- [x] Add validations to the inputs according to the Figma designs

### Resources/Instructions
- https://www.react-hook-form.com/
- [Figma Designs](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?type=design&node-id=1-26&mode=design&t=3VgdLeHerbKHjyg8-0)

**Comment by sabheasley** [comment]
Hello @MattPereira ! Can you please provide an update here prior to our Tuesday meeting:

- [ ] Progress
- [ ] Blockers
- [ ] Availability
- [ ] ETA

**Comment by MattPereira** [comment]
> Hello @MattPereira ! Can you please provide an update here prior to our Tuesday meeting:
> 
> * [ ]  Progress
> * [ ]  Blockers
> * [ ]  Availability
> * [ ]  ETA

- https://github.com/hackforla/CivicTechJobs/pull/451

**Comment by sabheasley** [comment]
Hi @MattPereira  can you please provide updates answering the following questions prior to our meeting, ty!

1. Progress 
2. Blockers 
3. Availability 
4. ETA
