### ISSUE TITLE
Create Design System

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#45]
### Dependency

- [x] #168 
- [x] #170 
- [x] #172 

### Overview

As a designer, we need a design system to lay out standards and share with the dev team so they can build the website. We need to start creating components with states.

### Action Items

- [x] Create components and states
- [x] Discuss with dev team
- [x] Figure out best breakpoints
- [x] Discuss design system framework & best practices with HfLA's Design System team
- [x] Update design system to adhere to framework & best practices above

### Resources/Instructions

Reference HfLA's design system framework (once they complete it)

**Comment by jenchuu** [comment]
Started design system:

https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A2

<img width="357" alt="CTJ design system" src="https://user-images.githubusercontent.com/88695763/142087867-177b8c20-329b-4c72-9087-c530a96f2722.png">

**Comment by jenchuu** [comment]
Let me know if these breakpoints will work? @Aveline-art and Sarah (not sure what her @ is)
576px =< for mobile phones
577px-768px for tablets
769px-1024px for small screens, laptops
1025px-1200px for desktops, large screens
1201px => X-Large screens, TVs

**Comment by Aveline-art** [comment]
Hi @jenchuu ! I just reviewed the Figma and tried making a demo of the navbar. For the most part the breakpoints are fine, but one oddity I noticed is that the Figma designs are 1440px by width (x-large screens). Do you have any opinions on how the padding to the left of the logo, and the padding to the right of the button to scale as the screen size shrinks from X-large to desktops? If not, can we use our best judgment to handle it?

**Comment by jenchuu** [comment]
Hi @Aveline-art , would these breakpoints be better?

**Option 1**
<576px for XS
>=576px for S
>=768 for M
>=992px for L
>=1200px for XL
>=1400px for XXL
[](https://getbootstrap.com/docs/5.0/layout/breakpoints/)

**Option 2**
688px< for mobile phones
688px-992px for tablets
993px-1312px for small laptops
1312> for desktops
[](https://coder-coder.com/media-query-breakpoints/)

**Comment by jenchuu** [comment]
@Aveline-art We designed desktop for 1440px width since that is the standard desktop frame for Figma and also suggested by HfLA's design system!
Hmm I'm not too certain about padding. We designed it with 176px padding on the left and right (used 8pt system) so maybe scale by a multiple of 8? Please feel free to use your best judgment and expertise :)

**Comment by Aveline-art** [comment]
@jenchuu There might have been some misunderstanding. I am perfectly fine with any breakpoints. From a development perspective, all I really need is to have an idea of where the breakpoints are so that we can work around it. You can feel free to set any points that you feel is best for you and your team.

That being said, if you have a hard time deciding, these points that you sent us previously works perfectly fine for us.

> 576px =< for mobile phones
577px-768px for tablets
769px-1024px for small screens, laptops
1025px-1200px for desktops, large screens
1201px => X-Large screens, TVs

For the padding, we will try our best then!

**Comment by sharadgaurav7** [comment]
@jenchuu , can you please edit this issue as needed

**Comment by kcoronel** [comment]
Closed this issue because the work has been completed.
