### ISSUE TITLE
CMS Prototypes for Usability Testing

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#454]
### Overview

As a design team, we need to usability test the CMS designs to ensure flow makes sense and is functional for users. We will create limited clickable prototypes in Figma and work with the UXRs for testing.

### Action Items

- [x] Split up prototypes/tasks/scenarios among designers
- [x] Internal design team feedback session
- [x] Discuss with UXRs
- [x] Make any necessary edits
- [x] Pilot test (1 UXD + 1 UXR)

### Resources/Instructions
- [CMS Usability test link](https://www.figma.com/proto/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?page-id=1%3A38&type=design&node-id=7956-104005&viewport=163%2C458%2C0.04&t=85YTSrWWhWh6dJsG-1&scaling=min-zoom&starting-point-node-id=7956%3A104005&mode=design)
- [CTJ: CRM Usability Test Phase 2 General Folder](https://drive.google.com/drive/folders/1fxZoUKCVLNUubeDRFblcgONFGHNcNQMy?usp=drive_link)
- [Phase 2 Usability Testing Results](https://drive.google.com/file/d/1GibVbROw8nXcwzkLoLS0B6RE7ip2pdFq/view?usp=drive_link)

**Comment by kcoronel** [comment]
Hi @jenchuu and @geibu can one of you please provide updates answering the following questions prior to our meeting, ty! 
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by geibu** [comment]
Update: Finalized and reviewed prototype with UXR team, finished pilot testing, and now getting ready for user testing

**Comment by jenchuu** [comment]
1. Same as Gabe - he oversaw the pilot test for UXD team.
2. Not really, but may be slower since Jenn UXR Lead is out on vacation!
3. Available til Oct 18
4. ETA depends on UXR team's testing schedule :)

**Comment by sabheasley** [comment]
Happy Tuesday! @jenchuu and @geibu can one of you please provide updates answering the following questions prior to our meeting, ty!

1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by sabheasley** [comment]
Happy Tuesday! @jenchuu and @geibu please edit this comment with your updates!

Progress - 
Blockers 
Availability - 
ETA -

**Comment by kchotani** [comment]
@jayywu @melkosm Hey Karen asked me to check in with you, she recalls the pilot test happening ( mentioned above). Could you update the issue with the results or updates on how the test went, please. Thanks!

**Comment by kcoronel** [comment]
hey @Leah0996 can you provide updates related to the usability testing in this issue or please link the issue that details the usability testing results.

**Comment by kcoronel** [comment]
All tasks completed, closing this issue
