### ISSUE TITLE
CRM Usability Test : Participant Recruitment

### ISSUE THREAD

**Issue by kcoronel** [hackforla/CivicTechJobs#455]
### Dependency

- [x] Creation of epic #453 

### Overview
Need to gather Hack for LA product manager participants for CMS usability test. 

### Action Items
- [x] Obtain a list of all projects that are active 
- [x] Obtain a list of PM and Team Leads for projects that are active 
- [x] Create a spreadsheet to keep track of folks messaged and responses (see resources below) 
https://docs.google.com/spreadsheets/d/1C9OvEEybVZ70NyaUUYEiYM3NQOJvdv2uRgXcYMShhpU/edit#gid=0
- [x] Create a message that will be sent in project slack channel (see resources below) 

### Resources/Instructions
[Product Management Community of Practice Agenda](https://github.com/hackforla/product-management/issues/131#issuecomment-1656240943)
[Hack for LA Project List from website](https://www.hackforla.org/projects/)
[CTJ : CMS testing message for slack](https://docs.google.com/document/d/1ZgiLLsQvi4uzUe1J-lhXtR3Ti3R73oSnNNVajk5bQDg/edit?usp=sharing)

**Comment by kcoronel** [comment]
@Leah0996 please track your progress with this work in this issue - ty!

**Comment by kcoronel** [comment]
Hi @Leah0996 can you please provide updates answering the following questions prior to our meeting, ty! 
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by Leah0996** [comment]
1. Progress: Reached out to all project teams and identified some team leads and product managers willing to participate in the usability testing study. Scheduled our first study for tomorrow @ 6pm EST/ 5pm PT
2. Blockers: Some project teams have not responded, Will be following up with them. 
3. Availability: N/A
4. ETA; N/A

**Comment by kcoronel** [comment]
@Leah0996 will work with Bonnie to create the locked folder for recordings - should be done before your 6pm

**Comment by sabheasley** [comment]
Hi @Leah0996 can you please provide updates answering the following questions prior to our meeting, ty!

1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by Leah0996** [comment]
Progress: Me & Nga conducted 3 interviews. We have two more scheduled for tomorrow. Will send link to designers if they want to join. 
Blockers: No blockers at the moment
Availability: N/A
ETA: N/A

**Comment by sabheasley** [comment]
Hi @Leah0996 can you please provide updates to the following? Thanks!

Progress 
Blockers 
Availability 
ETA

**Comment by Leah0996** [comment]
All information regarding recruiting for usability testing is there @kcoronel

**Comment by kcoronel** [comment]
Thank you @Leah0996 going to close this issue because all tasks have been completed.
