### ISSUE TITLE
Fix mkdocs deployment

### ISSUE THREAD

**Issue by MattPereira** [hackforla/CivicTechJobs#456]
### Overview
Our mkdocs deployment failing is preventing PMs from updating information at https://hackforla.github.io/CivicTechJobs/joining-the-team/intro/

### Action Items
- [ ] Fix the error that is causing the mkdocs deployment to fail

### Resources/Instructions
- [PM comment](https://github.com/hackforla/CivicTechJobs/issues/450#issuecomment-1738362366) 
- [Deployment Error Logs](https://github.com/hackforla/CivicTechJobs/actions/runs/6790904175/job/18461345713)
- [MK Doc folder](https://github.com/hackforla/CivicTechJobs/tree/main/mkdocs)
[staging site](https://stage.civictechjobs.org/login)login form and sign in form
[starter mkdocs docker image](https://hub.docker.com/r/hackforlaops/mkdocs/tags) at hackforla along with [repo](https://github.com/hackforla/docker-mkdocs) and [documentation](https://hackforla.github.io/docker-mkdocs)
- The image contains a minimal set of mkdocs plugins and teams can ask for/PR-add ones they think are useful for everybody. There's also documentation on [how to extend the image to add your own plugins](https://hackforla.github.io/docker-mkdocs/user-guide/#extend-the-image) locally.
- The Tools section in the [docs](https://hackforla.github.io/docker-mkdocs/) is kind of interesting. It's tools used (or found) while working on the document and the things learned about them that might be useful for other people. The - - [Docker page](https://hackforla.github.io/docker-mkdocs/docker/) could be useful for someone wanting to [reduce the size of their docker image](https://hackforla.github.io/docker-mkdocs/docker/#reducing-the-image-size).
- Advanced example of MK Docs: https://hackforla.github.io/website-wiki/ and https://hackforla.github.io/website-wiki/ which [builds its own local mkdocs image](https://github.com/hackforla/website-wiki/blob/f5357d0ecdd2569d7afaf2354956c751c7e56bfa/Dockerfile#L4) and makes use of [more plugins](https://github.com/hackforla/website-wiki/blob/f5357d0ecdd2569d7afaf2354956c751c7e56bfa/mkdocs.yml#L60-L70)

**Comment by MattPereira** [comment]
<img src="https://media0.giphy.com/media/1000WjcUQeqOaY/giphy.gif"/>

**Comment by kcoronel** [comment]
working on the issue here: https://github.com/hackforla/CivicTechJobs/issues/490

**Comment by kcoronel** [comment]
@LoTerence I realized that I was adding too many action items to this issue #490 and needed to split it up. Are you okay with fixing the deployment so that myself and the PM team make updates our MK Docs. 

Thanks!

**Comment by LoTerence** [comment]
The deployment works from the `develop` branch. The code just needs to be cleaned up and merged into main. I will make a new issue with specific tasks.
