### ISSUE TITLE
Fix deployment workflow for staging site

### ISSUE THREAD

**Issue by MattPereira** [hackforla/CivicTechJobs#457]
### Overview
We want to fix our `Deploy to Amazon ECS stage environment` workflow. Currently it is failing on the `Build, tag, and push image to Amazon ECR` with the following error:

<details><summary>See screenshots of action logs</summary>

![image](https://github.com/hackforla/CivicTechJobs/assets/73561520/8311cd46-13f8-48f9-8d95-a0bc9666e9d2)

![image](https://github.com/hackforla/CivicTechJobs/assets/73561520/879e94aa-d4e2-4abb-ae91-ecb7c890248d)

</details>

### Action Items
- [ ] Figure out how to fix deployment of site to staging environment

### Resources/Instructions
- [Failing workflow logs](https://github.com/hackforla/CivicTechJobs/actions/runs/6567395247/job/17840005925#step:5:308)
- [Last successful deployment of changes](https://github.com/hackforla/CivicTechJobs/actions/runs/6124549188/job/16624779961)
    - ECS task definition fails but deployment still successful
- https://github.com/hackforla/CivicTechJobs/blob/main/.github/workflows/build-deploy-stage.yml

**Comment by blulady** [comment]
Error: pg_config executable not found.
#20 13.68   
#20 13.68   pg_config is required to build psycopg2 from source.  Please add the directory
#20 13.68   containing pg_config to the $PATH or specify the full executable path with the
#20 13.68   option:
#20 13.68   
#20 13.68       python setup.py build_ext --pg-config /path/to/pg_config build ...
#20 13.68   
#20 13.68   or with the pg_config option in 'setup.cfg'.
#20 13.68   
#20 13.68   If you prefer to avoid building psycopg2 from source, please install the PyPI
#20 13.68   'psycopg2-binary' package instead.
#20 13.68   
#20 13.68   For further information please check the 'doc/src/install.rst' file (also at
#20 13.68   <https://www.psycopg.org/docs/install.html>).

**Comment by alexlaw528** [comment]
@MattPereira @bzzz-coding 

This could be a potential intermittent issue caused by the latest version of poetry - described [here](https://github.com/python-poetry/poetry/issues/7611)

I created PR #458 to attempt to fix though I'm not sure if there's a better way to test the patch without merging my changes to main.
