### ISSUE TITLE
Landing Page Down 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/CivicTechJobs#468]
### Overview
REPLACE THIS TEXT -Text here that clearly states the purpose of this issue in 2 sentences or less.

### Action Items
REPLACE THIS TEXT -If this is the beginning of the task this is most likely something to be researched and documented.

REPLACE THIS TEXT -If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

### Resources/Instructions

- Mail Chimp landing page https://mailchi.mp/6e199f5c087f/civic-tech-jobs
- Repository where civictechjob.org points to: https://github.com/hackforla/CivicTechJobs-comingsoon
  - [index.html file](https://github.com/hackforla/CivicTechJobs-comingsoon/blob/main/index.html) that uses iframe to load the mailchimp landing page

**Comment by ExperimentsInHonesty** [comment]
![image](https://github.com/hackforla/CivicTechJobs/assets/37763229/9dae2b57-f800-4215-9bdd-9942ec3913d6)

**Comment by ExperimentsInHonesty** [comment]
Error message is 
![image](https://github.com/hackforla/CivicTechJobs/assets/37763229/4c339fd3-b85e-4231-b08d-ebc27fe1310f)

**Comment by ExperimentsInHonesty** [comment]
We need to log into mailchimp via the civictechjobs@hackforla.org email address and see why

**Comment by ExperimentsInHonesty** [comment]
Code for iframe
`<iframe src="https://mailchi.mp/6e199f5c087f/civic-tech-jobs"  style="border: none;margin: 0 px; position: absolute; top: 0; left: 0; bottom: 0; right: 0; width: 100vw; height: 100vh;" allowfullscreen ></iframe> `

**Comment by ExperimentsInHonesty** [comment]
If they are disallowing iframes, we can do a redirect.

**Comment by sabheasley** [comment]
This has been resolved by Mailchimp without contact -- the landing page appear shortly after our meeting.
