### ISSUE TITLE
Cookies Banner and Privacy Policy Page

### ISSUE THREAD

**Issue by bennyv8** [hackforla/CivicTechJobs#469]
### Overview

As a developers, We want to implement a Cookies Banner and Privacy Policy Page for compliance with data protection regulations and user transparency. For this issue we will create a cookies banner that will appear at the bottom of the website's pages. The banner should not obscure content and be dismissible by users. Additionally we will create a comprehensive Privacy Policy page that details our data handling practices, including data collection, storage, processing, and protection.

### Action Items

In accordance with the designs in Figma

- [x] Create Cookies Banner Component
- [x] Implement functionality for user consent regarding cookies
- [x] Create Privacy Policy Page 

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by sabheasley** [comment]
Hi @bennyv8! Can you please give provide an update for this issue by answering the following:

Progress:
Blockers 
Availability:
ETA:

**Comment by bennyv8** [comment]
> Hi @bennyv8! Can you please give provide an update for this issue by answering the following:
> 
> Progress: Blockers  Availability: ETA:

Hi @sabheasley

Progress:
I've completed and implemented the functionality of the cookie banner. Currently I am working on the privacy policy page.

Blockers: 
I have a pending pr for cookies banner and need to do some research on best practices for adding assets. Will collaborate with dev team this Wednesday

Availability:
Not too sure what's meant by this. but if it means my schedule I'm usually available 10 - 5PM PST

ETA:
I plan on having a PR for the Privacy Policy page by next week Wednesday (11/15)
