### ISSUE TITLE
Add background image to login page

### ISSUE THREAD

**Issue by bzzz-coding** [hackforla/CivicTechJobs#472]
### Overview
Add background illustrations and patterns to the left side of login/signup page.

### Resources/Instructions
REPLACE THIS TEXT -If there is a site which has documentation that helps with this issue provide the link(s) here.

**Comment by MattPereira** [comment]
sorry this was poor communication on my part. i created this issue a while ago i should have linked it to you during last meeting

- https://github.com/hackforla/CivicTechJobs/issues/444
