### ISSUE TITLE
Impliment background styles on mobile for authentication page

### ISSUE THREAD

**Issue by MattPereira** [hackforla/CivicTechJobs#474]
### Overview
We want to make the mobile view of our authentication page look just like the figma designs provided by our wonderful design team.

### Action Items
- [ ] Update the authentication page mobile view to match

### Resources/Instructions
- [Figma Designs](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?type=design&node-id=1-26&mode=design&t=XVkCIgEA9RFOOYjI-0)

![image](https://github.com/hackforla/CivicTechJobs/assets/73561520/e2ab75d2-39a6-45a1-b98c-878df851f2ac)

**Comment by nooriaali9** [comment]
Based off of #442 this issue looks dev complete - closing it out.
