### ISSUE TITLE
CTJ Onboarding Questions and Comments [Jimmy - Dev Lead]

### ISSUE THREAD

**Issue by kcoronel** [hackforla/CivicTechJobs#491]
### Overview
This issue has been created for @JimmyJuarez10  our new Dev lead to give us comments and suggestions related to our current project onboarding project. 

### Action Items
- [x] While reviewing the documents listed below, please document open questions and suggestions as comments in this issue 
     - Review [Read Me Page](https://github.com/hackforla/CivicTechJobs)
     - Review [Wiki Page](https://github.com/hackforla/CivicTechJobs/wiki)
     - Review [Mk Docs Project Documentation](https://hackforla.github.io/CivicTechJobs/)
     - Review [Kanban Board Docs and Onboarding column (https://github.com/hackforla/CivicTechJobs/projects/1)

### Resources 
[Dev Kanban board](https://github.com/orgs/hackforla/projects/37)

**Comment by kcoronel** [comment]
@JimmyJuarez10 I sent over an invite to 1Password to your email address. Please complete steps and I will confirm and add you to our project vault. Please note that you have received calendar invites for 

1. Weekly Dev meetings happening every Wednesday (January 31 at 5pm pacific). 
2. CTJ Leads meeting happening every first Tuesday of the month (February 6 at 5pm pacific). This meeting is between project team leads where we review roadmap progress and update one another on task delegation within our teams. 
2. CTJ All meeting happening every month on the third Tuesday (February 20 at 5pm pacific). This meeting is with all team members.

**Comment by JimmyJuarez10** [comment]
I was hoping that I could get some direction on what the most pressing issues are for the team so we can tackle those first?

Benny and Bitian have informed we haven't built/architected the backend or the database so thats kinda where I am kinda focusing my attention first. Is that okay ?

**Comment by kcoronel** [comment]
@JimmyJuarez10 that sounds great! Thank you!

**Comment by kcoronel** [comment]
Closing this issue as all tasks have been completed.
