### ISSUE TITLE
Offboarding Jen Chung UX Design Team Lead

### ISSUE THREAD

**Issue by kcoronel** [hackforla/CivicTechJobs#493]
### Overview
Created this issue to help us track the task delegations for Jen Chung's offboarding from the project Civic Tech Jobs. 

### Action Items

For Jen: 
- [x] In a comment below, please share a job description for the UX Design lead role(reference: [UX Design Community of Practice job board](https://github.com/hackforla/UI-UX/projects/3)) 
- [x] In a comment below, please let us know which team members will remain active on the project
- [ ] Under resources, please share the link to your offboarding document 
- [ ] Confirm your offboarding document is saved in the Civic Tech Jobs project drive 
- [ ] Under resources below please reference how people should navigate the Figma i.e. reference designs under MVP Designs

For PM's: 
- [x] Reach out to Design active members 
- [x] Post UX Design lead role in [UX Design Community of Practice job board](https://github.com/hackforla/UI-UX/projects/3)
- [x] Interview UX Design leads - ask if Jen wants to be a part of this
- [ ] When Jen completes the above and is ready to be completely off-boarded use issue #375

**Comment by jenchuu** [comment]
**Project Name**: Civic Tech Jobs

**About the Project:**

Civic Tech Jobs’ goal is to streamline the online process of 1) helping prospective volunteers find open Hack for LA projects that better match their current skills and career aspirations and 2) team leads manage/post/edit open roles. Our goal is to launch MVP this year and test and iterate future versions.

**Volunteer Opportunity**:

We are looking for a UX Design Lead who:

- has strong communication and collaboration skills (will work closely with UX Researcher, Devs, and Product Managers)
- understands user and stakeholder needs
- can lead design/brainstorming discussions and critiques
- has a passion for civic tech and community-driven projects is a plus!

We are also looking for 2 UI/UX Designers to help us develop the MVP. Having industry experience with building digital products is a HUGE plus (but not necessary).

**Duration**:

Open ended, 6 hours/week

Team Meetings: Tuesdays, 5PM PST

**Who to communicate your interest to:**

- Slack channel link: #CivicTechJobs
- Contact Karen

**Comment by jenchuu** [comment]
-Lu

Gabe is also leaving

Tin has been on pause due to work; he mentioned possibly coming back (I told him to reach out to Karen or the general civictechjobs channel if/when he decides to come back)

**Comment by kcoronel** [comment]
Offboarding template: https://docs.google.com/document/d/1ZWKRt6SD3sAI9lQnJl1QDEBKS_834m0_JZi4fDHwtzA/edit?usp=sharing

**Comment by kcoronel** [comment]
hi @jenchuu checking in on the status of this, please let me know if I can be helpful. Thank you again!

**Comment by kcoronel** [comment]
Closing this issue because I have not heard from Jen in two months, and currently there has been no issues in the transition of Lu as Design lead.
