### ISSUE TITLE
Reach out to candidates for future CTJ opportunities

### ISSUE THREAD

**Issue by kcoronel** [hackforla/CivicTechJobs#494]
### Overview
This issue is designed to assist us in tracking volunteers who express interest in joining the Civic Tech Jobs outside of active recruitment efforts (creating an open role card in a [Community of Practice project board](https://github.com/hackforla/communities-of-practice). 

### Action Items
- [ ] In a comment, please write the role the inquirer is messaging about 
- [ ] Paste the message you received from the interested party 
- [ ] Include Slack Name and link to their Slack profile. 

### Resources/Instructions
Example: 
### Role: Product 
Yenlik: Hi Karen! I hope this message finds you well. My name is Yenlik, and I am keenly interested in your project "Civic Tech Jobs." I would love to contribute to the initiative, particularly in the role of a Product/Project Manager. Could you please provide more information on how I can get involved?

Karen: Hi [@Yenlik](https://hackforla.slack.com/team/U03P33XN2S2) at this time we do not have an opening for PM on civic tech jobs, but that may an opening in the near future. Would you want me to reach out?

Yenlik: Thank you, that will be great! Just in case my email is [example@gmail.com](mailto:example@gmail.com)

Karen: Awesome - thank you!

Yenlik Slack profile: https://hackforla.slack.com/team/U03P33XN2S2

**Comment by kchotani** [comment]
Hey @kcoronel, just a friendly reminder to complete the labels before adding the issue to the project board.

**Comment by kcoronel** [comment]
From Slack: 

Hi Karen! I hope this message finds you well. My name is Yenlik, and I am keenly interested in your project "Civic Tech Jobs." I would love to contribute to the initiative, particularly in the role of a Product/Project Manager. Could you please provide more information on how I can get involved?

Hi [@Yenlik](https://hackforla.slack.com/team/U03P33XN2S2) at this time we do not have an opening for PM on civic tech jobs, but that may an opening in the near future. Would you want me to reach out?

Thank you, that will be great! Just in case my email is [yn2191@gmail.com](mailto:yn2191@gmail.com)

Awesome - thank you!

**Comment by kcoronel** [comment]
### Role: UXR Research 

Hi Karen, I hope you are doing well. I am  interested in the volunteer UX Researcher position for civic tech jobs project. I am a mixed method researcher with 8 years of academic experience and i am currently enrolled in UX/UI bootcamp where I have conducted various usability testing and finished the projects from start to finish following all steps of research and design process. I am interested in learning more about the project and use my skills to cater the needs of Hacks for LA volunteers. Please let me know if you are available for a quick chat sometime in near future.
Thanks,
Manju

Manju slack profile: https://hackforla.slack.com/team/U06E9T37H9A

**Comment by kcoronel** [comment]
Closing this issue as it duplicates efforts done for at large Hack for LA recruiting.
