### ISSUE TITLE
Improvements to Webpack Config

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#50]
### Dependency

- [x] #25 

### Overview

As a developer, we need to create an environment that will ease development as well as provide users a seamless experience when using our website. For this issue we will configure webpack with several improvements that will improve the overall quality of our project.

### Action Items

- [ ] Change webpack config to have the follow improvements. If they already exist, be sure to check them off
  - [x] Production environment
  - [x] Sass loaders
  - [x] Babel loaders
  - [x] HtmlWebpackPlugin
  - [x] Minifying
  - [ ] Tree Shaking
  - [x] SVG and other image extensions management
- [ ] Release #190 

### Resources/Instructions

[Webpack Concepts](https://webpack.js.org/concepts/)
[Webpack Configuration](https://webpack.js.org/configuration/)
[Webpack Guides](https://webpack.js.org/guides/)
[Webpack Loaders](https://webpack.js.org/loaders/)

**Comment by Aveline-art** [comment]
I am taking this issue as this must be done concurrently with my work on #78

**Comment by Aveline-art** [comment]
@gjagnoor Is this inprogress? Why is it in links/questions/review?

**Comment by gjagnoor** [comment]
@Aveline-art Not really, just making final edits you suggested as part of the code review last night. It's there to inform the team that this issue is now under review. Did I misunderstand the purpose of this bin?

**Comment by Aveline-art** [comment]
@gjagnoor Yes. We don't really use it right now, but historically, it is only used if you need product/stakeholder opinion on your ticket, and only if you could not get that feedback over slack.

**Comment by Aveline-art** [comment]
Closed because ticket is completed
