### ISSUE TITLE
CTJ Onboarding Questions and Comments [Armon Brown UI/UX Designer]

### ISSUE THREAD

**Issue by kchotani** [hackforla/CivicTechJobs#505]
### Overview

Overview
This issue has been created for our new UI/UX designer to give us comments and suggestions related to our current project onboarding project.

### Action Items

While reviewing the documents listed below, please document open questions and suggestions as comments in this issue

- [x] Review [Read Me Page](https://github.com/hackforla/CivicTechJobs)

- [x] Review [Wiki Page](https://github.com/hackforla/CivicTechJobs/wiki)

- [x] Review [Mk Docs Project Documentation](https://hackforla.github.io/CivicTechJobs/)

- [x] Review [Kanban Board Docs and Onboarding column (https://github.com/hackforla/CivicTechJobs/projects/1)

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by kcoronel** [comment]
Hi @stanarmon I've set you up with our project tools and have assigned you to complete the Action Steps above. Feel free to ask any questions in these issues.

**Comment by kcoronel** [comment]
Hey @stanarmon have you completed the tasks assigned above? If so, can you please let me know so I can close this issue.

**Comment by stanarmon** [comment]
@kcoronel Hi. I haven't completed it. I didn't even know I had something assigned. I am new to github so I was unaware of it. I will get on it now. Sorry for the delay on it.

**Comment by kcoronel** [comment]
Armon was offboarded off the project, but he was able to complete the tasks above.
