### ISSUE TITLE
CTJ Onboarding Questions and Comments [Manju - UI/UX Researcher]

### ISSUE THREAD

**Issue by kcoronel** [hackforla/CivicTechJobs#516]
### Overview
This issue has been created for our new UI/UX Research Lead to give us comments and suggestions related to our current project onboarding project. 

### Action Items
- [x] While reviewing the documents listed below, please document open questions and suggestions as comments in this issue 
     - Review [Read Me Page](https://github.com/hackforla/CivicTechJobs)
     - Review [Wiki Page](https://github.com/hackforla/CivicTechJobs/wiki)
     - Review [Mk Docs Project Documentation](https://hackforla.github.io/CivicTechJobs/)
     - Review [Kanban Board Docs and Onboarding column (https://github.com/hackforla/CivicTechJobs/projects/1)

### Resources 
#510 -- this is where you can find the issue that contains the [offboarding document](https://docs.google.com/document/d/119VDSGnRPYMpf7T6WhJj9rbws5e-s5A4RNIM3gl3mMU/edit) that JWu our previous UXR Team Lead left 

Leah is currently working on this: https://github.com/hackforla/CivicTechJobs/issues/511

**Comment by kcoronel** [comment]
@snigbehara  I've set you up with our project tools and have assigned you to complete the Action Steps above. Feel free to ask any questions in this issue as a comment. Please note that you have received calendar invites for; 

CTJ Leads meeting happening every first Tuesday of the month (April 2 at 5pm pacific). This meeting is between project team leads where we review roadmap progress and update one another on task delegation within our teams.
CTJ All meeting happening every month on the third Tuesday (March 19 at 5pm pacific). This meeting is with all team members.

I will connect you with Leah on Slack so you can agree on a weekly meeting between you and her.

**Comment by kcoronel** [comment]
Repurposed this issue from Snigdha to Manju.

**Comment by kcoronel** [comment]
Hi @itsmanjuchawla I've set you up with our project tools and have assigned you to complete the Action Steps above. Feel free to ask any questions in these issues.

**Comment by itsmanjuchawla** [comment]
To enhance the research plan, it might be beneficial to establish clear goals and objectives that the team is trying to achieve with the civictechjobs.org website

**Comment by itsmanjuchawla** [comment]
I have reviewed the documents shared above and have started working on the research plan as discussed.
