### ISSUE TITLE
Qualifier - Skill Matrix Page Design

### ISSUE THREAD

**Issue by CarmenMM1** [hackforla/CivicTechJobs#519]
### Overview
Redesign on the Qualifier - Skill Matrix Page

### Action Items

1. Redesign User Flow (including Returning Users)
2. Redesign Qualifier Page
- [x] Finalise on the design of Slider or Scale
- [x] Sucess and Error Message
- [x] Different state of the card

### Resources/Instructions

**Comment by CarmenMM1** [comment]
### V1 - With Original Design (Slider) But I added a white blur on top
![Original Design - Slider - Blurry on top](https://github.com/hackforla/CivicTechJobs/assets/148927139/f6f5ee34-20db-4b30-a41f-f378bef66ad6)
_Issues:_
1.1 Sliders are not user-friendly, hard to drag

### V2 
![No # of roles](https://github.com/hackforla/CivicTechJobs/assets/148927139/ee629098-bca7-4b2c-ae19-1302c257c650)
Note: I was planning to design a Likert scale used by 16 personalities, https://www.16personalities.com/free-personality-test, but after studying the differences between **Likert Scale** and **Semantic Differential Scale**. 
Likert Scale: a 5-point or 7-point scale with a neutral option in the middle
**Semantic Differential Scale: a scale between two bipolar adjectives** 

### V3 - Latest and we pick this
Semantic Differential Scale is the one that we would like to use, updated version:
![UIUX](https://github.com/hackforla/CivicTechJobs/assets/148927139/f110df27-fd8e-4f82-8a03-540f75533f4c)

**Comment by kcoronel** [comment]
great work @CarmenMM1, closing this issue since all tasks have been completed.
