### ISSUE TITLE
Search Page Design

### ISSUE THREAD

**Issue by sharadgaurav7** [hackforla/CivicTechJobs#52]
### Overview

As a potential volunteer I should be able to search for open volunteer positions at hackforla so that I can find the right match for my interest and aspirations. 

### Action Items

- [x] Create self-filter (qualifier page)
- [x] Create UX/UI design for the search page
- [x] Search page to have other filters for Project, Program Area, and technologies
- [ ] Usability testing to validate ease of use, understanding of the terms mentioned on the page

### Resources/Instructions

Refer to the Requirements Document: https://docs.google.com/spreadsheets/d/1VcDLJnDA5CE7euzaZxOcqS3LLgyUFVLeqvdZx2sFGQk/edit#gid=804221697

**Comment by sdimran** [comment]
for the project cards once qualifiers have been selected, we can include the relevant information included in this link : 
https://github.com/hackforla/engineering/projects/2

if a user is not logged in : they will not be able to see what projects the posting is for but can see all other relevant information
if a user is logged in : they will be able to see project name and all relevant information as well as the call to action if interested in the role (slack link to join and connect with PM)

**Comment by sharadgaurav7** [comment]
@jenchuu , will you please check off all the completed action items on the issue, and assign @stephaniestahlberg for the usability search part

**Comment by jenchuu** [comment]
This was not the issue we were using to log the search page design. Please see https://github.com/hackforla/CivicTechJobs/issues/24
