### ISSUE TITLE
Qualifier Page (Skill Metrics and Calendar mobile Versions)

### ISSUE THREAD

**Issue by brendasdesign** [hackforla/CivicTechJobs#520]
### Overview

As a designer, it is necessary to create an ease of use for users to complete the skill evaluation and for the calendar, the goal is to make it more intuitive and easy for users to update the calendar

### Action Items

- [x] Research and Explore ideas for the skill metric
- [x] Paper wireframe
- [x] Create wireframe
- [x] Review with team
- [x] Finalize with the team during hands-on practice
- [x] Research different Calendar design 
- [ ] Create a wireframe
- [ ] Ideate with team member
- [ ] Make corrections 
- [ ] Finalize with team

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by brendasdesign** [comment]
03/24 : Team hands-on meeting: Ideate and edit the below pages under the qualifier page.
![Screenshot 2024-03-24 at 6 34 42 PM](https://github.com/hackforla/CivicTechJobs/assets/154822442/c0b5ebcc-7949-429a-8a7e-249f353546fb)
![Screenshot 2024-03-24 at 6 34 18 PM](https://github.com/hackforla/CivicTechJobs/assets/154822442/f242ba20-1e44-4054-9607-f47b6a60751e)
![Screenshot 2024-03-24 at 6 33 45 PM](https://github.com/hackforla/CivicTechJobs/assets/154822442/00f69386-5a7a-4ec3-9173-d5384c195e5f)

**Comment by kcoronel** [comment]
Great work @brendasdesign! Please provide update
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by kcoronel** [comment]
@brendasdesign hi! missed you at our All Team meeting, please update this issue with what you have accomplished.

**Comment by kcoronel** [comment]
@fenglugithub would it be okay to close this issue?

**Comment by fenglugithub** [comment]
@kcoronel Yes. It's ok to close it. Thanks!

**Comment by nooriaali9** [comment]
Closing this based on above comment ^
