### ISSUE TITLE
Landing page updates

### ISSUE THREAD

**Issue by fenglugithub** [hackforla/CivicTechJobs#522]
### Overview

As a member of the design team, we need to ensure that we are crediting Hack for LA in the landing page. We made updates to meet the requirement. 

### Action Items

- [x] Add credit for Hack for LA in the landing page.
- [x] Team review
- [x] Handoff to devs

### Resources/Instructions

[Landing Page](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?type=design&node-id=1%3A7&mode=design&t=ozxl12FJfLjxno3I-1)

**Comment by fenglugithub** [comment]
Added credit for Hack for LA in the Landing page.

<img width="935" alt="Screenshot 2024-03-27 at 4 21 54 PM" src="https://github.com/hackforla/CivicTechJobs/assets/43657452/c4ae0de6-5c2f-48a7-a97e-5eb0effd1eb5">

**Comment by kcoronel** [comment]
@fenglugithub please update - thank you!

**Comment by kcoronel** [comment]
Lu will initiate handoff to Dev team and will record that action here.
