### ISSUE TITLE
Create foundational structure for CTJ Backend

### ISSUE THREAD

**Issue by JimmyJuarez10** [hackforla/CivicTechJobs#523]
As an engineer I would like to create:
- [x] An endpoint ( /healthcheck ) to check backend health using Django.
- [x] Client should be able to GET /healthcheck
- [x] Backend should respond with 200 and the following JSON:
  - { uptime: 3123123, version: , hostname: }

**Comment by JimmyJuarez10** [comment]
As an engineer I would like to create:
- An endpoint ( /healthcheck ) to check backend health using Django.
- Client should be able to GET /healthcheck
- Backend should respond with 200 and the following JSON:
  - { uptime: 3123123, version: , hostname: }

**Comment by kcoronel** [comment]
@bzzz-coding please provide update
1. Progress 
2. Blockers 
3. Availability 
4. ETA

**Comment by LoTerence** [comment]
Merged into develop on 09/25
