### ISSUE TITLE
Create database schema for Post Database.

### ISSUE THREAD

**Issue by JimmyJuarez10** [hackforla/CivicTechJobs#524]
### Overview

As a developer, we would like to create a database schema in Postgres DB based off of the following screenshot for the Post DB.

![Image](https://github.com/hackforla/CivicTechJobs/assets/41131371/dbf607ee-a525-486d-a89f-8fb611fa4d55)

 

### Action Items

- [ ] Create SQL that creates the Post Table locally or in docker.

### Resources/Instructions

[Resources](https://hackforla.github.io/CivicTechJobs/resources/)

**Comment by kcoronel** [comment]
@bennyv8 please provide updates 
1. Progress 
2. Blockers 
3. Availability 
4. ETA
