### ISSUE TITLE
CTJ Onboarding Questions and Comments [Xiaotian Vivian Li- UI/UX Research Lead]

### ISSUE THREAD

**Issue by kcoronel** [hackforla/CivicTechJobs#526]
### Overview
This issue has been created for our new UI/UX Research Lead to give us comments and suggestions related to our current project onboarding project.

### Action Items
- [x] While reviewing the documents listed below, please document open questions and suggestions as comments in this issue 
     - Review [Read Me Page](https://github.com/hackforla/CivicTechJobs)
     - Review [Wiki Page](https://github.com/hackforla/CivicTechJobs/wiki)
     - Review [Mk Docs Project Documentation](https://hackforla.github.io/CivicTechJobs/)
     - Review [Kanban Board Docs and Onboarding column (https://github.com/hackforla/CivicTechJobs/projects/1)

### Resources 
#510 -- this is where you can find the issue that contains the [offboarding document](https://docs.google.com/document/d/119VDSGnRPYMpf7T6WhJj9rbws5e-s5A4RNIM3gl3mMU/edit) that JWu our previous UXR Team Lead left

**Comment by kcoronel** [comment]
Hi @xxl228  I've set you up with our project tools and have assigned you to complete the Action Steps above. Feel free to ask any questions in these issues.

Weekly UXR meetings happening every Friday (April 12 at 3pm pacific).
CTJ Leads meeting happening every first Tuesday of the month (May 7 at 5pm pacific). This meeting is between project team leads where we review roadmap progress and update one another on task delegation within our teams.
CTJ All meeting happening every month on the third Tuesday (April 21 at 5pm pacific). This meeting is with all team members.

**Comment by xxl228** [comment]
Hi @kcoronel I have read the relevant pages, no pressing issues or questions so far. But I will ask these questions as they come up.
