### ISSUE TITLE
Create Seed file for Local Development on Post Database

### ISSUE THREAD

**Issue by JimmyJuarez10** [hackforla/CivicTechJobs#530]
As a developer I would like to:

- Connect to PGDB
- Initialize the model for Opportunities
- Create a seed file for the Opportunities Database that creates 10 volunteer postings.

**Comment by bennyv8** [comment]
1. Completed
2. Resolving merge conflict for PR
3. --
4. End of week

**Comment by nooriaali9** [comment]
@bennyv8 Would you be able to add a feature here?

**Comment by kcoronel** [comment]
Marked as complete from conversation with @bennyv8 and @JimmyJuarez10
