### ISSUE TITLE
Prep Project Boards for Migration

### ISSUE THREAD

**Issue by kchotani** [hackforla/CivicTechJobs#537]
### Overview
We need to prepare the Project Boards for the forced migration that GitHub is doing in August, so that it is already working well for the team by then.

### Action Items
All cards on the main project board are backed up and moved to appropriate places

- [ ] copy this template to a comment below

````
### Text from project board card
```
[INSERT MARKDOWN HERE]
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

````

- [ ] copy markdown from each card on the board into your new comment where it says `[INSERT MARKDOWN HERE].  One card per comment
- [ ] delete card from project board. 

**All issues are on the project board**

- [ ] check to see if all issues are on the project board (resource 1.02) 
- [ ] if not, add them to the board, and put them in the correct columns 

### Resources/Instructions
1.01 main Project board: https://github.com/hackforla/CivicTechJobs/projects/1?card_filter_query=-is%3Aissue+-is%3Apr
1.02 [issues not on the project board]

**Comment by kcoronel** [comment]
### Text from project board card

[INSERT MARKDOWN HERE]
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from project board card
```
Drives etc.
- [Civic Tech Jobs Google Shared Drive](https://drive.google.com/drive/folders/1hXxvpC8W5Uuzjqo4CxnjDpAMI7sbVnq8?usp=sharing)
- [Hack for LA's Figma about Civic Tech Jobs](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=5326%3A26395)
- [Civic Tech Jobs Figma](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Project-Area?node-id=0%3A1
)
```

- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from project board card, Start Here column
```
GitHub Project Board - [Best Practices](https://docs.google.com/presentation/d/1plLNwC9VAOmlP0Y0LzVps2ZzJUnnRxQ0_w3yI-BCfKs/edit#slide=id.p)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from project board card
```
Tech Stack and Costs:
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by ExperimentsInHonesty** [comment]
### Text from project board card
```
Additional Resources
- [HfLA Logo Design Guidance - WIP](https://github.com/hackforla/UI-UX/issues/20)
- [HfLA Role Descriptions](https://github.com/hackforla/civic-opportunity/tree/master/roles-1)
```
- [ ] Determine where this item goes on the wiki (page and section)
- [ ] copy item to wiki
- [ ] hide this comment when completed.

**Comment by kcoronel** [comment]
Closing this issue as we have migrated the project board.
