### ISSUE TITLE
CTJ Onboarding Questions and Comments [Nooria Ali - Project Manager]

### ISSUE THREAD

**Issue by kcoronel** [hackforla/CivicTechJobs#544]
### Overview
This issue has been created for our new Project Manager to give us comments and suggestions related to our current project onboarding.

### Action Items
- [ ] While reviewing the documents listed below, please document open questions and suggestions as comments in this issue 
     - Review [Read Me Page](https://github.com/hackforla/CivicTechJobs)
     - Review [Wiki Page](https://github.com/hackforla/CivicTechJobs/wiki)
     - Review [Mk Docs Project Documentation](https://hackforla.github.io/CivicTechJobs/)
     - Review [Kanban Board Docs and Onboarding column (https://github.com/hackforla/CivicTechJobs/projects/1)

### Resources 

UXR - #510 -- this is where you can find the issue that contains the [offboarding document](https://docs.google.com/document/d/119VDSGnRPYMpf7T6WhJj9rbws5e-s5A4RNIM3gl3mMU/edit) that JWu our previous UXR Team Lead left

**Comment by nooriaali9** [comment]
1. Is there an actual live landing page yet? if yes, where can I find it?
2. I saw the 6 month roadmap via one sheet - how much of that is achieved yet?

- Create the system design for MVP
- Create Backend architecture
- Develop the service map of the job posting process and the user experience
- Design the search page (including the self-filter page), and the CMS
- User testing for MVP
 - Complete the MVP and launch
 
 3. Also the wiki page is outdated, needs to be updated to this - https://hackforla.github.io/CivicTechJobs/
 4. Most of the links on the documentation are outdated, I could look into updating it - once I get the correct links
 
 Also, I want to look through the board properly, which I will do over the weekend & get back with more questions

**Comment by nooriaali9** [comment]
https://docs.google.com/document/d/1mLz-uIsZcivXnpsgmQMe6V27bAzYQFAjjXDtIO46hpc/edit?usp=sharing - added this doc to CTJ google drive to track & discuss all issues that need to be closed out / are out dated

**Comment by kcoronel** [comment]
@nooriaali9 thank you for your questions
1. https://civictechjobs.org/ - coming soon page, will get back to you with staging site
2.

**Comment by nooriaali9** [comment]
@kcoronel I meant the outdated links in the MKDocs - https://hackforla.github.io/CivicTechJobs/ 

![Image](https://github.com/user-attachments/assets/fba7ec51-4e20-4b10-8076-c56fdce5e05b)

The above image has all outdated links ^^

1.  In Content Writer ->
- Review the _**[Project Board](https://github.com/hackforla/CivicTechJobs/projects/1)**_ and identify an actionable backlog item.
2. In Data Scientist ->
- Review the _**[Project Board](https://github.com/hackforla/CivicTechJobs/projects/1)**_ and identify an actionable backlog item. We are working to resolve some database architecture issues and are not onboarding new data scientist at this time.
3. In Product Manager and Owner ->
- Learn how we setup our [GitHub Kanban boards](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit?usp=sharing) and please comment if there is anything in the document that is unclear.
- Review our [OKRS](https://hackforla.github.io/CivicTechJobs/joining-the-team/product-manager/INSERT-PROJECT-OKRS-SPREADSHEET-LINK).
- Review the [Project Board](https://github.com/hackforla/[INSERT-REPO-NAME]/projects/1) and the [Product Management issues available on that board](https://hackforla/[INSERT-REPO-NAME]/projects/1?card_filter_query=label%3A%22role%3A+product%2Fproject+mgmt%22) to identify an actionable backlog item.
- Review Hack for LA [Product Management Templates](https://github.com/hackforla/product-managment/projects/2).
4. In UI/UX Designer ->
- Review the UI/UX issues on the [Project Management Board](https://github.com/hackforla/CivicTechJobs/projects/1?card_filter_query=label%3A%22role%3A+ui%2Fux%22) and identify an actionable backlog item.
5. In UI/UX Researcher ->
- [Completed Research](https://hackforla.github.io/CivicTechJobs/joining-the-team/uiux-researcher/research-completed)
- [In Progress Research](https://hackforla.github.io/CivicTechJobs/joining-the-team/uiux-researcher/research-inprogress)
- [Researching being audited](https://hackforla.github.io/CivicTechJobs/joining-the-team/uiux-researcher/research-audits)
6. In Web Developer ->
Read the development [Readme](https://github.com/hackforla/[INSERT-REPO-NAME]/blob/main/README.md)
Review the project board by the type of issue you are looking for. The [Frontend Coding Project Board](https://github.com/hackforla/CivicTechJobs/projects/1?card_filter_query=label%3A%22role%3A+frontend%22) or the [Backend Coding Project Board](https://github.com/hackforla/CivicTechJobs/projects/1?card_filter_query=label%3A%22role%3A+backend%22). Or you can check out the entire [project board](https://github.com/hackforla/CivicTechJobs/projects/1) here.
Your first commit will likely be an issue labeled good first issue. Check [the board](https://github.com/hackforla/[INSERT-REPO-NAME-HERE]/projects/1?card_filter_query=label%3A%22good+first+issue%22) for those issues. Don't worry if you don't see anything now, we are working on it.
7. In Other Volunteer ->
Review the [Project Board](https://github.com/hackforla/[INSERT-REPO-HERE]/projects/1).

8. This will be updated I assume - **https://hackforla.github.io/CivicTechJobs/misc/the-team/**

Sorry for the chunky comment - This is so we have sort of a to - do list and a quick glance at the doc & are able to fix all the broken links in the https://hackforla.github.io/CivicTechJobs/

**Comment by kcoronel** [comment]
@nooriaali9 have moved your comment to #490 as we work on onboarding documentation (which MK docs is a part of) feel free to close this issue :)
