### ISSUE TITLE
Configure team permissions for repository

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#55]
### Overview
As a lead developer, it would be nice to access a greater level of repo permissions to configure it according to developer needs. For this issue, we will discuss the levels of team permissions we have, and add members to each team accordingly.

### Action Items

- [x] Review the purpose of each team for this specific project
- [x] Discuss which team members belong in which team
- [x] Add the team members to the appropriate teams

### Resources/Instructions
[civictechjobs Teams](https://github.com/orgs/hackforla/teams?query=civictechjobs)

write: @jenchuu , @graceerya , @patula006 , @stephaniestahlberg , @arghmatey , @Dendorable 
maintain: @sdimran , @sharadgaurav7 
admin: @Aveline-art

**Comment by sharadgaurav7** [comment]
@Aveline-art, Can you please create a role chart showing team level permission levels and share it with Bonnie for her approval.

**Comment by Aveline-art** [comment]
This has been done via the advanced permissions I have been given.
