### ISSUE TITLE
CTJ Onboarding Questions and Comments [Rishi Raghu - UI/UX Researcher]

### ISSUE THREAD

**Issue by kcoronel** [hackforla/CivicTechJobs#555]
### Overview
This issue has been created for our new UI/UX Researcher to give us comments and suggestions related to our current project onboarding project.

### Action Items
- [x] While reviewing the documents listed below, please document open questions and suggestions as comments in this issue 
     - Review [Read Me Page](https://github.com/hackforla/CivicTechJobs)
     - Review [Mk Docs Project Documentation](https://hackforla.github.io/CivicTechJobs/) - please note we are working on updating this 
     - Review [Wiki Onboarding [Start Here]](https://github.com/hackforla/CivicTechJobs/wiki/Onboarding-%5BStart-Here%5D)

**Comment by rishi222k** [comment]
Hey @kcoronel!  

I’ve reviewed all the documents listed above and have a few clarifying questions:

- Wanted to clarify the type of suggestions you’re looking for. Are you seeking feedback on content design/structure, general improvements to the docs, or something else?

- I noticed a few links in the Mk Docs that lead to 404 pages. I understand the docs are a work in progress, but would you like me to include these in the comments?

- I’ve lightly skimmed the project contents in the Drive and Figma file mentioned in the resources. I’ll likely take a deeper look in the coming weeks and reach out if any questions arise. Are there any specific aspects you’d like me to review in detail at this stage as part of onboarding?

**Comment by kcoronel** [comment]
@rishi222k apologies for my delay in this 🫣 responses to your questions below 

- We are seeking feedback on the content (is it clear? is there something you feel was missing?) General improvements that will make the onboarding process efficient and clear. 
- Yes, please do add the pages you found with 404 pages so that we can make sure we revise these. 
- Please take a look and let us know if there is anything that would make it easier to navigate these. 

Thank you!!

**Comment by rishi222k** [comment]
@kcoronel Thanks for the clarification and getting back! Here's my feedback:

### GitHub Readme  

**Intro Para 1** 
>The website's main features include a *linklist* to public interest job boards and other resources *relevent* to their focused journey to work on projects and solve problems with a public benefit.

- I wasn’t entirely sure what "linklist" refers to in this context. While I was able to infer its meaning from the surrounding text, I’m unsure if it’s a commonly used term in design or refers to a specific UI element.   
- Typo fix: "relevant" 

**Intro Para 2** 
>The CivicTechJobs.org MVP site will be a platform to help prospective volunteers find *inter disciplinary* projects that will be useful for their career development while contributing to positive civic impact and a CMS for Hack for LA projects to be able to list their open roles.

Typo fix: "interdisciplinary"

**Intro Para 3** 
>Future iterations of the platform will *focus helping* volunteers find volunteer opportunities that match paid job postings, so that a volunteer can better prepare themselves for the marketplace.

Typo fix: "focus on helping"

**Technology used section > Collaboration Technologies**

Point 1 : GitHub project board link inactive(404 page):
https://github.com/hackforla/CivicTechJobs/projects/1

---

### Mk Docs - Project Documentation

**Home Page > *Hasn't it been done already?***
>Read more about what lead up to us developing this project, at our *History* page.
  
Link inactive(404): https://hackforla.github.io/CivicTechJobs/History
(Though link to history page is active on Docs/Misc/History: https://hackforla.github.io/CivicTechJobs/misc/history/)

**Project Board Link**
Inactive links(404): https://github.com/hackforla/CivicTechJobs/projects/1 
*Page locations*: Nav Menu>Joining the Team (Content Writer, Data Scientist, Project Manager, UI/UX Designer, Web Developer, Other Volunteer)

**Nav Menu> Joining the Team > Project Manager**

- Point 1: Google doc link is inactive(File deleted). URL: https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit?usp=sharing
- Point 3: OKRS link is inactive(404 page). URL: https://hackforla.github.io/CivicTechJobs/joining-the-team/product-manager/INSERT-PROJECT-OKRS-SPREADSHEET-LINK
- Point 5: Product Management link is inactive(404 page). URL: [https://hackforla/[INSERT-REPO-NAME]/projects/1?card_filter_query=label%3A"role%3A+product%2Fproject+mgmt](https://hackforla/%5BINSERT-REPO-NAME%5D/projects/1?card_filter_query=label%3A%22role%3A+product%2Fproject+mgmt)"

**Nav Menu> Joining the Team > UI/UX Designer**

- Starting Checklist > Point 3: Figma link does not open anywhere(might be a permission issue on my end though). Link: https://www.figma.com/files/team/1040075117587297658/Civic-Tech-Jobs?fuid=775836858007206739

**Nav Menu> Joining the Team > UX Researcher**

- The first 3 links are inactive.

**Nav Menu> Joining the Team > Web Developer**

Starting Checklist
- Point 1: Inactive README link. URL: [https://github.com/hackforla/[INSERT-REPO-NAME]/blob/main/README.md](https://github.com/hackforla/%5BINSERT-REPO-NAME%5D/blob/main/README.md)
- Point 2 & 4: All links are inactive.

---
Don't have any outstanding suggestions or questions beyond the points I’ve mentioned in my feedback. Overall, everything felt smooth to navigate and easy to onboard.

**Comment by kcoronel** [comment]
hi @rishi222k answering your questions below:

**Comment by rishi222k** [comment]
@kcoronel Thanks for getting back and clarifying these!
