### ISSUE TITLE
CTJ Onboarding Questions and Comments [Terence Lo - Developer, Backend] 

### ISSUE THREAD

**Issue by kcoronel** [hackforla/CivicTechJobs#557]
### Overview
This issue has been created for our new Developer - Front End to give us comments and suggestions related to our current project onboarding project.

### Action Items
- [x] While reviewing the documents listed below, please document open questions and suggestions as comments in this issue 
     - Review [Read Me Page](https://github.com/hackforla/CivicTechJobs)
     - Review [Mk Docs Project Documentation](https://hackforla.github.io/CivicTechJobs/) - please note we are working on updating this 
     - Review [Wiki Onboarding [Start Here]](https://github.com/hackforla/CivicTechJobs/wiki/Onboarding-%5BStart-Here%5D)

**Comment by LoTerence** [comment]
Hi Karen,

Just got done reviewing all the provided documentation! Thank you for clear and concise information.

I think my next steps will be to dive into the backend documentation on mkdocs, and install and run the project? Does that sound okay with you?

Looking forward to meeting everyone at today's meeting!

**Comment by kcoronel** [comment]
Sounds good! Closing this issue
