### ISSUE TITLE
CTJ Onboarding Questions and Comments [Roja Pinnamraju- Developer, Frontend]

### ISSUE THREAD

**Issue by kcoronel** [hackforla/CivicTechJobs#558]
### Overview
This issue has been created for our new Developer - Front End to give us comments and suggestions related to our current project onboarding project.

### Action Items
- [x] While reviewing the documents listed below, please document open questions and suggestions as comments in this issue 
     - Review [Read Me Page](https://github.com/hackforla/CivicTechJobs)
     - Review [Mk Docs Project Documentation](https://hackforla.github.io/CivicTechJobs/) - please note we are working on updating this 
     - Review [Wiki Onboarding [Start Here]](https://github.com/hackforla/CivicTechJobs/wiki/Onboarding-%5BStart-Here%5D)

**Comment by kcoronel** [comment]
@RojaPinnamraju any updates to this issue? 

Thanks!

**Comment by RojaPinnamraju** [comment]
Hi @kcoronel , I have reviewed all the documents mentioned above. Sorry for the late response!

**Comment by kcoronel** [comment]
Thanks @RojaPinnamraju! I will close this issue now - thank you!
