### ISSUE TITLE
Some Readme links are broken

### ISSUE THREAD

**Issue by LoTerence** [hackforla/CivicTechJobs#561]
### Overview
As a new team member, I found these issues while reading the onboarding documentation:

1. the readme.md project board link is broken. Here is a working link: https://github.com/orgs/hackforla/projects/37
2. the readme.md google drive link is broken. Clicking on it sends me to a page that says I have no access. Here is a working link: https://drive.google.com/drive/u/2/folders/1hXxvpC8W5Uuzjqo4CxnjDpAMI7sbVnq8
3. History link in mkdocs homepage is broken:
  - https://hackforla.github.io/CivicTechJobs/
  - Link provided: https://hackforla.github.io/CivicTechJobs/History
  - Working link about hfla history: https://github.com/hackforla/CivicTechJobs/wiki/History#history

### Action Items
- [ ] Update the readme.md project board link to: https://github.com/orgs/hackforla/projects/37
- [ ] Update the readme.md google drive link to: https://drive.google.com/drive/u/2/folders/1hXxvpC8W5Uuzjqo4CxnjDpAMI7sbVnq8
- [ ] Fix the mkdocs "History" link

### Resources/Instructions
PUT LINK TO README.md FILE HERE
https://github.com/hackforla/CivicTechJobs/blob/main/README.md

Mkdocs homepage:
https://hackforla.github.io/CivicTechJobs/

**Comment by DeepanshuMishraa** [comment]
Working on this!

**Comment by kcoronel** [comment]
Hey @DeepanshuMishraa thank you for offering to help, I think it may be easier for someone from the Hack for LA organization to support as they may have more access with some of the more internal organizational tools. 

@LoTerence thanks for starting this issue! I've committed an update to the Read.Me to update the Kanban board link. The Google Drive link should work, can you check again? You are listed as a contributor. For folks who are not listed as members will probably get a page that states 'no access'. Would you be able to support getting our MK Doc fixed? Currently @nooriaali9 has been taking a look at updating our MK Docs, so maybe you can work together? Let me know what you think. 

A friendly reminder that issues require: 

- Projects to be selected that states CTJ Project Board. 
- Milestone should be selected 

Thank you!!

**Comment by LoTerence** [comment]
Hi @kcoronel 
I'd be happy to support getting the MK Doc fixed in any way.

I see the two PRs you made to fix the readme google drive and project board links. Thanks for doing that!

Thank you for the correction, next time I make an issue I will be sure to include tags for milestone role and size.

**Comment by LoTerence** [comment]
Closing this issue because its being captured in #490 

https://github.com/hackforla/CivicTechJobs/issues/490#issuecomment-2325256852
