### ISSUE TITLE
Conslidate Important Links onto the Wiki

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#58]
### Overview
As a developer of CivicTechJobs, it would be useful for the team to have access to important documents. For this issue, we will consolidate links onto our wiki, so that they will be accessible and public.

### Action Items

- [x] Gather useful links that can be placed in the wiki
- [ ] Put those links on the wiki

### Resources/Instructions
[Wiki Homepage](https://github.com/hackforla/CivicTechJobs/wiki)
[Docs & Onboarding column](https://github.com/hackforla/CivicTechJobs/projects/1#column-15193568)

Note that the wiki is public. Anyone can click on a link there. Please make sure that the links are either well protected, or does not contain secret or sensitive information.

**Comment by stephaniestahlberg** [comment]
[user flow diagram](https://docs.google.com/document/d/1ja1rfgEksPwH5-zaJdOas7SvZghC2NqjO7ePxsyxxFg/edit)
[research slide deck ](https://docs.google.com/presentation/d/1fJOK6-2YyMgLKfF4ZmJfR5YMUNic4hGn/edit#slide=id.p1)

**Comment by jenchuu** [comment]
[https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A6](url)

**Comment by jenchuu** [comment]
I saw Stephanie and Patty created a user flow for the qualifier page. 
I created a task and user flow to help us see the overall process we want users to follow when entering CTJ site:
[Task and user flow](https://whimsical.com/ctj-task-and-user-flow-8GgB5Moy14fnQDv24o1fGC)

**Comment by sharadgaurav7** [comment]
@jenchuu, @stephaniestahlberg can we add the qualifier page user flow to the Task and user flow diagram? This way we can refer to just one document

**Comment by Aveline-art** [comment]
Closed because all resources have been compiled and listed in [this wiki](https://github.com/hackforla/CivicTechJobs/wiki/Resources).
