### ISSUE TITLE
Fix dev onboarding installation instructions

### ISSUE THREAD

**Issue by LoTerence** [hackforla/CivicTechJobs#590]
### Overview
As a new developer joining the team, I should be able to set up a development environment on my computer without much trouble.

When assisting Roja set up the development environment on her local machine, I came across some issues that should ideally be resolved to make it easier for future devs to start coding.

Issues:
- Installation instructions documentation is outdated
- `docker compose up` doesn't work out of box. We need to use the `docker-compose.dev.yml` file which can be confusing and unclear for new developers joining the project.
- building frontend static files blocks the vite development server from being served by django for some reason. This was not caused by using git checkout with the main branch.
- docker compose up `--watch` flag didnt work at first

Steps should simply be:
1. make a `dev.env` file
2. run `docker compose up --watch`

I'd like for it to be as easy as possible for new devs to get started working on the project.

### Action Items

- [x] merge `docker-compose.dev.yml` with the original `docker-compose.yml` file
- [x] There should be one `docker compose up` command that works
- [x] Investigate frontend build issue. Make sure django always serves the vite development server, even if there are static build files

After the above is done:
- [x] Update the dev installation instructions documentation
  - [x] Include instructions to download the latest version of docker
- [x] Update dev onboarding issue template with new documentation (`ISSUE_TEMPLATE/dev_onboarding.md`). (*Warning: at the momemnt, this file is only in the `main` branch. It is not in the `development` branch*)
 
(Update 10/09/2024): Moving this action item to a new Issue:
- [ ] #598

### Resources/Instructions
https://hackforla.github.io/CivicTechJobs/developer/installation/

**Comment by nooriaali9** [comment]
Hi @LoTerence the Role for this issue is missing, will you be able to update that?

**Comment by LoTerence** [comment]
> Investigate frontend build issue

Could not recreate frontend build issue. Skipping this.

**Comment by LoTerence** [comment]
Done
