### ISSUE TITLE
Add documentation about the two different branches: `main` and `develop` and how they work.

### ISSUE THREAD

**Issue by LoTerence** [hackforla/CivicTechJobs#598]
As a developer I need to understand why there are two different branches and how to use them.

This issue loosely depends on #610 , #608 

### Action Items

- [x] Separate `ava-main-v1` and new main (v2)
- [x] Write documentation about two branches
- [x] Write documentation about `ava-main-v1`

### Resources:

[A successful Git branching model » nvie.com](https://nvie.com/posts/a-successful-git-branching-model/)

**Comment by nooriaali9** [comment]
Hi @LoTerence added backend as the role, please correct it if it seems incorrect, and then move it to inprogress/prioritized backlog
