### ISSUE TITLE
Design System Component: Compound: Header Navigation

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#60]
### Dependency

- [x] #61 
- [x] #66 
- [x] #68 

### Overview
As a developer, we should start with a component first philosophy when creating new webpages. For this issue we will be developing the header navigation of the Landing Page.

### Action Items

- [ ] Review the design for the header nav element in the landing page in the Figma page indicated below
- [ ] Be sure to review our architecture documentation to understand where to create and find files relevant to this component
- [ ] Make sure that the component is:
  - [ ] Responsive, and that the items adjust themselves as screen size changes
  - [ ] Change from the desktop to mobile design after the mobile breakpoint
  - [ ] Stickied at the top and will shift the neighboring elements down, via selectors
- [ ] Release dependency on:
  - [ ] #73 
 
### Resources/Instructions
[Figma, Landing Page](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A7)

**Comment by Aveline-art** [comment]
@jenchuu I have a couple of clarification questions.

1. The [horizontal svg ](https://github.com/hackforla/CivicTechJobs/blob/main/frontend/src/assets/images/svgs/logo-horizontal.svg) contains some amount of empty space between the logo and the image's edge. This makes it impossible to center the image correctly. Can we resize this image?
2. The mockup for the landing page mobile does not currently contain an expanded view of how the hamburger menu will look. Will the expanded menu be included soon? Or would it take some time to prototype?

**Comment by jenchuu** [comment]
@Aveline-art 
1. I've edited the horizontal svg to make it easier to center - I'll comment you where it is in Figma. or how would you like me to send it to you?
2. How soon do you need the hamburger menu? We were prioritizing the other pages to design in the flow as we are still not 100% on the nav bar menu items.

**Comment by Aveline-art** [comment]
Hi @jenchuu !

If the svg is in the design system page, I can find it on my own. Is that where you store all the assets?

For the burger menu, I don't really need it at all. We can open a new issue once the design team has it read, and I can leave it as is for now.

**Comment by jenchuu** [comment]
@Aveline-art yes assets are in Figma. I also believe Ingrid and Cherri saved copies of the assets in the Google drive.
