### ISSUE TITLE
Create Models for Projects, COPs and Roles and Skills

### ISSUE THREAD

**Issue by bzzz-coding** [hackforla/CivicTechJobs#614]
### Overview
As a developer, I would like to create models for Projects, COPs, Roles and Skills based on the [new data schema diagram ](https://dbdiagram.io/d/hfla-civic-tech-jobs-671ad87097a66db9a333224e)

**Comment by LoTerence** [comment]
CTJ requirements

CTJ is responsible for:
- 1. Taking job postings from the projects that have
- CTJ is not responsible for project data
	- project data should come from people depot
- Job posters pick a project from the list
- 2. Skills matrix
- Ranking skills
- 3. Asking about user availability
- People depot will store User availability, all the user information
