### ISSUE TITLE
Create Models for Users, Opportunities, and Skill Matrices

### ISSUE THREAD

**Issue by bzzz-coding** [hackforla/CivicTechJobs#618]
### Overview
As a developer, I would like to create models for users, opportunities, and skill matrices based on the [new data schema diagram](https://dbdiagram.io/d/hfla-civic-tech-jobs-671ad87097a66db9a333224e)

### Action Items
- [ ] Create new models for users and skill matrices
- [ ] Update existing Opportunities model
- [ ] Create serializers
- [ ] Register models

**Comment by LoTerence** [comment]
Leaving this link here for future reference: https://dev.to/azayshrestha/working-with-json-and-jsonb-data-types-in-django-with-postgresql-4h00

I am going to need it for documenting the CTJ API
