### ISSUE TITLE
Design System Component: Compound: Footer Navigation

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#65]
### Dependency

- [x] #61 
- [x] #66 
- [x] #67 
- [x] #68 

### Overview
As a developer, we should start with a component first philosophy when creating new webpages. For this issue we will be developing the footer navigation of the Landing Page.

### Action Items

- [ ] Review the design for the footer navigation element in the landing page in the Figma page indicated below
- [ ] Be sure to review our architecture documentation to understanding where to create and find files relevant to this component
- [ ] Make sure that the component is:
  - [ ] Responsive, and that the items adjust themselves as screen size changes
  - [ ] Change from the desktop to mobile design after the mobile breakpoint
- [ ] Release dependency on:
  - [ ] #74 

### Resources/Instructions
[Figma, Landing Page](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A7)

**Comment by slavdefense** [comment]
I need help on xyz. Here are some screenshots. Here is a link to my repositories branch for you take a look. 
![Line 152](https://user-images.githubusercontent.com/77471354/154186059-76d106f7-2609-4b87-9e60-c9162c12b69a.png)
