### ISSUE TITLE
Design System Component: Element: Modal Cards

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#66]
### Dependency

- [x] #62 
- [x] #63 
- [x] #69 
- [x] #70 
- [x] #71 
- [x] #72

### Overview
As a developer, we should start with a component first philosophy when creating new webpages. For this issue we will be developing the modals of the Landing Page.

### Action Items

- [ ] Review the design for the modal element in the landing page in the Figma page indicated below
- [ ] Be sure to review our architecture documentation to understand where to create and find files relevant to this component
- [ ] Make sure that the component is:
  - [ ] Responsive, and that the items adjust themselves as screen size changes (if applicable)
  - [ ] Change from the desktop to mobile design after the mobile breakpoint (if applicable)
- [ ] Release dependency on:
  - [ ] #60
  - [ ] #65 

### Resources/Instructions
[Figma, Landing Page](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A7)

**Comment by Aveline-art** [comment]
@jenchuu Does the design team have any thoughts on how transitions should work? For example, for the modal, when the close button is clicked, should the modal fade out or perform an immediate exit? We can also play this by ear once the landing page is done and the team can perform on-site testing.

**Comment by jenchuu** [comment]
@Aveline-art For modal card example, let's do an immediate exit! *Yes, interactions and micro-interactions may change pending testing.
