### ISSUE TITLE
Tech Stack Documentation

### ISSUE THREAD

**Issue by sharadgaurav7** [hackforla/CivicTechJobs#7]
Akib, and Sarah to create system design documentation for the civictechjobs.org website

**Comment by arghmatey** [comment]
Notes from Akib from an issue on the website repo (from when this was going to be a feature of the Hack for LA site):

### Determine which technologies need to be used.
Confirmed using react as front end with potentially redux
Express as the backend
Postgres as the database
Ensure application is containerized with docker.

### Determine the monetary costs of using these technologies.
Currently negligible as we will be running on the free tiers.

**Comment by sharadgaurav7** [comment]
@arghmatey
Sarah, please post the tech stack pointers from Akib here,

**Comment by ExperimentsInHonesty** [comment]
Add information to page on the wiki
