### ISSUE TITLE
Landing Page: Top Portion

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#73]
### Dependency

- [x] #60 

### Overview
As a developer, we need to combine our components into our product so that we can deliver to stakeholders! For this issue, we will create the top portion of the landing page.

### Action Items

- [ ] Review the top portion of the landing page (this is everything above the CoP circles but does not include the CoP circles)
- [ ] Create the top portion
  - [ ] Note that, we preferably would not hard-code spaces (this is not responsive), but use the spacing utilities instead. Some classes have hard-coded spacing built in, so be sure to exchange them for the spacing utility classes.
- [ ] Release dependency on:
  - [ ] #79
  - [ ] #96 
  - [ ] #120

### Resources/Instructions
[Figma, Landing Page](https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A7)

**Comment by sdimran** [comment]
Hi @Aveline-art, this is good to work on -- i saw the dependency is cleared so will move this into the prioritized backlog, Thanks!

**Comment by Aveline-art** [comment]
I think I can lower the size, although I set it at 13+ as a precaution, to prevent an inexperienced developer from working on it.
