### ISSUE TITLE
Research Viability and Implementation of Staging Website

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#78]
### Overview
As a developer, we need to ensure that our work is easy for the team to review and comment on. For this issue we will conduct all the work needed to create a staging version of our product.

### Action Items

- [x] Research uploading the website onto a host/server
  - [x] Also research ways to have the repo (this repo) selectively upload to the staging or production website
- [x] Create a configuration proposal in the form of code
  - [x] This includes configurations as part of our frontend, backend, and database
  - [x] This also includes configurations based on infrastructure as code
  - [x] The proposal must make security as its top priority
    - [x] As part of this research how passwords to our various servers are encrypted, and how to prevent client access; make sure that the tools used for our servers provides this kind of protection
- [x] Find out whether we can create a "https://staging.civictechjobs.org" website with the civictechjobs.org domain alone
- [x] Implement the staging website
  - [x] Be sure to discuss with the ops team on how our env variables are protected/encrypted to prevent leaking it out
- [x] Edit the pull-request-template.md to include photos of visual changes.
- [ ] Update documentation on devOps details
- [x] Release
  - [x] #189 

### Resources/Instructions
[Link to current deployment plan](https://github.com/hackforla/CivicTechJobs/issues/78#issuecomment-1033233215)
[OWASP Top Ten](https://owasp.org/www-project-top-ten/)
[White-noise](http://whitenoise.evans.io/en/stable/)

The Ops team at HackForLA manages hosting our various projects. Please make contact with them through Slack under the #ops channel. The stack that they are using are Terraform and AWS, so focus research on those tools.

Concerning the selective upload, GitHub natively have ways of doing this. The slightly more dangerous way is to have two GitHub actions, which runs on dispatch to either the staging or production environment. This is potentially dangerous since reverting is difficult if the the wrong dispatch is accidentally ran without a history of which commit was previously hosted. The better way would be to link it to [Github release ](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)system, since releases are very purposeful. The final solution might involve a bit of both, but please do broad research on possible options!

**Comment by Aveline-art** [comment]
Questions:

1. When we say 'staging website' what differentiates it from a production website?
2. What problem is the staging website trying to solve, or what is it about that the production website lacks that can be solved with a staging website?
3. What kind of configurations are most optimal when doing AB testing?
4. What QoL features can be have for a staging environment for the team when they are reviewing the staging website?

**Comment by sdimran** [comment]
Hi @Aveline-art, as discussed though we may not need the full capabilities of a staging site for our landing page initial, when we get closers to our mvp it will be a need. Bonnie confirmed that the drive space will not time out so lets utilize it and get comfortable with  working within the staging environment even for landing page initial. 

lets go through with getting that set up

**Comment by Aveline-art** [comment]
@sdimran I've noticed you've directly assigned me to this? Does this mean I need to prioritize this over my other assigned issue? Please let me know how I should proceed with this.

**Comment by sdimran** [comment]
Hi @Aveline-art, my mistake! totally forgot to just put it back into the backlog and leave the assignee empty  -- ill unassign you now and you can prioritize based on your capacity

**Comment by Aveline-art** [comment]
Assigning myself this issue to periodically relay updates on my communications with the ops team

Jan 12, 2022

- spoke with ops team about requirements (thank you @arghmatey for meeting with them at the CoP meeting)
- waiting to hear back from them as they examine our DockerFiles

**Comment by Aveline-art** [comment]
Jan 10, 2022

- Ops team reported back after examining DockerFiles
- Currently arranging a meeting to go over configuration requirements before staging website can go live

**Comment by Aveline-art** [comment]
Jan 26, 2022

- Ops team is behind on arranging a meeting due to internal issues. As of now, there is no meeting planned and we are unsure when it will happen.

**Comment by sdimran** [comment]
thank you for the updates @Aveline-art !

**Comment by Aveline-art** [comment]
The ops team has gotten back to me with some minimum requirements for deployment:

- [ ] production settings are in place
- [ ] the docker container runs when using production settings

**Comment by Aveline-art** [comment]
Update March 22, 2022:

Research stage is complete. The current implementation plan for a staging environment involves

- Set up our technologies for production; this is done since the staging environment should closely follow production, only that the database is not the one used for production
- Using nginex as our webserver
- Using Amazon EC2 to upload our docker container
  - Add other services as needed, although there are no plans for those as of now
- Continue to use PostgreSQL as our database, if only for staging purposes
- Have a framework for writing stress tests to tests the ability of our server
- Give numerical estimates on our storage, memory, and bandwidth needs so that we can compute accurately our costs

The next step is to complete a demo of how the staging environment would look like.

**Comment by Aveline-art** [comment]
Current directory structure:

```yml
├── .github/ # GitHub
│   └── ISSUE_TEMPLATE/
├── config/ # Backend
├── docker/ # Backend
├── frontend/    # Frontend
│   ├── migrations/
│   ├── src/    # Frontend
│       ├── assets/    # Frontend
│       ├── components/    # Frontend
│       ├── pages/    # Frontend
│       ├── router/    # Frontend
│       └── templates/    # Frontend
│   ├── static/    # Frontend
│       └── frontend/    # Frontend
│   └── templates/    # Frontend
│       └── frontend/    # Frontend
├── server/ # Backend
│   └── migrations/
└── <loose files> # Frontend
```
*<p style="text-align: center;">Overall project structure</p>*

**Comment by Aveline-art** [comment]
Update Mar 30, 2022

- Got application layer (gunicorn) and server layer (nginx) to work with docker
- Webpack is not building production files correctly during the dockerfile's build step, will debug

**Comment by Aveline-art** [comment]
### Update April 1, 2022

- Finished with everything as far as our side is concerned.
  - One thing I could not test was https settings since I need a valid ssl certification for it (there are options to create a dummy, however, but the process is rather complex)
  - Therefore, ssl certs should be tested once we are live
- The next steps are:
  - Create a demo on what kind of AWS tools we can use and what settings we need to make this work
  - Secure our servers by configuring nginx and gunicorn
  - Consult an experienced devOps developer on the security of our current infrastructure

**Comment by Aveline-art** [comment]
### Update April 14, 2022

- Met with Ops team to discuss our configurations
- Recommendations and improvements:
  - Remove nginx and use whitenoise to reduce server costs
  - (optional) Reduce app size by pooling everything into the server or config directory



@sdimran @sharadgaurav7 After meeting with the Ops team, we have come to the conclusion that we need to cut and reduce costs for our configuration. These measures would take time, however. Below are several plans to move forward. Please select the one we would prefer.

- [ ] **Do not do a reduction.** This means that we can host right now.
  - *Pro:* No more additional work.
  - *Pro:* Greater community support.
  - *Con:* Monetarily costly for little benefit.
  - *Con:* Adds unnecessary bloat.
- [ ] **Do a small reduction.** This will take an estimated 4 weeks to finish.
  - *Pro*: Relatively quick to implement.
  - *Pro*: Removes the costliest component.
  - *Pro*: Removes bloat.
  - *Con*: Small community support.
- [ ] **Do a large reduction.** This will take about 8 or more weeks to finish.
  - *Pro*: Most cost effective.
  - *Con*: Very difficult to implement and could take a long time.
  - *Con*: Almost no community support

**Comment by sdimran** [comment]
@Aveline-art for option 2 when you mention the con as small community support, could you expand on what that means?

**Comment by Aveline-art** [comment]
Community support means that there is not a large community of developers who uses a certain technology. When something has less community support, it is harder to find solutions to obscure problems or there might not be strict best practices in place.

**Comment by Aveline-art** [comment]
Reopening this as there is still more work to be done before this can be completely closed

**Comment by gjagnoor** [comment]
Notes from Ops meeting on 11/9/2022

Tasks - 
1. Db - Kevin will set DB instance credentials for CTJ using aws lambda 
2. Landing Page - We need to build a coming soon page   
3. DNS - Kevin is going to set up an [issue for Bonnie](https://github.com/hackforla/ops/issues/64#issue-1443136984) using the template they built together

What CTJ needs right now - 

We want to focus on the staging environment. So that non-developers on the team can see the site before it goes live. We don’t need anything too heavy in terms of resources. We just need to get this up so people can use it and see it. 

Concerns - 

- Staging and production cannot use the same tables. Do we know what strategy we have to be able to avoid this, incase it is using the same tables?
      - How does RDS shard data — how do people see it in AWS

**Comment by Aveline-art** [comment]
> FYI, I believe that currently, all DB user accounts (e.g. civictechjobs_stage vs cti_dev) can access any DB in the RDS instance

That's not good... Is there a way to limit access so that we lower the risk of cross-contaminating data? The worst situation is if someone added test data from staging into the production database as we'll need to manually verify and delete it.

If not, I think we need to reconsider the value of using our sole RDS for staging. What ways do we have of testing integration without using the sole RDS instance in staging?
