### ISSUE TITLE
Add GitHub to our Navigation

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/CivicTechJobs#79]
### Dependency

- [x] #73 
- [x] #74 

### Overview

As a developer, nothing excites me more about a project than to see its GitHub repository. For this issue, we will make minor edits to our navigation to include a link to our repository, to attract more, potential open-source developers.

### Action Items

- [ ] Add a GitHub link or icon to our Figma design for our footer or header, whichever makes more sense
- [ ] After edits have been edited, create an issue for development to add the icon to our website

### Resources/Instructions

[GitHub Logos and Usage](https://github.com/logos)

#### Examples of headers/footers with GitHub links

[Sample - MkDocs](https://www.mkdocs.org/)
[Sample - MUI](https://mui.com/)
[Sample - React](https://reactjs.org/)
[Sample - Webpack](https://webpack.js.org/)
[Sample - TensorFlow](https://www.tensorflow.org/)

**Comment by nooriaali9** [comment]
Closing this issue - since it is outdated/ not a priority anymore - based off of https://github.com/hackforla/CivicTechJobs/issues/552
