### ISSUE TITLE
Navigation bar items for landing page

### ISSUE THREAD

**Issue by jenchuu** [hackforla/CivicTechJobs#80]
### Overview

We need the navigation bar menu items and potentially a sitemap to give structure to CTJ's website.

### Action Items

- [ ] Figure out MVP's nav bar menu items

### Resources/Instructions

<img width="647" alt="CTJ Landing page nav bar menu items" src="https://user-images.githubusercontent.com/88695763/146247992-e6837bfb-58ea-4afd-b828-f37dc81743b4.png">

**Comment by sdimran** [comment]
Trying to understand what the goal is for the projects and roles choices in the nav bar. Roles are covered in our landing page front page under the communities of practice and Projects come from HackforLA website which users can see if the select the Hack for LA icon. @jenchuu is it part of the design that the nav bar will be the same for both the landing page and the search page?

**Comment by sharadgaurav7** [comment]
@jenchuu , Danish, and I had a chance to review. We would like to take out the "Roles" option, and add in "Post New Position" (We would need better options, we can't use the term JOB). This "Post" option will lead to the CMS system. 

Other notes: Links in our menu row will lead to these respective pages
1. Hackforla link leads to landing page for the hackforla webpage (let's check if there is a new page designed)
2. How to Join link leads to https://www.hackforla.org/join
3. Projects will lead to https://www.hackforla.org/projects/

**Comment by jenchuu** [comment]
@sdimran @sharadgaurav7 Hi the nav bar menu items were placeholder items and not based on any research. The nav bar will be across the entire CTJ website; yes it will show for both the landing page and search page.

Thank you for defining the nav bar items and where each will lead to! We'll change the designs to reflect these changes.

**Comment by jenchuu** [comment]
Below is nav bar options A and B.

Option A: secondary ghost "Donate" button and primary "Post a Position" button
<img width="817" alt="Final nav bar option A" src="https://user-images.githubusercontent.com/88695763/147011855-11cddc1d-d51c-44a0-8b0a-cd9c09fb0dc6.png">

Option B: secondary light blue "Donate" button and primary dark blue "Post a Position" button
<img width="817" alt="Final nav bar option B" src="https://user-images.githubusercontent.com/88695763/147011989-b16339ec-a8f9-4594-bcc3-08203f93d826.png">

I prefer option A.. Thoughts?

**Comment by jenchuu** [comment]
Per discussion with @sdimran and @ExperimentsInHonesty below is updated nav bar with one login CTA for both volunteers and team leads (backend will be able to recognize the two types of users)

<img width="888" alt="Nav bar" src="https://user-images.githubusercontent.com/88695763/148712669-83d6eb46-aa03-4bde-a272-23b537df9ca0.png">

**Comment by jenchuu** [comment]
@sdimran @sharadgaurav7

Can you confirm the nav bar items and names? Did we decide that "Projects" will lead to search page for project roles OR are we renaming it?
I'd like to ensure our IA and create a sitemap once we have the nav bar items confirmed so we ensure we have all the pages we need to design for.

**Comment by sdimran** [comment]
Hi @sharadgaurav7 have we come to a final decision on this issue? i would like to have it solidified so that UX can finalize and hand it off to Dev

**Comment by jenchuu** [comment]
@sdimran @sharadgaurav7 Sharad mentioned comments about possibly needing two log in buttons? Where might the comments regarding this idea be?

**Comment by stephaniestahlberg** [comment]
Instead of having two logins, how about after the user logins, there is an option to browse roles or post a role? That seems more intuitive. Especially compared to a CMS button that most people won't know what it means. 

The option to post a role might be restricted to certain roles/accounts, right? I don't know how exactly that would work, but if I understand correctly, we don't want anyone with a HfLA account to have the option to post a role. Since it would be restricted, the option to "post a role" could appear only for those authorized to do so.

**Comment by jenchuu** [comment]
Thanks for explaining @sharadgaurav7 
The designers and I agree with @stephaniestahlberg
 
I thought we had agreed we would have ONE log in for both volunteers and teams - with the backend being able to recognize the user type. Once a team lead is logged in, there would be a dropdown menu with CMS type options.

**Comment by sharadgaurav7** [comment]
@stephaniestahlberg , @jenchuu  we have argued for and against each of these options. Based on our discussions, we strongly believe  using a separate login will reduce the number of steps and reduce confusion. 

I will recommend moving ahead with the two logins, and let the data prove or unprove the hypothesis.

**Comment by jenchuu** [comment]
@sharadgaurav7 OK, we have changed the nav bar items in desktop and mobile to reflect this:

Desktop
<img width="1085" alt="CTJ nav bar items (desktop)" src="https://user-images.githubusercontent.com/88695763/157349889-1328776e-54ba-43ce-966e-c0a8f7323a5a.png">

Mobile
<img width="465" alt="CTJ hamburger menu items (mobile)" src="https://user-images.githubusercontent.com/88695763/157349906-9a176b90-e1f1-4641-a67d-6e901c2ed704.png">

**Comment by sharadgaurav7** [comment]
> @sharadgaurav7 OK, we have changed the nav bar items in desktop and mobile to reflect this. Moved to Review column.
> 
> Desktop <img alt="CTJ nav bar items (desktop)" width="1085" src="https://user-images.githubusercontent.com/88695763/157349889-1328776e-54ba-43ce-966e-c0a8f7323a5a.png">
> 
> Mobile <img alt="CTJ hamburger menu items (mobile)" width="465" src="https://user-images.githubusercontent.com/88695763/157349906-9a176b90-e1f1-4641-a67d-6e901c2ed704.png">

@ExperimentsInHonesty , we need you to review this and provide your feedback. Will add this to our agenda item for the meeting on 3/13/22

**Comment by jenchuu** [comment]
Edited mobile hamburger menu:
<img width="437" alt="CTJ hamburger menu items (mobile)2" src="https://user-images.githubusercontent.com/88695763/159293503-53c42cd0-eb5e-4159-9f98-b40151563a1b.png">

**Comment by sdimran** [comment]
@jenchuu @sharadgaurav7 and I compared notes and had a discussion -- can we make the "Team Lead/Post a role" button read as "CMS Log in" and have a tooltip on the top right with the description : "If you are a team lead/PM at HackforLA, use this to post a role/view the dashboard". lets plan to go live with this version of the nav bar and see the feedback

**Comment by jenchuu** [comment]
@sdimran @sharadgaurav7 
Changed to CMS Log in. Can you explain why you think a tooltip is needed? I don't see the need or fit here... I can see that description fitting better on the CMS Log in page at top once a user clicks on the button.

Please see revised nav bar items below:
<img width="998" alt="CTJ nav bar items (desktop) 2" src="https://user-images.githubusercontent.com/88695763/160217877-7b1d88d1-b9a6-4ac8-a5cb-961b1000b248.png">

<img width="435" alt="CTJ hamburger menu items (mobile)3" src="https://user-images.githubusercontent.com/88695763/160217996-f89f02b6-8027-42db-9f62-8457184cd645.png">

**Comment by sdimran** [comment]
Looks good @jenchuu. with regards to the tooltip, this was to give users some clarity in case they were wondering what CMS log in means, but also agree that having that description at the top of the log in page itself once clicked would satisfy that. we can go with your suggestion(this can include a link to the normal user log in page where they should have gone). thoughts @sharadgaurav7

**Comment by sdimran** [comment]
@jenchuu  is there an update on this? we had a discussion during our team meeting regarding the tooltip question. we are okay to use your suggestion.

**Comment by sdimran** [comment]
This is final and complete, good to close.
