### ISSUE TITLE
UX Design: Landing Page Wireframe for civictechjobs.org Option 1

### ISSUE THREAD

**Issue by sharadgaurav7** [hackforla/CivicTechJobs#9]
Overview
We need to design the webpages for civictechjobs.org so that a user (potential volunteer) can easily search for a volunteer opportunity that fits their skills or aspirations.

Resources/Instructions
https://www.figma.com/file/G5bOqhud6azbxyR9El9Ygp/Civic-Tech-Jobs?node-id=1%3A7

**Comment by sdimran** [comment]
PM's to meet with UX to discuss User flow schema

**Comment by Aveline-art** [comment]
Closed because done
